import type { Metadata } from 'next';
import SiteHeader from '@/components/v2/SiteHeader';
import SiteFooter from '@/components/v2/SiteFooter';
import { AU_FOOTER_COLUMNS } from '@/data/auFooterColumns';
import HeroInlineForm from '@/components/HeroInlineForm';
import Breadcrumbs from '@/components/v2/Breadcrumbs';
import ModalCTAButton from '@/components/v2/ModalCTAButton';
import MidPageCTA from '@/components/v2/MidPageCTA';
import '../au-service.css';

const CANONICAL = 'https://factoryjet.com/au/ai-development';
const UPDATED = '2026-09-25';
const TITLE = 'AI Development Company Australia | Custom AI | FactoryJet';
const H1 = 'The AI Development Company for Australian Businesses That Want AI Inside the Systems They Already Run';
const DESCRIPTION =
  'AI development company in Australia for SMEs and mid-market. Custom AI development, AI integration with Xero, MYOB, CRM and ERP, and AI implementation you own.';

/* Design tokens, copied by value from ../au-service.css so inline styles stay
   on-system without CSS custom property references in this file. */
const T = {
  ink: '#0F0F12',
  n200: '#E5E5E0',
  n400: '#6E6E68',
  orange: '#FF5C00',
  green: '#047857',
  small: '#B23E13',
  fm: "'Geist Mono',monospace",
  fd: "'Plus Jakarta Sans',sans-serif",
};

/* ONE array drives the visible trail AND the BreadcrumbList JSON-LD, so the
   schema can never describe a trail a human cannot see. Never hand-copy a
   second list here. */
const crumbs = [
  { name: 'FactoryJet', url: 'https://factoryjet.com' },
  { name: 'Australia', url: 'https://factoryjet.com/au' },
  { name: 'AI Development', url: CANONICAL },
];

/* ─── External sources, each fetch-verified 2026-09-25 (HTTP 200, claim
       confirmed in the fetched body) ──────────────────────────────────── */
// OAIC, Guidance on privacy and the use of commercially available AI products
// (21 Oct 2024, updated 17 Jan 2025): "Privacy obligations will apply to any
// personal information input into an AI system, as well as the output data
// generated by AI (where it contains personal information)"; recommends
// organisations do not enter personal information, particularly sensitive
// information, into publicly available generative AI tools; recommends a
// privacy by design approach including a Privacy Impact Assessment.
const SRC_OAIC_PRODUCTS =
  'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-the-use-of-commercially-available-ai-products';
// OAIC, Guidance on privacy and developing and training generative AI models
// (21 Oct 2024): developers must take reasonable steps to ensure personal
// information is accurate; PIA as part of privacy by design at planning stage.
const SRC_OAIC_DEV =
  'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-developing-and-training-generative-ai-models';
// OAIC, APP quick reference: 13 APPs; APP 8 cross-border disclosure; APP 10
// quality; APP 11 security of personal information.
const SRC_OAIC_APPS =
  'https://www.oaic.gov.au/privacy/australian-privacy-principles/australian-privacy-principles-quick-reference';
// AWS Regions list: ap-southeast-2 Asia Pacific (Sydney), ap-southeast-4 Asia
// Pacific (Melbourne), both Australia.
const SRC_AWS_REGIONS = 'https://docs.aws.amazon.com/global-infrastructure/latest/regions/aws-regions.html';
// Microsoft Learn, list of Azure regions: Australia East = New South Wales.
const SRC_AZURE_REGIONS = 'https://learn.microsoft.com/en-us/azure/reliability/regions-list';

/* ─── FAQ source of truth (drives UI + FAQPage schema) ─────────────── */
const FAQ_CATEGORIES = [
  { key: 'basics',   label: 'AI development basics' },
  { key: 'choosing', label: 'Choosing an AI development company' },
  { key: 'delivery', label: 'Timelines, cost & how it works' },
  { key: 'data',     label: 'Data, privacy & Australian rules' },
] as const;

const FAQ_ITEMS: { category: string; question: string; answer: string }[] = [
  // ── AI development basics ──
  { category: 'basics', question: 'What is AI development?',
    answer: 'AI development is designing, building, testing and running software that uses artificial intelligence to do a useful job in a business. Today that usually means software built around a large language model, the kind of AI behind ChatGPT and Claude, connected to your own data and systems. It covers the whole path: picking the job, preparing data, building, testing accuracy, going live and keeping it working.' },
  { category: 'basics', question: 'What are AI development services?',
    answer: 'AI development services are the pieces of work an AI development company offers. The usual list is custom AI software development, AI integration with your existing systems, AI implementation from pilot to daily use, search and question answering over your own documents, data preparation, accuracy testing, and support after launch. Most Australian projects use three or four of these together rather than one on its own.' },
  { category: 'basics', question: 'What is AI integration?',
    answer: 'AI integration means connecting AI to the software your business already runs, so it can read the right information and put its results in the right place. For example, AI that reads a supplier invoice and drafts the bill in Xero, or summarises a customer’s history inside your CRM before a call. The value comes from the connection, not from the AI model sitting on its own.' },
  { category: 'basics', question: 'What are some examples of AI integration?',
    answer: 'Common ones for Australian businesses: coding supplier bills in Xero or MYOB from emailed invoices; keying emailed purchase orders into an ERP as draft sales orders; summarising long ticket threads in a helpdesk; drafting product descriptions from supplier spreadsheets in Shopify; and a Microsoft Teams assistant that finds the right policy in SharePoint. Each one removes a repeated copy-and-paste step.' },
  { category: 'basics', question: 'What is AI implementation?',
    answer: 'AI implementation is the step from a promising idea or demo to AI your team uses every day. It covers the work most demos skip: preparing real data, connecting to real systems, testing accuracy on real cases, setting permissions, meeting Privacy Act duties, training staff, monitoring results and fixing problems. It is where most AI projects either succeed or quietly stall.' },
  { category: 'basics', question: 'What is RAG, in plain English?',
    answer: 'RAG stands for retrieval-augmented generation. Think of it as an open-book exam. Before the AI answers, the system looks up the most relevant pages from your own documents, hands them to the AI, and tells it to answer only from those pages. That is how AI can answer from your price list or returns policy instead of guessing, and show you where each answer came from.' },
  { category: 'basics', question: 'Can Python be used for AI development?',
    answer: 'Yes. Python is the most common language for AI development, because most AI libraries and model tools are written for it first. We use Python for data preparation, retrieval and model work, and TypeScript for the parts your team clicks on and for many integrations. The language matters less to you than who maintains it, so we document everything and hand you the code.' },
  { category: 'basics', question: 'Is an AI agent the same as AI development?',
    answer: 'No. An AI agent is one thing an AI development company can build: AI that takes actions across your systems within rules you set, such as rebooking a delivery or chasing an overdue invoice. AI development is the wider field, which also covers document search, integrations, data tools and internal apps. For agents specifically, see our AI agents page for Australian businesses.' },

  // ── Choosing an AI development company ──
  { category: 'choosing', question: 'What are the top AI development companies in Australia?',
    answer: 'It depends on your size and the job. Names that come up often in Australian searches include Avenue Group in Perth, Osher Digital in Brisbane, ZenityAI, EB Pearls and Microknot in Sydney, Vrinsoft in Melbourne, and Red Marble AI. Larger enterprises also use the big consultancies. We list several, including us, on this page with a neutral note on each. Speak to two or three before choosing.' },
  { category: 'choosing', question: 'How do I choose an AI development company in Australia?',
    answer: 'Ask to see AI systems they have put live, not demos. Ask who will write the code and whether the same team supports it after launch. Confirm you will own the code, prompts and data. Ask how they measure accuracy, how they handle the Privacy Act and where your data will be hosted, and when they would tell you to buy a tool instead. Clear answers to all of these are a good sign.' },
  { category: 'choosing', question: 'Are you an Australian company?',
    answer: 'We work with Australian businesses remotely rather than from a local office, and we would rather say so up front. What we offer is a senior team, the founder involved on every project, systems hosted in Australian cloud regions where your data needs it, and code you own outright. If an onshore team is a hard requirement for you, the local firms listed on this page are good places to start.' },
  { category: 'choosing', question: 'Should I use a freelancer or an AI development company?',
    answer: 'A freelancer suits a small prototype or a single contained script. A company makes more sense when the AI must connect to several systems, handle personal information, or run every day for years. That work needs testing, security, holiday cover and someone on call when a connected system changes. Plenty of businesses start with a freelancer and move to a team once the idea proves itself.' },
  { category: 'choosing', question: 'Should we buy an off-the-shelf AI tool or build custom AI?',
    answer: 'Buy first when the job is general: writing, summarising, meeting notes or searching documents. Tools like Microsoft Copilot or ChatGPT Enterprise are quick to roll out. Build when the job depends on your own systems, pricing rules or data, or when a tool cannot reach the software your team uses. Most businesses end up with a mix, and we will tell you honestly which side each job falls on.' },
  { category: 'choosing', question: 'Do you work with businesses in Sydney, Melbourne, Brisbane and Perth?',
    answer: 'Yes. We work with businesses across Australia, including Sydney, Melbourne, Brisbane, Perth, Adelaide and Canberra, and regional towns too. AI development works well remotely: discovery workshops over video, a shared test environment from the early weeks, and regular demos of working software. What matters more than a postcode is who answers when something needs fixing.' },
  { category: 'choosing', question: 'Which companies offer AI integration services in Australia?',
    answer: 'Many software agencies now list AI integration services, from small specialists to large IT firms. The useful question is not who offers it but who has integrated with your specific systems before, such as Xero, MYOB, NetSuite, HubSpot or Zendesk. Ask each provider how they would connect to your stack and what happens when one of those systems releases an update.' },
  { category: 'choosing', question: 'Are you tied to one AI model or vendor?',
    answer: 'No. We do not resell any AI platform. We choose between models from OpenAI, Anthropic, Google, Microsoft Azure and open-source options based on accuracy on your test cases, where your data needs to stay, and running cost. We build so the model can be swapped later without rewriting the system, because the best model this year may not be the best next year.' },

  // ── Timelines, cost & how it works ──
  { category: 'delivery', question: 'How long does custom AI development take?',
    answer: 'A focused first project usually takes 6 to 14 weeks from kick-off to live use. Discovery takes 1 to 2 weeks, data preparation 1 to 4 weeks, a working prototype 2 to 4 weeks, the production build and integrations 3 to 8 weeks, and a pilot with real users 2 to 4 weeks. Phases overlap. Messy data and older systems stretch the timeline; a clear, narrow job shortens it.' },
  { category: 'delivery', question: 'How much does it cost to build a custom AI?',
    answer: 'It depends on scope, not a rate card, so we do not publish prices. The biggest cost drivers are how many systems the AI must connect to, how clean your data is, how accurate it needs to be, how much personal information it touches, and whether you want monthly support. We scope after a free first call and quote a fixed price per phase. Model usage is billed to you directly by the provider.' },
  { category: 'delivery', question: 'How do I develop my own AI?',
    answer: 'Start with one job, not a strategy document. Pick a repeated task where mistakes are low-risk and results are easy to measure. Check the data it needs. Try a ready-made tool first. If that falls short, build a small prototype, test it on real cases, run a short pilot with the people who do the job, then roll out with training and monitoring. Add the next job only after the first one works.' },
  { category: 'delivery', question: 'Can I build my own AI for free?',
    answer: 'You can build a simple prototype at little cost using free tiers and no-code tools, and it is a good way to test an idea. Running AI properly in a business is different: model usage is billed, connections need securing, and someone has to test, monitor and fix it. Free is fine for learning. For anything customers or staff rely on, plan for the build and the upkeep.' },
  { category: 'delivery', question: 'What are the stages of AI development?',
    answer: 'We use six: discovery, data preparation, model choice and prototype, production build and integration, evaluation and pilot, then launch with monitoring and support. Other firms name them differently, and you will see lists of five or seven. Every serious AI development life cycle tests accuracy before launch and keeps watching after it, because AI output can drift as your data and the models change.' },
  { category: 'delivery', question: 'What are the key principles when implementing AI?',
    answer: 'Five we hold to. Start with a measurable business problem. Keep a person checking outputs where mistakes matter. Use the least personal information you need. Test accuracy on real cases before launch and keep measuring after. And make sure you own and understand what was built, so you are never stuck with a black box that only one supplier can touch.' },
  { category: 'delivery', question: 'What is the 30% rule for AI?',
    answer: 'There is no official 30% rule. People use the phrase for different rules of thumb, most often that AI should take on a slice of a job, around a third, while people keep the judgment calls. We treat it as a reminder rather than a target: pick the repeatable part of a task for AI, keep a person on the decisions, and measure the real time saved instead of assuming a number.' },
  { category: 'delivery', question: 'What happens after the AI goes live?',
    answer: 'We stay on. Monthly support covers monitoring accuracy, fixing problems, updating prompts and connections when your systems change, and testing new models as they arrive. You get a plain report on how the system is used and where it gets things wrong. You can take support in-house at any time, because the code and documentation are yours. Who does the work: senior engineers, with founder Bhavesh Barot involved throughout.' },

  // ── Data, privacy & Australian rules ──
  { category: 'data', question: 'Does the Privacy Act apply to AI?',
    answer: 'Yes, whenever personal information is involved. The OAIC, Australia’s privacy regulator, says privacy obligations apply to any personal information put into an AI system, and to AI output that contains personal information. So the 13 Australian Privacy Principles, covering things like security, accuracy and overseas disclosure, shape how we design any AI that touches customer, patient or staff details.' },
  { category: 'data', question: 'Can our data stay in Australia?',
    answer: 'Yes, where you need it to. We can host the system, its database and its document search in Australian cloud regions, such as AWS Sydney or Melbourne and Microsoft Azure Australia East, and choose AI model options that process data in Australia where available. We document exactly which provider sees which data and where, so your privacy officer and your customers get a straight answer.' },
  { category: 'data', question: 'Should staff paste customer details into ChatGPT?',
    answer: 'No. The OAIC recommends organisations do not enter personal information, and particularly sensitive information, into publicly available generative AI tools. That is one of the most common reasons businesses come to us: staff are already using AI, but through personal accounts. A properly set up business tool or custom build gives them the same help without the privacy risk.' },
  { category: 'data', question: 'Do we need a Privacy Impact Assessment for an AI project?',
    answer: 'Often it is the sensible step. A Privacy Impact Assessment, or PIA, is a written check of how a project affects people’s personal information and how you will reduce the risks. The OAIC recommends a privacy by design approach for AI that includes a PIA. We flag it at discovery and give your privacy lead the data maps and design notes it needs.' },
  { category: 'data', question: 'Do we need perfect data before starting AI development?',
    answer: 'No. Checking whether your data is good enough for one specific job is part of the work. Many useful first projects run on data you already have in emails, documents, your CRM or your accounting system. If a job needs better data, we tell you exactly what to fix and in what order. What you do need is someone who knows the process well enough to judge whether the AI got it right.' },
  { category: 'data', question: 'Do we own the AI you build?',
    answer: 'Yes. The code, integrations, prompts, test sets and documentation are yours. We are not a platform you rent. If you move the work in-house or to another provider, it keeps running. You hold the accounts with the AI model providers and cloud hosts and pay them directly, with no markup through us.' },
  { category: 'data', question: 'What stops the AI from making things up?',
    answer: 'Nothing removes the risk completely, so we design around it. The AI answers from your own documents, shows its sources, says “I don’t know” when it does not, and a person approves anything that matters. Before launch we test it against a set of real questions with known answers, and we keep scoring it every month after launch.' },
];

/* ─── Named Australian AI development companies (open self-disclosure,
       ItemList). Each note is based on the company’s own homepage, fetched
       2026-09-25. ──────────────────────────────────────────────────────── */
const AI_DEV_COMPANIES: { name: string; note: string }[] = [
  { name: 'FactoryJet', note: 'That is us. A founder-led AI development company working remotely with Australian SMEs and mid-market firms. Strongest where AI has to connect to commerce and operations systems: Xero, MYOB, CRM, ERP, ecommerce, helpdesk and Microsoft 365. You own the code, and the same team supports it.' },
  { name: 'Avenue Group', note: 'Head office in Perth, with a presence in Melbourne and Sydney. Builds custom chatbots, machine learning, computer vision and agentic automation, and offers onshore data centre and cloud hosting from Perth.' },
  { name: 'Osher Digital', note: 'A Brisbane-based firm offering custom AI development, AI agent development, AI consulting, process automation and custom ERP software for clients across Australia.' },
  { name: 'ZenityAI', note: 'A Sydney-based AI engineering firm focused on government and enterprise work: custom models, agentic systems, governance and compliance frameworks, and secure deployment.' },
  { name: 'EB Pearls', note: 'A Sydney software company in Surry Hills with a delivery office in Kathmandu, building AI-native software, mobile apps, web and ecommerce platforms.' },
  { name: 'Microknot', note: 'A Sydney software development agency offering AI software development alongside custom software, web and mobile apps, data analytics and legacy system modernisation.' },
  { name: 'Vrinsoft', note: 'Established in 2008, based in Melbourne with a presence in Sydney, Adelaide, Brisbane and Perth. Offers AI development alongside mobile apps, custom software and web development.' },
  { name: 'Red Marble AI', note: 'An Australian AI specialist covering AI strategy and governance, product engineering, data science, generative AI solutions and AI literacy training.' },
  { name: 'AI Developers', note: 'An Australian AI development services company building AI agents, chatbots, machine learning and process automation across sectors such as legal, medical, transport and agriculture.' },
];

/* ─── JSON-LD (Organization is referenced by @id only, defined sitewide) ── */
const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Service',
      '@id': `${CANONICAL}#service`,
      name: 'AI Development Services Australia',
      serviceType: 'Custom AI development, AI integration and AI implementation',
      provider: { '@id': 'https://factoryjet.com/#organization' },
      areaServed: { '@type': 'Country', name: 'Australia' },
      url: CANONICAL,
      description:
        'Custom AI software development, AI integration into CRM, ERP, Xero, MYOB, ecommerce, helpdesk and Microsoft 365, and AI implementation from pilot to production: data preparation, retrieval over your documents, model choice, evaluation, security, Privacy Act and APPs, Australian cloud hosting where needed, monitoring and support. The client owns the code and data.',
      hasOfferCatalog: {
        '@type': 'OfferCatalog',
        name: 'AI development services',
        itemListElement: [
          'Custom AI software development',
          'AI integration services',
          'AI implementation',
          'Document search and question answering (RAG)',
          'AI evaluation and monitoring',
          'AI support and maintenance',
        ].map((n) => ({ '@type': 'Offer', itemOffered: { '@type': 'Service', name: n } })),
      },
    },
    {
      '@type': 'BreadcrumbList',
      '@id': `${CANONICAL}#breadcrumb`,
      itemListElement: crumbs.map((c, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: c.name,
        item: c.url,
      })),
    },
    {
      '@type': ['WebPage', 'Article'],
      '@id': CANONICAL,
      url: CANONICAL,
      name: TITLE,
      headline: H1,
      description: DESCRIPTION,
      inLanguage: 'en-AU',
      datePublished: '2026-09-25',
      dateModified: UPDATED,
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['h1', '[data-speakable="true"]'] },
      breadcrumb: { '@id': `${CANONICAL}#breadcrumb` },
      author: {
        '@type': 'Person',
        name: 'Bhavesh Barot',
        jobTitle: 'Founder & CEO',
        url: 'https://factoryjet.com/about',
        sameAs: [
          'https://www.linkedin.com/in/bhavesh-ai-gtm-expert/',
          'https://github.com/factoryjet-tech',
        ],
      },
      publisher: { '@id': 'https://factoryjet.com/#organization' },
      about: { '@id': `${CANONICAL}#service` },
    },
    {
      '@type': 'ItemList',
      '@id': `${CANONICAL}#companies`,
      name: 'AI development companies in Australia',
      itemListElement: AI_DEV_COMPANIES.map((a, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: a.name,
      })),
    },
    {
      '@type': 'FAQPage',
      '@id': `${CANONICAL}#faq`,
      mainEntity: FAQ_ITEMS.map((f) => ({
        '@type': 'Question',
        name: f.question,
        acceptedAnswer: { '@type': 'Answer', text: f.answer },
      })),
    },
  ],
};

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: CANONICAL, languages: { 'en-AU': CANONICAL, 'x-default': CANONICAL } },
  openGraph: {
    title: TITLE,
    description:
      'An AI development company for Australian SMEs and mid-market firms. Custom AI software, AI integration services and AI implementation into the systems you already run, with the Privacy Act designed in. You own the code.',
    url: CANONICAL,
    siteName: 'FactoryJet',
    locale: 'en_AU',
    type: 'website',
    images: [{ url: '/images/au/ai-development/ai-development-og.webp', width: 1200, height: 630, alt: 'AI development company Australia: a FactoryJet developer and a Sydney business owner reviewing a custom internal AI tool' }],
  },
  robots: { index: true, follow: true },
};

const srcNote = { fontFamily: T.fm, fontSize: 11, color: T.n400, marginTop: 12 } as const;
const srcLink = { textDecoration: 'underline' } as const;
const detailBody = { padding: '0 0 20px', maxWidth: 820 } as const;

/* Phased delivery: one array drives the <details> expanders. */
const PHASES: { n: string; t: string; w: string; d: string; out: string }[] = [
  { n: '01', t: 'Discovery', w: '1 to 2 weeks', d: 'We sit (on video) with the people who do the job, map the process step by step, and agree one measurable goal: hours saved, reply time, error rate or orders processed. We also make the build, buy or integrate call here, before you spend on engineering.', out: 'A one-page scope, a success measure, a fixed quote for the next phases.' },
  { n: '02', t: 'Data preparation', w: '1 to 4 weeks', d: 'We find where the information lives (shared drives, Xero or MYOB, your CRM, your shop, your inbox), check it is accurate and that you are allowed to use it this way, strip out personal information the job does not need, and set up secure, read-only access first.', out: 'A data map your privacy officer can read, and clean inputs for the prototype.' },
  { n: '03', t: 'Model choice and prototype', w: '2 to 4 weeks', d: 'We build a working prototype on your real data and try two or three AI models against a test set of real cases with known right answers. You see it working on your own examples, not a slide deck.', out: 'A working prototype, an accuracy score per model, and a recommendation.' },
  { n: '04', t: 'Production build and integration', w: '3 to 8 weeks', d: 'The prototype becomes proper software: connections to your CRM, ERP, accounting, shop, helpdesk or Microsoft 365, user permissions, logging, error handling, Australian hosting where needed, and a simple screen your team can use.', out: 'Production code in your repository, deployed to your cloud account.' },
  { n: '05', t: 'Evaluation and pilot', w: '2 to 4 weeks', d: 'A small group uses it on real work. We score accuracy, watch where it struggles, fix it, and confirm the goal from discovery is being met before anyone else gets access.', out: 'A pilot report: accuracy, time saved, issues found and fixed.' },
  { n: '06', t: 'Launch, monitoring and support', w: '1 to 2 weeks, then monthly', d: 'Rollout with short training, written usage rules, security checks and your privacy documents finished. After launch we watch accuracy and usage every month, update connections when your systems change, and test new models as they arrive.', out: 'A live system, a monthly report, and the same team on call.' },
];

/* "Which fits you" checklist: build vs buy vs integrate. */
const FIT: { t: string; s: string; items: string[]; link?: { href: string; label: string } }[] = [
  { t: 'Buy an off-the-shelf AI tool', s: 'Tick three or more and a ready-made tool is probably enough.',
    items: ['The job is general writing, summarising or meeting notes', 'Your team already works in Microsoft 365 or Google Workspace', 'No customer or patient data needs to go into it', 'You do not need it to write anything back into your systems', 'You want something live this month'] },
  { t: 'Integrate AI with the tools you already run', s: 'Tick three or more and an AI integration project fits.',
    items: ['People copy information between two systems every day', 'You run Xero, MYOB, a CRM, an ERP or a helpdesk you do not want to replace', 'You already pay for an AI tool nobody uses properly', 'The AI needs to read your data and put results back in place', 'A person should still approve the result'] },
  { t: 'Build custom AI software', s: 'Tick three or more and a custom AI development project makes sense.',
    items: ['The job follows rules only your business knows', 'It needs data from three or more systems at once', 'Accuracy must be measured and proven, not assumed', 'Personal information must stay in Australia', 'You want to own the code and switch AI models later'],
    link: { href: '/au/ai-consulting', label: 'Not sure? Start with AI consulting' } },
];

/* How-to-choose checklist, rendered as <details>. */
const CHOOSE: { t: string; d: string }[] = [
  { t: 'Show me something live', d: 'Ask for AI systems running in a real business today. Demos and proofs of concept are easy. Systems that survived a year of real use are not.' },
  { t: 'Who exactly will build it?', d: 'Get names. Ask whether the people on the sales call are the people who write the code, and whether that team supports it after launch.' },
  { t: 'When would you tell us to buy instead?', d: 'An honest custom AI development company has a clear answer. If every problem needs a custom build, the advice is a sales process.' },
  { t: 'How will you measure accuracy?', d: 'You want a test set of real cases with known answers, a score before launch, and the same score tracked every month after.' },
  { t: 'Have you integrated with our systems?', d: 'Name your stack: Xero or MYOB, your CRM, your ERP, your shop and helpdesk. Ask how they would connect and what happens when one of them updates.' },
  { t: 'Where will our data be stored and processed?', d: 'Which AI providers see it, on what terms, in which country, and does anyone train on it? Ask for this in writing. If it must stay in Australia, ask how.' },
  { t: 'How do you handle the Privacy Act?', d: 'They are not your lawyers, but they should map personal information, limit it, keep it secure and give your privacy lead what a Privacy Impact Assessment needs.' },
  { t: 'What do we own at the end?', d: 'Code, prompts, integrations, test sets and documentation should all be yours, with no ongoing licence needed to keep using them.' },
  { t: 'Can we switch AI models later?', d: 'A well-built system can change model without a rewrite. Being tied to one model means being tied to one price list.' },
  { t: 'What does support look like after launch?', d: 'Ask who watches it, how fast they respond, and how they handle model updates. Most AI failures happen after the launch party, not before it.' },
];

export default function AiDevelopmentAUPage() {
  return (
    <>
      <script id="ld-au-ai-development" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <SiteHeader locale="au" logoHref="/au" />

      <div className="au-svc">
      <main>

        <Breadcrumbs items={crumbs} />

        {/* ═══ 1. HERO ═══ */}
        <section className="sec-lg dot-grid" style={{ position: 'relative' }}>
          <div className="wrap">
            <div className="col-6040">
              <div>
                <div className="flex-wrap mb-6">
                  <span className="chip"><span className="dot dot-orange" />AI Development Company Australia</span>
                  <span className="chip">AI Integration</span>
                  <span className="chip">You Own the Code</span>
                </div>
                <h1>{H1}</h1>
                <p className="lead mt-6" style={{ maxWidth: 560 }}>
                  FactoryJet is an AI development company for Australian SMEs and mid-market firms. We design, build
                  and support custom AI software, connect it to the CRM, ERP, Xero or MYOB, shop, helpdesk and
                  Microsoft 365 tools your team already uses, and take it from a promising idea to something people
                  rely on every day. You own the code and the data. The same senior team stays on after launch.
                </p>

                <div className="byline mt-6" style={{ maxWidth: 560 }}>
                  <div className="av">BB</div>
                  <div className="who"><b>Bhavesh Barot</b>, Founder<br /><span>500+ businesses served since 2014</span></div>
                  <div className="upd">Last updated<br />25 September 2026</div>
                </div>

                <div className="mt-6" style={{ maxWidth: 560 }}>
                  <HeroInlineForm region="au" source="au_ai_development_hero" submitLabel="Talk to the Founder" />
                </div>
              </div>

              <div className="card" style={{ padding: 8 }}>
                <img src="/images/au/ai-development/ai-development-hero.webp" width={1400} height={933} fetchPriority="high" decoding="async" alt="A FactoryJet developer and a Sydney business owner reviewing a custom internal AI tool on a monitor, with the harbour through the window" style={{ width: '100%', height: 'auto', borderRadius: 12, display: 'block' }} />
                <div style={{ padding: '14px 12px 8px' }}>
                  <span className="eyebrow">What you get</span>
                  <div className="scorecard-row">
                    <div><div className="scorecard-metric">AI built into your systems</div><div className="scorecard-note">CRM, ERP, Xero, MYOB, shop, helpdesk, M365</div></div>
                    <div className="scorecard-val" style={{ fontSize: 15 }}>Integrated</div>
                  </div>
                  <div className="scorecard-row">
                    <div><div className="scorecard-metric">Code, prompts and data</div><div className="scorecard-note">no platform lock-in, no licence</div></div>
                    <div className="scorecard-val" style={{ fontSize: 15 }}>Yours</div>
                  </div>
                  <div className="scorecard-row">
                    <div><div className="scorecard-metric">Australian hosting</div><div className="scorecard-note">AWS Sydney or Melbourne, Azure Australia East</div></div>
                    <div className="scorecard-val" style={{ color: T.green, fontSize: 15 }}>Available</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ═══ 2. ANSWER-FIRST DEFINITION (GEO) ═══ */}
        <section className="sec">
          <div className="wrap">
            <div className="def" style={{ maxWidth: 940 }} data-speakable="true">
              <span className="lab">What does an AI development company do?</span>
              <p>
                An AI development company builds software that uses AI to do a real job in your business, then keeps
                it working. It picks the task, prepares your data, chooses a model, connects it to systems like Xero
                or your CRM, tests accuracy, meets Privacy Act duties and puts it live. A good one tells you when a
                ready-made tool is enough.
              </p>
            </div>
            <div className="def mt-6" style={{ maxWidth: 940 }}>
              <span className="lab">Three terms, in plain English</span>
              <p>
                <b>AI development</b> is building the software. <b>AI integration</b> is connecting AI to the tools you
                already use, so it reads the right information and writes results back in the right place. <b>AI
                implementation</b> is everything that turns a demo into daily use: real data, permissions, testing,
                training, monitoring and support.
              </p>
            </div>
            <p className="lead mt-8" style={{ maxWidth: 920 }}>
              Why this matters for an Australian business: your staff are probably already using AI, often through
              personal accounts. The Office of the Australian Information Commissioner (OAIC) says privacy obligations
              apply to any personal information put into an AI system, and it recommends businesses do not enter
              personal information, especially sensitive information, into publicly available generative AI tools.
              Proper AI development gives your team the same help inside systems you control.
            </p>
            <p style={srcNote}>
              Source: <a href={SRC_OAIC_PRODUCTS} target="_blank" rel="noopener noreferrer nofollow" style={srcLink}>OAIC, guidance on privacy and the use of commercially available AI products</a>.
            </p>
          </div>
        </section>

        {/* ═══ 3. FACTS BAND (verified only) ═══ */}
        <section className="stats-band">
          <div className="wrap">
            <ul className="col-4" style={{ gap: 20 }}>
              {[
                { v: '13', t: 'Australian Privacy Principles apply to AI that handles personal information, including overseas disclosure (APP 8) and security (APP 11)', s: 'OAIC', u: SRC_OAIC_APPS },
                { v: 'In + out', t: 'privacy obligations cover both what goes into an AI system and AI output that contains personal information', s: 'OAIC guidance', u: SRC_OAIC_PRODUCTS },
                { v: '2', t: 'AWS regions in Australia (Sydney and Melbourne) where an AI system and its data can be hosted', s: 'AWS', u: SRC_AWS_REGIONS },
                { v: 'NSW', t: 'is where Microsoft’s Azure Australia East region sits, another onshore hosting option', s: 'Microsoft Learn', u: SRC_AZURE_REGIONS },
              ].map((r) => (
                <li key={r.t}>
                  <div style={{ fontFamily: T.fd, fontWeight: 800, fontSize: 26, color: T.orange }}>{r.v}</div>
                  <p style={{ fontSize: 13.5, color: T.ink, marginTop: 4 }}>{r.t}</p>
                  <a href={r.u} target="_blank" rel="noopener noreferrer nofollow" style={{ fontFamily: T.fm, fontSize: 10, color: T.n400, textDecoration: 'underline' }}>{r.s}</a>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* ═══ 4. LISTICLE: WHAT WE BUILD ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <div style={{ maxWidth: 760 }}>
              <span className="eyebrow">Our AI development services</span>
              <h2>Nine kinds of custom AI development we do for Australian businesses</h2>
              <p className="lead mt-4">
                Each one is a real job with a plain example. Most projects start with one and add the next once the
                first is working. None of them asks you to replace the software you run today.
              </p>
            </div>
            <ol className="stack mt-10" style={{ maxWidth: 920 }}>
              {[
                { n: '01', t: 'Answers from your own documents', d: 'A private search box that answers staff or customer questions from your policies, manuals, contracts and price lists, and shows which page each answer came from. Example: a Brisbane wholesaler’s sales team asks about trade terms for a new customer and gets the exact clause, not a guess.' },
                { n: '02', t: 'AI with Xero and MYOB', d: 'AI that reads supplier bills and receipts from an inbox, suggests the account code and GST treatment based on how you have coded similar bills before, and leaves a draft for your bookkeeper to approve. Nothing posts without a person.' },
                { n: '03', t: 'Document and email processing', d: 'AI that reads purchase orders, delivery dockets, application forms or claims and pulls the key details into your systems. Example: emailed purchase orders from trade buyers become draft sales orders in your ERP, ready for a person to check.' },
                { n: '04', t: 'AI inside your CRM', d: 'Call and email summaries on the customer record, suggested next steps, and first-draft quotes and follow-ups written in your tone. Example: after a sales call, the notes, actions and a draft reply are waiting in HubSpot or Salesforce before the rep has put the phone down.' },
                { n: '05', t: 'AI for ecommerce operations', d: 'Product descriptions drafted from supplier data, cleaner attributes and categories, better on-site search, and returns reasons sorted into themes. This is our home ground; see our Australian ecommerce development and Shopify development work.' },
                { n: '06', t: 'Helpdesk and inbox triage', d: 'Incoming tickets and emails sorted, tagged, prioritised and given a suggested reply, with anything sensitive routed straight to a person. Example: “where is my order” questions get a drafted answer with tracking pulled in; complaints go to a manager.' },
                { n: '07', t: 'AI in Microsoft 365', d: 'Connections between AI and SharePoint, Outlook, Teams and Excel, so answers and actions happen where your team already works. Example: a Teams assistant that finds the latest signed version of a supplier agreement in SharePoint.' },
                { n: '08', t: 'Internal AI tools and apps', d: 'Small, focused applications for one team: a quote builder, a compliance checker, a report writer that pulls numbers from three systems. Example: a weekly trading summary drafted from your shop, ERP and ad accounts, checked by a person, sent on Monday.' },
                { n: '09', t: 'AI agents that take actions', d: 'AI that carries out multi-step tasks across your systems within rules you set, such as chasing an overdue invoice or rebooking a delivery. Agents need extra design care, so they have their own page: AI agents for Australian businesses.' },
              ].map((s) => (
                <li key={s.n} className="card" style={{ display: 'flex', gap: 18, alignItems: 'flex-start' }}>
                  <span style={{ fontFamily: T.fm, fontWeight: 700, fontSize: 15, color: T.orange, minWidth: 34 }}>{s.n}</span>
                  <div>
                    <h3 style={{ fontSize: 18 }}>{s.t}</h3>
                    <p className="mt-2" style={{ marginTop: 6 }}>{s.d}</p>
                  </div>
                </li>
              ))}
            </ol>
            <ul className="col-4 mt-10" style={{ gap: 16 }}>
              <li><a className="svc-card" href="/au/ai-agents" style={{ display: 'block', height: '100%' }}><span className="eyebrow">Sibling service</span><h3 style={{ fontSize: 17 }}>AI agents for Australian businesses</h3><p className="mt-2">When the AI should act on its own across your systems.</p></a></li>
              <li><a className="svc-card" href="/au/ai-consulting" style={{ display: 'block', height: '100%' }}><span className="eyebrow">Sibling service</span><h3 style={{ fontSize: 17 }}>AI consulting in Australia</h3><p className="mt-2">When you are still deciding what AI should do first.</p></a></li>
              <li><a className="svc-card" href="/au/ai-receptionist" style={{ display: 'block', height: '100%' }}><span className="eyebrow">Sibling service</span><h3 style={{ fontSize: 17 }}>AI receptionist</h3><p className="mt-2">When the job is answering the phone, not software.</p></a></li>
              <li><a className="svc-card" href="/au/ecommerce-development" style={{ display: 'block', height: '100%' }}><span className="eyebrow">Sibling service</span><h3 style={{ fontSize: 17 }}>Ecommerce development</h3><p className="mt-2">When AI needs to live inside your online store.</p></a></li>
            </ul>
          </div>
        </section>

        {/* ═══ 5. INTEGRATION + RAG, ENGINEER IMAGE ═══ */}
        <section className="sec-lg">
          <div className="wrap">
            <div className="col-6040">
              <div>
                <span className="eyebrow">How custom AI knows your business</span>
                <h2>AI integration that answers from your data, not from the internet</h2>
                <div className="stack mt-6">
                  <p>
                    A general AI model knows a lot about the world and nothing about your business. It has never seen
                    your price list, your returns policy or last month’s supplier agreement. Ask it about them and it
                    will either say it does not know or, worse, make up something that sounds right.
                  </p>
                  <p>
                    The fix most custom AI development uses is called <b>RAG</b>, short for retrieval-augmented
                    generation. Think of it as an open-book exam. Before the AI answers, the system looks up the most
                    relevant pages from your own documents and records, hands them to the AI, and tells it to answer
                    using only those pages. The answer can then show exactly where it came from.
                  </p>
                  <p>
                    Getting that right is most of the engineering. Documents have to be split sensibly, kept up to date
                    when files change, and filtered by permissions so the payroll folder never shows up in a warehouse
                    answer. We build that plumbing, test it against real questions, and keep it current after launch.
                    It is also where Australian hosting matters: the search index holds copies of your documents, so
                    it lives in the same Australian region as the rest of your data when that is a requirement.
                  </p>
                </div>
              </div>
              <div className="card" style={{ padding: 8 }}>
                <img src="/images/au/ai-development/ai-development-engineer.webp" width={1200} height={800} loading="lazy" decoding="async" alt="A FactoryJet AI engineer in a Melbourne office working on two monitors showing a diagram of connected system blocks" style={{ width: '100%', height: 'auto', borderRadius: 12, display: 'block' }} />
                <div style={{ padding: '14px 12px 8px' }}>
                  <span className="eyebrow">Inside a typical build</span>
                  <div className="scorecard-row"><div><div className="scorecard-metric">Your documents and records</div><div className="scorecard-note">drives, CRM, ERP, Xero or MYOB, shop, helpdesk</div></div><div className="scorecard-val" style={{ fontSize: 14 }}>Source</div></div>
                  <div className="scorecard-row"><div><div className="scorecard-metric">Search and permissions layer</div><div className="scorecard-note">finds the right pages, hides the wrong ones</div></div><div className="scorecard-val" style={{ fontSize: 14 }}>Retrieve</div></div>
                  <div className="scorecard-row"><div><div className="scorecard-metric">AI model</div><div className="scorecard-note">chosen on your test cases, swappable</div></div><div className="scorecard-val" style={{ fontSize: 14 }}>Answer</div></div>
                  <div className="scorecard-row"><div><div className="scorecard-metric">A person, where it matters</div><div className="scorecard-note">approves anything customer-facing</div></div><div className="scorecard-val" style={{ color: T.green, fontSize: 14 }}>Check</div></div>
                </div>
              </div>
            </div>

            <div className="card mt-10" style={{ padding: 0, overflowX: 'auto' }}>
              <table className="cmp-table">
                <thead>
                  <tr><th>System you run</th><th>What AI integration usually does there</th><th>Who approves</th></tr>
                </thead>
                <tbody>
                  <tr><td className="feat">Xero or MYOB</td><td>Reads bills and receipts, suggests account codes and GST treatment, drafts the entry</td><td>Your bookkeeper</td></tr>
                  <tr><td className="feat">CRM (HubSpot, Salesforce, Zoho)</td><td>Summarises calls and emails, drafts follow-ups and quotes, flags stalled deals</td><td>The account owner</td></tr>
                  <tr><td className="feat">ERP (NetSuite, Dynamics, Odoo)</td><td>Turns emailed purchase orders into draft sales orders, answers stock questions</td><td>Sales or ops staff</td></tr>
                  <tr><td className="feat">Ecommerce (Shopify, BigCommerce, Magento)</td><td>Drafts product copy, cleans attributes, sorts returns reasons, improves on-site search</td><td>Merchandiser</td></tr>
                  <tr><td className="feat">Helpdesk (Zendesk, Freshdesk, Gorgias)</td><td>Tags and prioritises tickets, drafts replies with order data pulled in</td><td>Support agent</td></tr>
                  <tr><td className="feat">Microsoft 365</td><td>Answers from SharePoint, drafts in Outlook, assists inside Teams</td><td>The person asking</td></tr>
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* ═══ 6. PHASED DELIVERY (details expanders) ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <div style={{ maxWidth: 780 }}>
              <span className="eyebrow">The AI development life cycle</span>
              <h2>AI implementation, step by step: six phases and how long each takes</h2>
              <p className="lead mt-4">
                Most AI development companies show a process diagram with no timings. Here are ours, with honest
                ranges. A first project usually runs 6 to 14 weeks from kick-off to live use. Phases overlap, so the
                total is shorter than the sum. Open each phase to see what happens and what you get at the end.
              </p>
            </div>
            <ul className="faq-list mt-10" style={{ maxWidth: 920 }}>
              {PHASES.map((p) => (
                <li key={p.n}>
                  <details className="faq-item">
                    <summary>
                      <span className="q-text"><span style={{ fontFamily: T.fm, color: T.small, marginRight: 12 }}>{p.n}</span>{p.t} <span style={{ fontFamily: T.fm, fontSize: 12, color: T.n400, marginLeft: 8 }}>{p.w}</span></span>
                      <span className="chevron">
                        <svg viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="M3 5L7 9L11 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" /></svg>
                      </span>
                    </summary>
                    <div style={detailBody}>
                      <p>{p.d}</p>
                      <p className="mt-2" style={{ marginTop: 8 }}><b style={{ color: T.ink }}>You get:</b> {p.out}</p>
                    </div>
                  </details>
                </li>
              ))}
            </ul>
            <p style={srcNote}>
              Ranges are typical for one focused use case at an Australian SME or mid-market firm. Several
              integrations, older on-premise systems or sensitive health and financial data push toward the top of
              each range.
            </p>
          </div>
        </section>

        {/* ═══ 7. GOOD FIRST PROJECT, WAREHOUSE IMAGE ═══ */}
        <section className="sec-lg">
          <div className="wrap">
            <div className="col-6040">
              <div>
                <span className="eyebrow">What a first project looks like</span>
                <h2>What makes a good first AI development project</h2>
                <div className="stack mt-6">
                  <p>
                    The best first project is small, repeated every day and easy to measure. Think of work where
                    people read something messy (an emailed order, a PDF invoice, a support request), type it into
                    another system, and fix the mistakes later. That kind of job has past examples you can test
                    against, so you know how accurate the system is before anyone relies on it.
                  </p>
                  <p>
                    We start in <b>discovery</b> by agreeing one goal you can measure. In <b>data preparation</b> we
                    collect past cases with the correct answers, which become the test set. The <b>prototype</b> shows
                    the idea working on your data, the <b>build</b> connects it to your systems with drafts rather than
                    final actions, and the <b>pilot</b> runs alongside your team while we measure accuracy on every
                    case.
                  </p>
                  <p>
                    Your people stay in charge. They check and approve instead of re-typing, and anything unusual goes
                    to them first.
                  </p>
                </div>
              </div>
              <div className="card" style={{ padding: 8 }}>
                <img src="/images/au/ai-development/ai-development-warehouse.webp" width={1200} height={800} loading="lazy" decoding="async" alt="A warehouse manager in a Brisbane distribution centre checking orders on a tablet in an aisle of stacked cartons" style={{ width: '100%', height: 'auto', borderRadius: 12, display: 'block' }} />
                <div style={{ padding: '14px 12px 8px' }}>
                  <span className="eyebrow">Why this is a good first project</span>
                  <div className="scorecard-row"><div className="scorecard-metric">Repeated every day</div><div className="scorecard-val" style={{ fontSize: 14 }}>Yes</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">Easy to measure</div><div className="scorecard-val" style={{ fontSize: 14 }}>Yes</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">Past data to test against</div><div className="scorecard-val" style={{ fontSize: 14 }}>Yes</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">A person approves each result</div><div className="scorecard-val" style={{ color: T.green, fontSize: 14 }}>Always</div></div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ═══ 8. COMPARISON TABLE ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <span className="eyebrow">Side by side</span>
            <h2 style={{ maxWidth: 800 }}>Off-the-shelf AI tool vs freelancer vs offshore dev shop vs an AI development company</h2>
            <p className="lead mt-4" style={{ maxWidth: 760 }}>
              Each option is right for someone. This is how they compare on the things that decide whether AI keeps
              working after month three.
            </p>
            <div className="card mt-8" style={{ padding: 0, overflowX: 'auto' }}>
              <table className="cmp-table">
                <thead>
                  <tr>
                    <th>What matters</th>
                    <th>Off-the-shelf AI tool</th>
                    <th>Freelancer</th>
                    <th>Offshore dev shop</th>
                    <th className="fj">FactoryJet</th>
                  </tr>
                </thead>
                <tbody>
                  <tr><td className="feat">Best fit</td><td><span className="partial">General writing and search</span></td><td><span className="partial">Small prototypes</span></td><td><span className="partial">Well-specified builds</span></td><td className="fj"><span className="yes">Australian SMEs and mid-market</span></td></tr>
                  <tr><td className="feat">Control over how it works</td><td><span className="partial">Settings the vendor allows</span></td><td><span className="yes">Full</span></td><td><span className="partial">Full, via change requests</span></td><td className="fj"><span className="yes">Full: your rules, your data</span></td></tr>
                  <tr><td className="feat">Integration depth</td><td><span className="partial">Built-in connectors only</span></td><td><span className="partial">One or two systems</span></td><td><span className="yes">Deep, if specified</span></td><td className="fj"><span className="yes">Deep: Xero, MYOB, CRM, ERP, shop, M365</span></td></tr>
                  <tr><td className="feat">Speed to first result</td><td><span className="yes">Days</span></td><td><span className="yes">Weeks</span></td><td><span className="partial">Weeks to months</span></td><td className="fj"><span className="yes">Prototype in weeks</span></td></tr>
                  <tr><td className="feat">Accuracy testing</td><td><span className="no">Not on your cases</span></td><td><span className="partial">Varies</span></td><td><span className="partial">Often functional tests only</span></td><td className="fj"><span className="yes">Test set before launch, monthly after</span></td></tr>
                  <tr><td className="feat">Privacy Act and Australian hosting</td><td><span className="partial">Vendor terms decide</span></td><td><span className="partial">Varies</span></td><td><span className="partial">Ask; often not the default</span></td><td className="fj"><span className="yes">Designed in, AU regions available</span></td></tr>
                  <tr><td className="feat">Who owns it</td><td><span className="no">The vendor; you rent it</span></td><td><span className="partial">Depends on the contract</span></td><td><span className="partial">Often yours, check licences</span></td><td className="fj"><span className="yes">You: code, prompts, data</span></td></tr>
                  <tr><td className="feat">Support after launch</td><td><span className="partial">Vendor help desk</span></td><td><span className="no">If they are available</span></td><td><span className="partial">Separate contract, new team</span></td><td className="fj"><span className="yes">Same team, monthly</span></td></tr>
                  <tr><td className="feat">Who does the work</td><td>You and your team</td><td>One person</td><td><span className="partial">Mixed seniority, rotating staff</span></td><td className="fj"><span className="yes">Senior engineers + founder</span></td></tr>
                </tbody>
              </table>
            </div>
            <p className="mt-6" style={{ maxWidth: 800 }}>
              The real difference in this table is who owns the outcome. A typical offshore dev shop builds to a specification and
              moves the team on. We scope the job with you, measure accuracy against your own cases, host where your
              data needs to live, and the same senior people support it for as long as you want them to.
            </p>
            <p className="mt-4" style={{ maxWidth: 800 }}>
              Our honest advice: try an off-the-shelf tool first for general jobs. Bring in an AI development company
              when the job needs your own systems, your own rules, or data you cannot paste into a public tool.
            </p>
          </div>
        </section>

        <MidPageCTA
          headline={'Have an AI idea that needs to connect to your real systems?'}
          sub={'Tell us the job and the tools involved. On a short call with the founder, we will tell you whether a ready-made tool will do, what a custom build would involve, and roughly how many weeks each phase would take.'}
          label={'Talk to the Founder'}
        />

        {/* ═══ 9. WHAT CAN GO WRONG ═══ */}
        <section className="sec-lg">
          <div className="wrap">
            <div style={{ maxWidth: 780 }}>
              <span className="eyebrow">The part most pages leave out</span>
              <h2>What can go wrong with AI implementation, and how we prevent it</h2>
              <p className="lead mt-4">
                Most AI development company pages in Australian search results skip this part. These are the problems that make business owners nervous, and every one of them is avoidable.
              </p>
            </div>
            <ul className="col-3 mt-12">
              <li className="svc-card"><h3>No clear job for it</h3><p className="mt-4">AI bought because it is new ends up unused. We start from one measurable task and a number you already track, and we say no to projects that do not have one.</p></li>
              <li className="svc-card"><h3>It makes things up</h3><p className="mt-4">AI can state wrong answers confidently. We ground answers in your documents, show sources, make it say &ldquo;I don’t know&rdquo;, and keep a person approving anything customer-facing.</p></li>
              <li className="svc-card"><h3>The demo never meets real data</h3><p className="mt-4">A prototype on ten tidy examples says little about ten thousand messy ones. We test on your real cases from the prototype phase and share accuracy before launch.</p></li>
              <li className="svc-card"><h3>Personal information ends up offshore by accident</h3><p className="mt-4">APP 8 sets rules for sending personal information overseas. We map where every piece of data goes, use business terms that do not train on your inputs, and host in Australia where needed.</p></li>
              <li className="svc-card"><h3>It quietly gets worse</h3><p className="mt-4">Models are updated, your data changes, and accuracy drifts. Monthly scoring against a fixed test set catches that before your customers do.</p></li>
              <li className="svc-card"><h3>Staff do not trust it</h3><p className="mt-4">If the people doing the job were never asked, they route around the system. We involve them from discovery, run the pilot with them, and keep a person in control of decisions.</p></li>
              <li className="svc-card"><h3>Running costs surprise you</h3><p className="mt-4">Model usage is billed per use. We estimate running costs at the prototype stage, choose the smallest model that meets the accuracy bar, and show usage in the monthly report.</p></li>
              <li className="svc-card"><h3>A connected system changes</h3><p className="mt-4">Xero, your CRM or your shop platform releases an update and a connection breaks. Monitoring alerts us, and fixing it is part of monthly support.</p></li>
              <li className="svc-card"><h3>The builder disappears</h3><p className="mt-4">The classic agency failure: launch, invoice, gone. You own everything we build, it is documented, and the team that built it stays on to support it.</p></li>
            </ul>
          </div>
        </section>

        {/* ═══ 10. PRIVACY ACT + AUSTRALIAN HOSTING ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <div style={{ maxWidth: 780 }}>
              <span className="eyebrow">Privacy Act and APPs, in plain English</span>
              <h2>AI development services with Australian privacy designed in, not bolted on</h2>
              <div className="stack mt-6">
                <p>
                  If your AI touches personal information, meaning anything about a customer, patient, tenant or staff
                  member, the Privacy Act 1988 and its 13 Australian Privacy Principles (APPs) apply to most
                  businesses. The OAIC is clear that privacy obligations cover both the personal information put into
                  an AI system and any AI output that contains personal information.
                </p>
                <p>
                  Three APPs shape most of our design decisions. <b>APP 8</b> covers sending personal information
                  overseas, which matters because many AI models run outside Australia by default. <b>APP 10</b> asks
                  you to take reasonable steps to keep personal information accurate, which is one reason we test AI
                  output before it lands in a customer record. <b>APP 11</b> asks you to protect personal information
                  from misuse and unauthorised access, which is why access is limited by role and every AI action is
                  logged.
                </p>
                <p>
                  The OAIC also recommends a privacy by design approach for AI, including a Privacy Impact Assessment
                  (a written check of how a project affects people’s personal information and how you reduce the
                  risks), and its guidance for AI developers says the planning stage is where that work belongs. The
                  Australian Government’s voluntary Guidance for AI Adoption points the same way: test and monitor AI
                  systems, and keep human control.
                </p>
                <p>
                  Where your data needs to stay onshore, we build in Australian cloud regions: AWS has regions in
                  Sydney and Melbourne, and Microsoft Azure’s Australia East region is in New South Wales. We then
                  choose AI model options and settings to match, and write down exactly what goes where.
                </p>
              </div>
              <p style={srcNote}>
                Sources: <a href={SRC_OAIC_PRODUCTS} target="_blank" rel="noopener noreferrer nofollow" style={srcLink}>OAIC, privacy and commercially available AI products</a>;{' '}
                <a href={SRC_OAIC_DEV} target="_blank" rel="noopener noreferrer nofollow" style={srcLink}>OAIC, privacy and developing generative AI models</a>;{' '}
                <a href={SRC_OAIC_APPS} target="_blank" rel="noopener noreferrer nofollow" style={srcLink}>OAIC, APP quick reference</a>;{' '}
                <a href={SRC_AWS_REGIONS} target="_blank" rel="noopener noreferrer nofollow" style={srcLink}>AWS Regions</a>;{' '}
                <a href={SRC_AZURE_REGIONS} target="_blank" rel="noopener noreferrer nofollow" style={srcLink}>Microsoft Learn, Azure regions</a>.
              </p>
            </div>
            <ul className="col-3 mt-10">
              <li className="card"><h3>What we do</h3><p className="mt-4">Map the personal information each feature uses, remove what it does not need, choose providers with business terms that do not train on your inputs, and prepare the inputs for your Privacy Impact Assessment.</p></li>
              <li className="card"><h3>How we secure it</h3><p className="mt-4">Role-based access, secrets kept out of code, Australian hosting where you need it, logs of every AI action, and a person approving anything with real consequences.</p></li>
              <li className="card"><h3>What we do not do</h3><p className="mt-4">We are not lawyers and do not give legal sign-off. Your business stays responsible for its privacy duties. We build to your requirements and document what your adviser needs.</p></li>
            </ul>
          </div>
        </section>

        {/* ═══ 11. WHICH FITS YOU (details checklist) ═══ */}
        <section className="sec-lg">
          <div className="wrap">
            <div style={{ maxWidth: 760 }}>
              <span className="eyebrow">Build, buy or integrate?</span>
              <h2>Which kind of AI project fits your business?</h2>
              <p className="lead mt-4">
                Open each option and count how many lines sound like you. It is a quick way to know which conversation
                to have before you talk to any AI development company.
              </p>
            </div>
            <ul className="faq-list mt-8" style={{ maxWidth: 920 }}>
              {FIT.map((f) => (
                <li key={f.t}>
                  <details className="faq-item">
                    <summary>
                      <span className="q-text">{f.t}</span>
                      <span className="chevron">
                        <svg viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="M3 5L7 9L11 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" /></svg>
                      </span>
                    </summary>
                    <div style={detailBody}>
                      <p style={{ marginBottom: 10 }}>{f.s}</p>
                      <ul className="scope-list">
                        {f.items.map((it) => <li key={it}>{it}</li>)}
                      </ul>
                      {f.link && <p className="mt-4"><a href={f.link.href} style={{ color: T.small, textDecoration: 'underline' }}>{f.link.label}</a></p>}
                    </div>
                  </details>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* ═══ 12. HOW TO CHOOSE CHECKLIST (details) ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <div style={{ maxWidth: 760 }}>
              <span className="eyebrow">Before you sign anything</span>
              <h2>How to choose an AI development company in Australia: a ten-point checklist</h2>
              <p className="lead mt-4">
                Use this with any AI software development company, including us. A good one will enjoy the questions.
                A weak one will steer you back to the demo.
              </p>
            </div>
            <ol className="faq-list mt-8" style={{ maxWidth: 920, listStyle: 'none' }}>
              {CHOOSE.map((c, i) => (
                <li key={c.t}>
                  <details className="faq-item">
                    <summary>
                      <span className="q-text"><span style={{ fontFamily: T.fm, color: T.small, marginRight: 12 }}>{String(i + 1).padStart(2, '0')}</span>{c.t}</span>
                      <span className="chevron">
                        <svg viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="M3 5L7 9L11 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" /></svg>
                      </span>
                    </summary>
                    <div style={detailBody}><p>{c.d}</p></div>
                  </details>
                </li>
              ))}
            </ol>
          </div>
        </section>

        {/* ═══ 13. WHY FACTORYJET (E-E-A-T) + PILOT IMAGE ═══ */}
        <section className="sec-lg">
          <div className="wrap">
            <div className="col-6040">
              <div>
                <span className="eyebrow">Why FactoryJet</span>
                <h2>An AI software development company that grew up inside commerce systems</h2>
                <div className="stack mt-6">
                  <p>
                    FactoryJet was founded in 2014 by Bhavesh Barot and has served 500+ businesses since, most of them
                    in commerce: B2B wholesalers such as Bombay Petals, direct-to-consumer brands such as Belle Maison,
                    and the ERPs, CRMs, accounting tools and ecommerce platforms that sit behind them. That decade of
                    integration work is why our AI development starts from your systems, not from a model.
                  </p>
                  <p>
                    We are a services company. We design, build, implement and support AI, and you own what we build.
                    We do not sell a platform, take a cut of your model costs, or hand you to a junior team after the
                    contract is signed. The founder is involved in every engagement.
                  </p>
                  <p>
                    Not sure what to build yet? Start with <a href="/au/ai-consulting" style={{ textDecoration: 'underline' }}>AI consulting for Australian businesses</a>,
                    which hands its plan straight to the same engineers. For more on how we think about builds, read{' '}
                    <a href="/blog/ai-agent-build-vs-buy-2026" style={{ textDecoration: 'underline' }}>our build vs buy guide for AI agents</a> or{' '}
                    <a href="/blog/what-is-an-ai-agent-cost-2026" style={{ textDecoration: 'underline' }}>what drives the cost of an AI agent</a>, and see
                    our wider <a href="/services/ai-integration-services" style={{ textDecoration: 'underline' }}>AI integration services</a> page.
                  </p>
                </div>
              </div>
              <div className="card" style={{ padding: 8 }}>
                <img src="/images/au/ai-development/ai-development-pilot.webp" width={1200} height={800} loading="lazy" decoding="async" alt="Three colleagues in a bright Perth office reviewing pilot results for a new AI tool on printed charts around a white table" style={{ width: '100%', height: 'auto', borderRadius: 12, display: 'block' }} />
                <div style={{ padding: '14px 12px 8px' }}>
                  <span className="eyebrow">What sets the scope</span>
                  <div className="scorecard-row"><div className="scorecard-metric">Number of systems to connect</div><div className="scorecard-val" style={{ fontSize: 14 }}>Reach</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">State of your data</div><div className="scorecard-val" style={{ fontSize: 14 }}>Prep</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">Accuracy the job needs</div><div className="scorecard-val" style={{ fontSize: 14 }}>Testing</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">Personal information and hosting</div><div className="scorecard-val" style={{ fontSize: 14 }}>Privacy</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">Support after launch</div><div className="scorecard-val" style={{ fontSize: 14 }}>Monthly</div></div>
                  <div className="scorecard-row"><div className="scorecard-metric">First call with the founder</div><div className="scorecard-val" style={{ color: T.green, fontSize: 14 }}>Free</div></div>
                  <div className="mt-6">
                    <ModalCTAButton label="Talk to the Founder" region="au" modalVariant="default" btnVariant="primary-light" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ═══ 14. ENGAGEMENT SHAPES (no pricing) ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <div style={{ maxWidth: 760 }}>
              <span className="eyebrow">Scope, not packages</span>
              <h2>Four ways to work with our AI development team</h2>
              <p className="lead mt-4">
                Every engagement is quoted for your scope, with a fixed price per phase. These are the shapes it
                usually takes, from smallest to largest.
              </p>
            </div>
            <ul className="col-4 mt-10" style={{ gap: 20 }}>
              <li className="svc-card"><h3>Prototype sprint</h3><p className="mt-4">One job, your real data, a working prototype and an accuracy score in a few weeks. You decide whether to go further with evidence, not a pitch.</p></li>
              <li className="svc-card"><h3>Fixed-scope build</h3><p className="mt-4">From discovery to live use for one use case, including integrations, testing, training and launch. The most common starting point.</p></li>
              <li className="svc-card"><h3>AI integration project</h3><p className="mt-4">You already have an AI tool. We connect it properly to Xero, MYOB, your CRM, ERP, shop, helpdesk or Microsoft 365 so it can actually do the job.</p></li>
              <li className="svc-card"><h3>Monthly support</h3><p className="mt-4">Monitoring, fixes, model updates and small improvements for systems we built, or for AI someone else built and then left behind.</p></li>
            </ul>
          </div>
        </section>

        {/* ═══ 15. AUSTRALIA-WIDE + DEMAND CARD ═══ */}
        <section className="sec-lg">
          <div className="wrap">
            <div className="col-6040">
              <div>
                <span className="eyebrow">Sydney, Melbourne, Brisbane and beyond</span>
                <h2>AI developers for Australian businesses, wherever you are</h2>
                <div className="stack mt-6">
                  <p>
                    People often search for an AI development company in Sydney or Melbourne expecting to need a team
                    down the road. For this work you do not. We run discovery workshops over video, share a test
                    environment from the early weeks, and demo working software at regular milestones, for businesses in
                    Sydney, Melbourne, Brisbane, Perth, Adelaide, Canberra, Hobart and regional Australia.
                  </p>
                  <p>
                    What matters more than a postcode is who answers when something breaks. At FactoryJet that is the
                    same senior team that built your system, with the founder involved throughout.
                  </p>
                  <p>
                    If the job is a phone line rather than software, see our <a href="/au/ai-receptionist" style={{ textDecoration: 'underline' }}>AI
                    receptionist for Australian businesses</a>. If you want AI to act on its own across your systems,
                    see <a href="/au/ai-agents" style={{ textDecoration: 'underline' }}>AI agents in Australia</a>. For all our Australian services,
                    visit <a href="/au" style={{ textDecoration: 'underline' }}>FactoryJet Australia</a>.
                  </p>
                </div>
                <div className="flex-wrap mt-6">
                  <a className="city-pill" href="/au">FactoryJet Australia</a>
                  <a className="city-pill" href="/au/ai-agents">AI agents Australia</a>
                  <a className="city-pill" href="/au/ai-consulting">AI consulting Australia</a>
                  <a className="city-pill" href="/au/ai-seo">AI SEO Australia</a>
                  <a className="city-pill" href="/au/shopify-development">Shopify development Australia</a>
                  <a className="city-pill" href="/contact">Contact us</a>
                </div>
              </div>

              <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: `1px solid ${T.n200}`, padding: '14px 18px' }}>
                  <span style={{ fontFamily: T.fm, fontSize: 10, letterSpacing: '.13em', textTransform: 'uppercase', color: T.n400 }}>Australia · Monthly Search Demand</span>
                  <span style={{ background: T.small, color: '#fff', fontFamily: T.fm, fontSize: 10, borderRadius: 999, padding: '3px 9px' }}>DataForSEO</span>
                </div>
                <div style={{ padding: '4px 18px 14px' }}>
                  <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
                    {[
                      { kw: 'ai development', v: '260', w: '100%', kd: 'The head term' },
                      { kw: 'ai integration', v: '170', w: '65%', kd: 'Connect AI to your tools' },
                      { kw: 'ai development company', v: '140', w: '54%', kd: 'Buyer intent' },
                      { kw: 'ai development company in australia', v: '140', w: '54%', kd: 'Buyer intent, national' },
                      { kw: 'ai development services', v: '90', w: '35%', kd: 'Buyer intent' },
                      { kw: 'ai implementation', v: '90', w: '35%', kd: 'Idea to daily use' },
                      { kw: 'ai application development', v: '50', w: '19%', kd: 'Custom apps' },
                      { kw: 'ai integration services', v: '40', w: '15%', kd: 'Buyer intent' },
                    ].map((r) => (
                      <li key={r.kw} className="demand-row">
                        <div className="demand-top"><span className="demand-kw">{r.kw}</span><span className="demand-v">{r.v}<span style={{ fontSize: 9, color: T.n400 }}> searches</span></span></div>
                        <div className="demand-bar"><i style={{ width: r.w }} /></div>
                        <div className="demand-kd">{r.kd}</div>
                      </li>
                    ))}
                  </ul>
                  <p style={{ textAlign: 'center', fontFamily: T.fm, fontSize: 10, color: T.n400, marginTop: 10 }}>Source: DataForSEO, Australia, September 2026</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ═══ 16. COMPETITOR LIST (self-disclosure, ItemList) ═══ */}
        <section className="sec-lg dot-grid">
          <div className="wrap">
            <div style={{ maxWidth: 760 }}>
              <span className="eyebrow">The honest landscape</span>
              <h2>AI development companies in Australia worth knowing</h2>
              <p className="lead mt-4">
                We are one option, not the only one. These AI development companies show up when Australian buyers
                search for AI development services or ask AI assistants for a recommendation. Each note is based on
                what the company says on its own website. Talk to a few and pick the fit.
              </p>
            </div>
            <ul className="stack mt-10" style={{ maxWidth: 900 }}>
              {AI_DEV_COMPANIES.map((a, i) => (
                <li key={a.name} className="card" style={{ display: 'flex', gap: 18, alignItems: 'flex-start' }}>
                  <span style={{ fontFamily: T.fm, fontWeight: 700, fontSize: 15, color: T.orange, minWidth: 30 }}>{i + 1}</span>
                  <div>
                    <h3 style={{ fontSize: 18 }}>{a.name}{a.name === 'FactoryJet' && <span style={{ fontFamily: T.fm, fontSize: 10, background: T.small, color: '#fff', borderRadius: 999, padding: '2px 8px', marginLeft: 8, verticalAlign: 'middle' }}>That is us</span>}</h3>
                    <p className="mt-2" style={{ marginTop: 6 }}>{a.note}</p>
                  </div>
                </li>
              ))}
            </ul>
            <p style={srcNote}>
              Companies named from live Australian search results and AI assistant answers for AI development company queries, September 2026. Notes reflect each company’s own website on 25 September 2026. Listing is not endorsement.
            </p>
          </div>
        </section>

        {/* ═══ 17. FAQ (canonical Linear Minimal) ═══ */}
        <section className="sec-lg" id="faq">
          <div className="wrap">
            <div style={{ textAlign: 'center' }}>
              <span className="eyebrow">FAQ</span>
              <h2>AI development questions Australian business owners actually ask</h2>
            </div>
            <div className="faq-grid">
              <aside className="faq-sidebar">
                <span className="faq-sidebar-topics">Topics</span>
                <nav className="faq-sidebar-nav">
                  {FAQ_CATEGORIES.map((c) => (
                    <a key={c.key} href={`#faq-${c.key}`}>
                      {c.label}
                      <span className="faq-nav-count">{FAQ_ITEMS.filter((f) => f.category === c.key).length}</span>
                    </a>
                  ))}
                </nav>
                <div className="faq-sidebar-cta">
                  <ModalCTAButton label="Still have a question? Ask the founder →" region="au" modalVariant="default" btnVariant="secondary-light" />
                  <p>Replies within 24 hours.</p>
                </div>
              </aside>

              <div>
                {FAQ_CATEGORIES.map((c) => (
                  <div key={c.key} id={`faq-${c.key}`} style={{ marginBottom: 40 }}>
                    <div className="faq-cat-header">
                      <span className="faq-cat-bar" />
                      <p className="faq-cat-label">{c.label}</p>
                    </div>
                    <ul className="faq-list">{FAQ_ITEMS.filter((f) => f.category === c.key).map((f) => (
                      <li key={f.question}><details className="faq-item">
                        <summary>
                          <span className="q-text">{f.question}</span>
                          <span className="chevron">
                            <svg viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="M3 5L7 9L11 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" /></svg>
                          </span>
                        </summary>
                        <div className="faq-ans"><p>{f.answer}</p></div>
                      </details></li>
                    ))}</ul>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* ═══ 18. FINAL CTA (the only dark section) ═══ */}
        <section className="dark-sec">
          <div className="wrap" style={{ textAlign: 'center', maxWidth: 640 }}>
            <span className="eyebrow">Ready when you are</span>
            <h2>Turn your AI idea into software your team uses every day</h2>
            <p className="mt-4">
              Send your name and work email. The founder replies within 24 hours to book a short call about the job,
              the systems involved, and whether a ready-made tool or a custom build is the right answer. No spam, no
              obligation.
            </p>
            <div className="mt-8" style={{ display: 'flex', justifyContent: 'center', gap: 12, flexWrap: 'wrap' }}>
              <ModalCTAButton label="Talk to the Founder" region="au" modalVariant="default" btnVariant="primary-light" />
              <a className="btn btn-outline" href="/au/ai-consulting" style={{ color: '#fff', borderColor: 'rgba(255,255,255,.25)' }}>Start with AI consulting</a>
            </div>
          </div>
        </section>

      </main>
      </div>

      <SiteFooter linkColumns={AU_FOOTER_COLUMNS} variant="dark" tagline="Ecommerce, AI agents, websites and AI search for Australian businesses. Built by senior engineers, supported after launch, owned by you." />
    </>
  );
}
