/**
 * AI Consulting (/services/ai-consulting) FAQ: the single source for the visible
 * accordion in AiConsultingSections.tsx AND the FAQPage JSON-LD in
 * src/app/services/ai-consulting/page.tsx. Never duplicate these strings elsewhere.
 *
 * Questions: Google People Also Ask for US searches (DataForSEO, location 2840) on
 * "ai consulting services", "ai consulting company", "ai strategy consulting",
 * "ai implementation services", "ai readiness assessment" (2026-09-26 pull) plus one
 * extra pass on "ai consulting for small business", "ai implementation consultant",
 * "what does an ai consultant do", "ai strategy consultant" and "ai implementation cost"
 * (2026-09-26, US$0.011). Career and salary questions were left out on purpose.
 * No FactoryJet prices on this service page: cost answers explain pricing models and
 * link the cost guides.
 */

export const AI_CONSULTING_FAQ_CATEGORIES = [
  { id: 'faq-what', label: 'What AI consulting is' },
  { id: 'faq-readiness', label: 'AI readiness' },
  { id: 'faq-rules', label: 'Rules of thumb & failure rates' },
  { id: 'faq-cost', label: 'Cost & value' },
  { id: 'faq-smb', label: 'Small & mid-size business' },
  { id: 'faq-choose', label: 'Choosing a firm' },
  { id: 'faq-work', label: 'Working with FactoryJet' },
] as const;

export interface AiConsultingFaq {
  id: string;
  category: (typeof AI_CONSULTING_FAQ_CATEGORIES)[number]['id'];
  question: string;
  answer: string;
}

const RAW: ReadonlyArray<Omit<AiConsultingFaq, 'id'>> = [
  // What AI consulting is
  { category: 'faq-what', question: 'What is AI consulting services?', answer: 'AI consulting services help a business decide where artificial intelligence will pay off, check whether its data and systems are ready, and then put the chosen AI into daily work. A full engagement covers four things: a readiness assessment, a ranked list of use cases, the build or purchase of the AI, and support after launch. Some firms stop after the plan. FactoryJet carries the plan through to working software.' },
  { category: 'faq-what', question: 'What does an AI consulting company do?', answer: 'An AI consulting company studies how your business runs, finds the tasks where AI saves real time or wins real revenue, and recommends what to build, buy or skip. A good one also estimates the effort, flags data and risk problems early, and stays for the rollout. The weaker ones hand over a slide deck and leave your team to work out the hard part, which is getting AI to run on your real systems.' },
  { category: 'faq-what', question: 'What does an AI consultant actually do?', answer: 'Day to day, an AI consultant interviews the people who do the work, maps each process step by step, looks at the data those steps produce, and tests whether an AI model can do part of the job well enough. Then they write down what to change, in what order, and what it will take. Implementation consultants go further and configure, connect and test the AI inside your tools.' },
  { category: 'faq-what', question: 'What is an AI strategy consultant?', answer: 'An AI strategy consultant helps leadership decide where AI fits in the business plan. The output is a short list of priorities: which departments go first, which problems are worth solving with AI, what to leave alone, how to handle risk, and how to measure success. Strategy is the first step, not the whole job. Without someone to build and support what the strategy picks, it stays on paper.' },
  { category: 'faq-what', question: 'What is the difference between AI consulting and AI development?', answer: 'AI consulting decides what to do and why. AI development builds it. Consulting produces the readiness assessment, the use-case roadmap and the build-or-buy call. Development produces the working software: the agent, the model integration or the automated workflow. At FactoryJet the same team does both, so the people who scope the work are the people who build it. See our AI development and AI agent development pages for the build side.' },
  { category: 'faq-what', question: 'What are AI implementation services?', answer: 'AI implementation services take a chosen AI use case and make it work inside your business. That means connecting the AI to your CRM, ERP, help desk or store, setting permissions, testing it on real cases, training your staff, and watching it after launch. Implementation is where most AI projects succeed or fail, because a model that works in a demo often breaks on messy real data.' },
  // AI readiness
  { category: 'faq-readiness', question: 'What is an AI readiness assessment?', answer: 'An AI readiness assessment is a structured check of whether your business can use AI well today. It looks at five areas: the quality and access of your data, the systems AI would connect to, the processes it would change, the people who would use it, and the risk and compliance rules that apply. The output is a score per area, a list of gaps, and the use cases you could start now.' },
  { category: 'faq-readiness', question: 'What are the five pillars of AI readiness?', answer: 'Most frameworks use five pillars: data (is it accurate, complete and reachable), technology (can your systems connect to AI through APIs), process (is the work written down clearly enough to automate), people (do staff have the skills and the willingness to use it), and governance (who approves AI decisions and how risk is managed). Our assessment scores each pillar separately, because one weak pillar can sink a project.' },
  { category: 'faq-readiness', question: 'What are the five stages of AI readiness?', answer: 'A common way to describe the stages is: unaware, exploring, experimenting, operating and scaling. Unaware businesses have no AI plan. Exploring businesses are reading and asking. Experimenting businesses run pilots and personal tools. Operating businesses have at least one AI system in daily work with an owner. Scaling businesses repeat that pattern across departments. Most small and mid-size businesses we meet sit between exploring and experimenting.' },
  { category: 'faq-readiness', question: 'How do I know if my business is ready for AI?', answer: 'Ask four questions. Do you have a repeated task that eats hours every week? Does that task leave a digital trail, such as emails, tickets, orders or forms? Can your main systems export or share data through an API? Is there one person who will own the result? If you can answer yes to all four, you are ready for a first project. If not, the assessment shows what to fix first.' },
  // Rules of thumb
  { category: 'faq-rules', question: 'What is the 30% rule for AI?', answer: 'There is no official 30% rule. People use the phrase loosely, in a few different ways. One version is a planning rule of thumb that AI should take on about 30% of a role\'s routine work while people keep the judgment calls, or that a first project should aim to automate around 30% of a process rather than all of it. Treat it as a reminder to start partial and measured, not as a standard.' },
  { category: 'faq-rules', question: 'What is the 10/20/70 rule for AI?', answer: 'It comes from BCG. The rule says only about 10% of the value from an AI transformation comes from the AI application itself, 20% from the data and technology underneath it, and 70% from people and process: workflow redesign, culture, governance and how staff work with the AI. The practical lesson is that most of the effort in a good AI project is not the model.' },
  { category: 'faq-rules', question: 'Why do most AI projects fail?', answer: 'Mostly for reasons that are not about the model. MIT\'s NANDA initiative, reported by Fortune in August 2025, found that about 95% of generative AI pilots in its study had no measurable effect on profit, and blamed a learning gap in how tools fit into real work. The same research found purchased tools and outside partners succeeded about twice as often as internal builds, roughly 67% versus one third.' },
  { category: 'faq-rules', question: 'What are the top 5 AI services?', answer: 'The five AI services businesses ask for most are: customer support agents that answer and route tickets, sales assistants that research and qualify leads, document processing that reads invoices, orders and forms, workflow automation that moves data between systems, and AI search and content work so assistants like ChatGPT can find you. A consultant should tell you which of these fits your business first.' },
  // Cost & value
  { category: 'faq-cost', question: 'How much does an AI consultant cost?', answer: 'Freelance AI consultants charge about $75 to $150 an hour and boutique AI agencies $125 to $250 an hour, according to Layer3 Labs. Consultants bill in three ways: an hourly or day rate, a fixed fee for a scoped project such as a readiness assessment, or a monthly retainer for ongoing advice and support. The price moves with seniority, scope, and whether the consultant also builds. We give a fixed quote before any work starts, and our cost guides cover typical market ranges in detail.' },
  { category: 'faq-cost', question: 'How much does AI implementation cost?', answer: 'An AI discovery engagement costs about $2,000 to $5,000, and a first production workflow $5,000 to $25,000, according to Layer3 Labs. Cost depends on four things: infrastructure and model usage, integration with the systems you already run, maintenance and retraining over time, and the people needed to build and manage it. Harvard Business School Online uses the same four buckets. A narrow agent connected to one system costs far less than a multi-system rollout. Our AI agent cost guide breaks down typical ranges by project type.' },
  { category: 'faq-cost', question: 'How much does AI cost for a small business?', answer: 'A first done-for-you AI install for an owner-led business typically costs $4,500 to $25,000, according to a September 2026 market range from consultant Justin McKelvey. Keep that first step small: one process, one system, one owner. Off-the-shelf AI tools charge per seat or by usage. A custom build adds a one-time project fee and usually a smaller monthly support and usage cost. The expensive mistake is buying many subscriptions before knowing which process to fix. Our cost guides show typical ranges.' },
  { category: 'faq-cost', question: 'Is it worth paying for AI consulting?', answer: 'It is worth it when the consultant\'s advice changes what you build or stops you buying the wrong thing. A readiness assessment that kills a bad project early can save far more than it costs. It is not worth it if you already know the exact use case and have developers who can build it. In that case, skip the strategy work and go straight to a scoped build.' },
  // Small & mid-size business
  { category: 'faq-smb', question: 'Is AI consulting worth it for a small business?', answer: 'Yes, if it is sized for a small business. You do not need a transformation program. You need someone to find the one or two tasks where AI clearly pays off, confirm your tools can support it, and build it properly. U.S. Census Bureau survey data from December 2025 to May 2026 shows only about 17% to 20% of U.S. businesses using AI, so a well-chosen first project can still put you ahead.' },
  { category: 'faq-smb', question: 'Which AI is best for small business owners?', answer: 'The best AI is the one that fits a job you already do every day. For writing and research, a general assistant such as ChatGPT, Claude or Gemini on a business plan is enough. For customer questions, an AI support agent connected to your help desk works better. For bookkeeping, orders or scheduling, look first at the AI already built into the software you pay for, then build custom only where it falls short.' },
  { category: 'faq-smb', question: 'Should we build custom AI or buy an off-the-shelf tool?', answer: 'Buy when a proven tool already does the job inside software you use, and your process is standard. Build when the work depends on your own data, rules or several connected systems, or when the tool you would buy cannot see the information it needs. MIT research reported by Fortune found purchased tools and partnerships succeeded more often than solo internal builds. Our build vs. buy guide walks through the decision.' },
  // Choosing a firm
  { category: 'faq-choose', question: 'What are the top 10 AI consulting companies in the USA?', answer: 'It depends on your size. Firms on Google page one for AI consulting in the US include EY, IBM Consulting, BCG, The Hackett Group and Centric Consulting. IBM says it has over 75,000 consultants trained in generative AI. Those firms are built for large budgets and long programs. Small and mid-size businesses are often better served by a firm that scopes tightly and also builds. Our list of the best AI consulting firms in the USA compares options by business size.' },
  { category: 'faq-choose', question: 'Who are the Big 4 in AI consulting?', answer: 'The Big Four are the professional services firms Deloitte, PwC, EY and KPMG. Each sells consulting alongside audit and tax, and AI is now part of that consulting work. EY, for example, runs a dedicated US AI consulting practice. These firms are strongest on enterprise strategy, risk and governance. For a business with a few hundred employees or fewer, a focused firm that can advise and also build is usually a better fit.' },
  { category: 'faq-choose', question: 'How do I choose an AI consulting firm?', answer: 'Check five things. Can they show AI they built that is running today, not only reports? Will the people who scope the work also build it? Do they give a fixed quote for a defined scope? Who owns the code, prompts and accounts at the end? What happens after launch, and who fixes it when a model or an API changes? A firm that answers all five plainly is worth a call.' },
  { category: 'faq-choose', question: 'What questions should I ask an AI consultant before hiring?', answer: 'Ask: What would you not recommend we build, and why? What data will you need from us, and in what state? How will we measure success in the first 90 days? What happens to our data, and does any provider train on it? Who owns the finished work? What does support look like after launch? Vague answers to the data and support questions are the clearest warning sign.' },
  // Working with FactoryJet
  { category: 'faq-work', question: 'How long does AI implementation take?', answer: 'The readiness assessment is a short, fixed-scope piece of work. After that, a narrow, well-scoped AI agent typically reaches its first production deployment in 3 to 12 weeks. Timelines stretch when the AI must connect to several systems or handle many edge cases that need real testing. We give you a dated plan with the fixed quote, before work starts.' },
  { category: 'faq-work', question: 'Who owns the AI systems FactoryJet builds?', answer: 'You do. The code, prompts, workflows, configuration and every account with AI and cloud providers are set up in your name. If you ever move to another team, you take all of it with you. We build the agents for you as a deliverable you own. We do not rent you a platform, and nothing we build stops working because you stop working with us.' },
  { category: 'faq-work', question: 'Do you support the AI after launch?', answer: 'Yes. Support is the part most consultants skip and the part that decides whether AI keeps working. AI models change, APIs change, and your business changes. We monitor the systems we build, review errors and edge cases, adjust prompts and rules, and report what the AI handled each month. Our AI agent monitoring page describes the support plan in detail.' },
  { category: 'faq-work', question: 'How do you handle our data and AI risk?', answer: 'We map the data each use case touches during the assessment, keep AI access to the minimum it needs, and set up AI providers on business or API accounts in your name, choosing settings where the provider says your data is not used for training. We use the NIST AI Risk Management Framework as a checklist for risk and approvals, and we keep a person in the loop wherever an AI decision carries real consequences.' },
  { category: 'faq-work', question: 'What industries does FactoryJet do AI consulting for?', answer: 'Mostly commerce and operations-heavy businesses: ecommerce and B2B wholesale, manufacturing, healthcare practices and dental groups, law firms, property management, restaurants and automotive dealers. We have industry pages for each with the specific agents we build. For regulated work, we map the rules that apply and work with your own counsel. We do not give legal advice.' },
];

export const AI_CONSULTING_FAQS: AiConsultingFaq[] = RAW.map((faq, i) => ({ ...faq, id: `Q${String(i + 1).padStart(2, '0')}` }));
