/**
 * AI Search & SEO hub FAQ: the single source for the visible accordion in
 * AiSeoHubSections.tsx AND the FAQPage JSON-LD in src/app/services/ai-seo/page.tsx.
 * Never duplicate these strings elsewhere. Questions come from Google People Also Ask
 * and DataForSEO research for the US and India, 2026-09-23. Four questions were ported
 * from the pre-redesign page (classic SEO merge of 2026-09-23 and the Perplexity answer).
 */

export const AI_SEO_FAQ_CATEGORIES = [
  { id: "faq-what", label: "What AI SEO is" },
  { id: "faq-engines", label: "ChatGPT, Perplexity & AI Overviews" },
  { id: "faq-classic", label: "Classic SEO" },
  { id: "faq-method", label: "How we work" },
  { id: "faq-cost", label: "Cost & contracts" },
  { id: "faq-choose", label: "Choosing an agency" },
  { id: "faq-market", label: "US & India" },
] as const;

export interface AiSeoFaq { id: string; category: string; question: string; answer: string }

export const AI_SEO_FAQS: AiSeoFaq[] = [
  { id: 'Q01', category: "faq-what", question: "What is AI SEO, or AI search optimization?", answer: "AI SEO, also called AI search optimization, is the work of getting your website named and quoted as a source when AI tools answer a question. It builds on normal SEO: clean structure, fast pages and real authority. Then it adds three things on top: access for the bots that fetch pages for AI answers, pages formatted so a short answer can be lifted out, and mentions on other sites that the AI engines treat as proof you are credible." },
  { id: 'Q02', category: "faq-what", question: "What is an AI SEO agency?", answer: "An AI SEO agency gets your business cited and recommended by ChatGPT, Perplexity, Claude, Gemini and Google AI Overviews. It does four jobs: it opens crawler access, restructures pages so answers are easy to lift, adds schema markup machines can read, and earns third-party mentions. Some call this an AEO agency or a GEO agency. A good one also tracks how often each engine names you, not just where you rank on Google." },
  { id: 'Q03', category: "faq-what", question: "What are AI SEO services?", answer: "AI SEO services are the specific pieces of work behind AI search visibility: an audit of where AI engines cite you today, robots.txt rules for retrieval bots, schema in JSON-LD, answer-first page rewrites, third-party citation work, and monthly tracking of citations per engine. At FactoryJet they run on the same retainer as classic SEO, because most of the same fixes help both." },
  { id: 'Q04', category: "faq-what", question: "What is the difference between GEO, AEO, LLM SEO, ChatGPT SEO and AI SEO?", answer: "Mostly the label. GEO, generative engine optimization, leans toward engines that write answers, like ChatGPT and Perplexity. AEO, answer engine optimization, leans toward direct answers such as Google AI Overviews and featured snippets. LLM SEO and ChatGPT SEO are the same job again. Buy the work, not the acronym. Our generative engine optimization page covers the GEO half in full detail." },
  { id: 'Q05', category: "faq-what", question: "How is AI SEO different from traditional SEO? Will I lose my Google rankings?", answer: "Traditional SEO aims for a high position in a list of links. AI SEO aims to be quoted inside a written answer. You do not trade one for the other. Most of the work that earns a citation, like schema, clear structure, expert content and outside mentions, also helps your Google position. That is why every monthly report we send carries both numbers." },
  { id: 'Q06', category: "faq-what", question: "What does answer engine optimization do?", answer: "It makes one clear answer on your page easy to lift. An answer engine wants roughly 40 to 60 words that settle the question, near the top of a clearly labeled section, backed by schema. AEO is the formatting half of AI SEO. Sold on its own it usually disappoints, because formatting alone does not build the authority engines look for." },
  { id: 'Q07', category: "faq-engines", question: "Which AI engines do you optimize for?", answer: "ChatGPT, Perplexity, Claude and Gemini, plus Google AI Overviews. We track how often each one cites you every month. Many agencies focus only on AI Overviews because it reuses their Google playbook. We treat ChatGPT and Perplexity as first-class targets too, because that is where many buyers now start their research." },
  { id: 'Q08', category: "faq-engines", question: "Which AI crawlers do I need to allow in robots.txt?", answer: "Name each one instead of relying on a wildcard. The retrieval crawlers that decide citations are OAI-SearchBot, Claude-SearchBot, Claude-User, PerplexityBot, Perplexity-User and Googlebot. GPTBot and ClaudeBot are training crawlers, so blocking them is a rights decision, not a visibility one. Google-Extended and Applebot-Extended control training separately. OpenAI says a robots.txt change takes about 24 hours to register." },
  { id: 'Q09', category: "faq-engines", question: "How do I rank in ChatGPT answers?", answer: "Four steps, in order. Allow OAI-SearchBot, because OpenAI says sites that block it will not show in ChatGPT search answers. Put a direct answer in the first 40 to 60 words under each heading. Get into the ordinary web results ChatGPT searches behind the scenes. Then earn mentions on sites it already trusts. Heavy JavaScript hurts you more here than on Google." },
  { id: 'Q10', category: "faq-engines", question: "Is Perplexity worth optimizing for?", answer: "Yes, especially for B2B and research-heavy purchases. Perplexity shows its sources in every answer, which makes it the easiest engine to measure yourself against. People using it are often deep in research and close to a decision, so a citation there reaches buyers at a useful moment." },
  { id: 'Q11', category: "faq-engines", question: "How do I show up in Google AI Overviews, and why am I not getting one?", answer: "These are two different problems. Showing up takes answer-first formatting, schema, and enough authority that Google is comfortable quoting you. Seeing no Overview at all usually means Google judged the search too unclear, too commercial or too sensitive. Overviews also come and go from week to week, so judge them over a month, never a single day." },
  { id: 'Q12', category: "faq-engines", question: "Can ChatGPT do SEO?", answer: "ChatGPT can help with parts of SEO. It can draft outlines, suggest title tags and explain a technical error. It cannot change your site, fix your crawl settings, earn mentions on other websites, or check whether its own suggestions are true. It also cannot make itself cite you. Use it as a helper, and let people with real experience make the calls." },
  { id: 'Q13', category: "faq-engines", question: "Is there an AI that can do SEO for me?", answer: "Not end to end. AI tools are good at research, first drafts and spotting technical issues at scale. SEO results still depend on decisions and work no tool does on its own: choosing which pages matter, fixing the site, writing from real expertise, and getting other sites to mention you. A tool gives you data. You still need someone to act on it." },
  { id: 'Q14', category: "faq-engines", question: "What are the best AI SEO tools, and which AI agent is best for SEO?", answer: "There is no single best one, because each does a different job. ChatGPT, Claude and Gemini are good for drafts, outlines and explaining errors. Content tools such as Surfer score a draft against the pages that already rank. For repeat work, like checking hundreds of product pages, a custom AI agent can run the checks for you. We build those agents too, and a person still signs off every change." },
  { id: 'Q15', category: "faq-engines", question: "Do keywords still matter in AI search?", answer: "Yes, but they work differently. People type short keywords into Google and ask long, full questions in ChatGPT or Perplexity. So you still research keywords, then you also map the real questions buyers ask and answer each one plainly. The engines also look at entities, meaning the clear facts about who you are, what you sell and where you work. Keywords get you found. Clear facts get you quoted." },
  { id: 'Q16', category: "faq-classic", question: "Do you still do traditional SEO, or only AI SEO?", answer: "Both, on the same retainer. Technical fixes, content and authority are the base that Google rankings and AI citations both sit on, so we do not split them into two products. If all you want is classic SEO, we can scope that too. Each SEO service has its own page in the SEO services section above. Search is not all we do either: we also build ecommerce stores, AI agents and websites." },
  { id: 'Q17', category: "faq-classic", question: "What are the main SEO services?", answer: "Most SEO work falls into five groups. Technical SEO makes the site easy to crawl and fast. On-page SEO shapes titles, headings and content around what buyers search for. Content creates pages that answer real questions. Authority work earns links and mentions. Local SEO covers your Google Business Profile and map results. We add AI search visibility on top of all five." },
  { id: 'Q18', category: "faq-classic", question: "Is SEO still worth it in 2026?", answer: "Yes. AI assistants still pull from web pages, and Google still sends people to websites. What changed is where the answer shows up. A page that ranks well, loads fast and states a clear answer now has two ways to win: a click from the results page and a mention inside an AI answer. Skipping SEO means giving up both." },
  { id: 'Q19', category: "faq-classic", question: "Is SEO dead now with AI, and is GEO replacing SEO?", answer: "No, but it has changed shape. Pew Research found that people click a website less often when Google shows an AI summary. So the goal has widened: rank for the search, and be one of the sources the AI summary quotes. GEO is not replacing SEO. AI engines still read the web pages that search engines index, so GEO is SEO with an extra layer on top." },
  { id: 'Q20', category: "faq-classic", question: "What is an SEO company, and what does an SEO agency do?", answer: "An SEO company, or SEO agency, is a team you hire to get more of the right people to your website from search. The work covers fixing technical problems, improving pages, writing content buyers search for, earning mentions on other sites, and reporting on what changed. A good one tells you what it will change on your site each month, not just which keywords it will watch." },
  { id: 'Q21', category: "faq-classic", question: "What are the best SEO tools?", answer: "Start with the free ones from the search engines. Google Search Console shows which searches bring people to your site, Bing Webmaster Tools does the same for Bing, and Google Analytics 4 shows what visitors do next. For deeper research, most teams add one paid suite such as Semrush or Ahrefs, and a crawler such as Screaming Frog. The simplest place to begin is Search Console." },
  { id: 'Q22', category: "faq-classic", question: "Can I do SEO myself?", answer: "Yes, you can do the basics yourself. Set up Google Search Console, write a clear title and description for each page, answer real customer questions on your site, and keep your Google Business Profile up to date. It gets harder once you need technical fixes, schema, or mentions on other websites. That is usually the point where hiring help saves you time." },
  { id: 'Q23', category: "faq-classic", question: "Can you optimize my current website, or do I need a new one?", answer: "Usually we optimize the site you already have. If it is too slow or cannot be crawled properly, a rebuild can cost less than patching it, and because we also build websites, the same team can do that work. It is a recommendation when the numbers call for it, never a forced upsell." },
  { id: 'Q24', category: "faq-classic", question: "Should I hire an SEO agency near me or a remote one?", answer: "Search for an SEO agency near me and you mostly get local generalists who also do social media and print. For search work alone, a specialist that works remotely often does better, because what matters is who does the work, not where their office is. We work with clients across the US and India, and our city SEO pages cover what ranking in each local map pack takes." },
  { id: 'Q25', category: "faq-classic", question: "How long does SEO take to work?", answer: "You will usually see a first measurable lift in 30 to 90 days from technical fixes and quick-win content, with results building by month four to six. AI citations can move faster once crawler access and answer blocks are fixed, but they also go up and down from week to week. Anyone promising page one in a week is selling something that will not last." },
  { id: 'Q26', category: "faq-classic", question: "Do you guarantee first-page Google rankings?", answer: "No. No honest SEO company can guarantee a ranking or an AI citation, because Google and the AI engines decide those, not the agency. What we do promise is the work itself, full transparency about what we changed, and a monthly report that shows whether it is working. If it is not moving, we change the plan." },
  { id: 'Q27', category: "faq-classic", question: "Do you do local SEO and Google Business Profile work?", answer: "Yes. Local SEO is one of our core services. We tune your Google Business Profile, build local landing pages, and keep your name, address and phone details consistent across the web, so you show up in the map pack and in near-me searches across your service area. Our local SEO page covers the full scope." },
  { id: 'Q28', category: "faq-classic", question: "Do you offer ecommerce and Shopify SEO?", answer: "Yes. We handle ecommerce SEO for Shopify, WooCommerce and custom stores. That covers category and product page structure, Product and Offer schema, duplicate URLs, faceted navigation and the technical issues that quietly cap store traffic. Shopify stores have their own quirks, like duplicate collection URLs, so they get a dedicated Shopify SEO service." },
  { id: 'Q29', category: "faq-classic", question: "What is technical SEO and why does it matter?", answer: "Technical SEO makes sure search engines and AI crawlers can fetch, read and trust your site. It covers crawl settings, page speed, schema, indexing, redirects and internal links. It matters even more for AI search, because most AI crawlers do not run JavaScript the way a browser does. Content that only appears after scripts run can be invisible to them." },
  { id: 'Q30', category: "faq-classic", question: "Which industries do you work with?", answer: "We run dedicated SEO programs for healthcare practices, dental practices, law firms and roofing companies, plus ecommerce brands, B2B companies and small businesses in the US and India. Each industry has its own rules. Healthcare and legal pages need stronger trust signals, and roofing demand spikes after storms, so the plan changes with the market you are in." },
  { id: 'Q31', category: "faq-method", question: "What is included in the AI visibility audit?", answer: "Four parts. A scan of how often ChatGPT, Perplexity, Claude, Gemini and Google AI Overviews cite you today. A gap report showing where competitors get cited and you do not. A review of your schema and crawler access listing what is missing or broken. And a 90-day roadmap in priority order, plus a strategy call with Bhavesh, our founder." },
  { id: 'Q32', category: "faq-method", question: "How do AI mentions turn into leads?", answer: "A mention only pays off if the visit that follows can turn into a lead. So we tag visits that arrive from ChatGPT, Perplexity, Gemini and other assistants in Google Analytics 4, and check where those people land. Then we make sure that page has a clear next step, like a short form or a booking link. The report shows AI-referred visits and the leads they became." },
  { id: 'Q33', category: "faq-method", question: "How do you write content that AI engines will cite?", answer: "A senior strategist briefs each article. Someone with real expertise writes it. We then edit it so each section opens with a clear answer, and add FAQPage, HowTo or Article schema. We do not ship generic AI-written filler. Bland model output is exactly the kind of content that does not get quoted, and the engines keep getting better at spotting it." },
  { id: 'Q34', category: "faq-method", question: "How do you get third-party citations? Do you do link building?", answer: "We pitch your named experts to industry publications, podcasts, expert directories and data partners that AI engines already read. It overlaps with link building, but the goal is a named mention and a source credit, not keyword-stuffed anchor text. No bulk guest posts, no private blog networks, nothing that breaks Google's spam policies." },
  { id: 'Q35', category: "faq-method", question: "What moves AI search visibility fastest?", answer: "Three things, in this order. Unblock the retrieval crawlers. Add a clear answer block and FAQPage schema to your ten most important commercial pages. Get named on two or three outside sites the engines already use. That is weeks of work, not quarters. Everything after that is the slower part that builds over time, and there is no shortcut through it." },
  { id: 'Q36', category: "faq-method", question: "How do you track AI citations?", answer: "We run a fixed set of buyer questions through ChatGPT, Perplexity, Claude and Gemini for your target topics and log every time you are cited. We also track Google AI Overview appearances and normal rankings. The same questions run on the same schedule every month, so a change in the numbers means something real, not a reworded prompt." },
  { id: 'Q37', category: "faq-method", question: "What do I get in the monthly report?", answer: "Citations per AI engine, and how you compare with named competitors. Google ranking changes, AI Overview appearances, and impressions and clicks from Search Console. Organic and AI-referred visits, with conversions where tracking is set up. Each number ties back to a line on your 90-day roadmap, so you can see the plan next to what actually happened." },
  { id: 'Q38', category: "faq-cost", question: "How much does AI SEO cost?", answer: "It depends on scope, which is why a rate without scope tells you very little. The main cost drivers are how many pages need structural work, how competitive your key searches are, how many AI engines you want tracked, whether we write new content or only restructure what you have, and whether outside citation work is included. We scope it on a short call and quote before any work starts." },
  { id: 'Q39', category: "faq-cost", question: "How much do SEO services typically cost?", answer: "Many agencies do not publish a rate, and prices vary a lot between markets like the US and India, and by scope. What should drive the number is the work: how many hours, who does them, and what changes on your site in month one. Very cheap plans often buy automated reports instead of real work. We give you a fixed quote on the same call where we scope the job." },
  { id: 'Q40', category: "faq-cost", question: "Is SEO costly? What is the cheapest way to do SEO?", answer: "The cheapest way is to do the basics yourself with free tools like Google Search Console. Paid SEO costs more when your market is crowded, your site has technical problems, or you need new content and outside mentions. Be careful with very low-priced packages. They often buy automated reports or low-quality links that can hurt you later. Pay for work you can see on your site." },
  { id: 'Q41', category: "faq-cost", question: "Why no annual contracts, and what happens if I cancel?", answer: "AI search shifts every quarter, so locking you into twelve months of a plan that may need to change by month four does not make sense. You give one billing cycle of notice. We finish the current month, hand over all work in progress, and transfer schema and content to your team. Everything we build is yours from day one." },
  { id: 'Q42', category: "faq-cost", question: "Can I start with just the audit?", answer: "Yes. The AI visibility audit is a complete deliverable. Many clients use it once and carry out the roadmap with their own team. Others move into a monthly retainer afterward. Either way, you own everything in the audit." },
  { id: 'Q43', category: "faq-choose", question: "How do I pick an AI SEO agency?", answer: "Three quick checks. One: do they track citations in ChatGPT, Perplexity, Claude and Gemini, or only Google AI Overviews? Two: does a senior person run your account, or an account manager passing notes to a team you never meet? Three: will they put a citation count per engine in writing every month? An agency that passes all three is worth a call." },
  { id: 'Q44', category: "faq-choose", question: "Which AI SEO agencies are the best?", answer: "It depends on what you need. On 23 September 2026, OuterBox, Level Agency, Thrive Agency and Coalition Technologies held page-one spots for ai seo agency in the US, and SEO Discovery and Techmagnate were the top two agency sites for the same search in India. Bigger shops suit buyers who want one vendor for every channel. FactoryJet fits companies that want Bhavesh, our founder, and the team on the account, with citation counts per engine." },
  { id: 'Q45', category: "faq-choose", question: "Why would I pick FactoryJet over a bigger AI SEO company?", answer: "Sometimes you should not. Established agencies have far more domain authority than we do. If the safest name on the invoice matters most, hire the incumbent. We win on how the work is delivered: Bhavesh, our founder, and the team run your account, you get citation counts per engine instead of a rankings PDF, and the terms are month to month." },
  { id: 'Q46', category: "faq-choose", question: "Who will I actually work with?", answer: "Bhavesh Barot, our founder, and the team run your account, including the senior engineers who make the site changes themselves. You will not be handed to a junior who rotates off the account next quarter, and you can reach the people doing the work directly." },
  { id: 'Q47', category: "faq-market", question: "Do you offer AI SEO services in both the US and India?", answer: "Yes. We run AI SEO and SEO programs for businesses in the US and India, with the same audit, the same site changes and the same monthly report. What changes is the research. Buyers in each country search with different words and see different competitors, so we pull keyword and results data for your market, not someone else's. India clients can also start from our AI SEO company in India page." },
  { id: 'Q48', category: "faq-market", question: "Is AI search used as much in India as in the US?", answer: "Both are big, early markets for it. When Google shared its numbers in July 2025, it said AI Mode, its chat-style search, had more than 100 million monthly users across the US and India. AI Overviews, the summary above the results, was live in more than 200 countries and territories and had 2 billion monthly users. So the same citation work matters in both places." },
  { id: 'Q49', category: "faq-market", question: "Who are the top SEO companies in India?", answer: "It changes by search and by week. On 23 September 2026, Google India showed Techmagnate first and SEO Discovery third for ai seo services, and SEO Discovery first for ai seo agency. For seo company, Semrush's agency directory and firms based in Chennai, Delhi and Gurugram filled page one. Check who ranks for your exact service, then ask each firm to show you its own reporting." },
];
