/**
 * Website Design hub FAQ: the single source for the visible accordion AND the
 * FAQPage JSON-LD in src/app/services/web-design/page.tsx. Never duplicate these
 * strings elsewhere. Built from Google People Also Ask + US/India keyword research,
 * 2026-09-23. No prices on this page: cost questions explain the cost drivers and
 * link to the cost guides.
 */

export const WEB_DESIGN_FAQ_CATEGORIES = [
  { id: "faq-hiring", key: "hiring", label: "Hiring a web design company" },
  { id: "faq-platforms", key: "platforms", label: "Choosing a website platform" },
  { id: "faq-cost", key: "cost", label: "Cost and timeline" },
  { id: "faq-redesign", key: "redesign", label: "Website redesign" },
  { id: "faq-ai", key: "ai", label: "AI, Google, and speed" },
  { id: "faq-working", key: "working", label: "Working with FactoryJet" },
] as const;

export interface WebDesignFaqLink { label: string; url: string }

export interface WebDesignFaq {
  id: string;
  category: string;
  question: string;
  answer: string;
  /** External source for a statistic in the answer, shown after it. */
  source?: WebDesignFaqLink;
  /** Internal guide linked after the answer. */
  link?: WebDesignFaqLink;
}

export const WEB_DESIGN_FAQS: WebDesignFaq[] = [
  { id: 'Q01', category: 'hiring', question: "What does a web design company do?", answer: "A web design company plans, designs, builds, and launches your website. That covers the page structure, the visual design, the code, mobile layouts, speed, and the SEO basics, and often hosting and support after launch. FactoryJet does all of it for B2B and service businesses, and builds every page so Google and AI assistants can read it from day one." },
  { id: 'Q02', category: 'hiring', question: "What do web development companies do?", answer: "A web development company writes and ships the code behind a website or web app. That includes the front end people see, the CMS your team edits, forms, logins, payments, and connections to tools like your CRM or booking system. Many firms, FactoryJet included, do design and development together, so one team owns the result from first sketch to launch." },
  { id: 'Q03', category: 'hiring', question: "What is the difference between web design and web development?", answer: "Web design decides what the site looks like and how people move through it: layout, type, color, and the path to contact you. Web development turns that design into working code and connects it to your tools. You need both. Hiring them separately is where many projects stall, because the design promises something the build can't deliver on time." },
  { id: 'Q04', category: 'hiring', question: "Which company is best for web design and development?", answer: "The best company is the one that fits your size, your buyers, and your budget, and can prove its work. Ask each shortlisted firm for live sites you can test on PageSpeed Insights, a fixed written scope, and a clear answer on who supports the site after launch. If a firm can't show all three, keep looking." },
  { id: 'Q05', category: 'hiring', question: "What are the top 10 web design companies in the USA and India?", answer: "Directories such as Clutch and DesignRush publish top 10 lists for both the USA and India, and some of their placements are sponsored. Use those lists to build a shortlist, not to decide. Then compare each firm on live site speed, a fixed written scope, who owns the code and accounts, and what happens after launch." },
  { id: 'Q06', category: 'hiring', question: "Is it worth hiring a web designer?", answer: "Yes, if your website has to win work. A DIY builder is fine for a hobby site or a simple one-pager. Once you depend on Google, run paid ads, or sell to buyers who compare vendors online, a designed and properly built site usually pays for itself through more calls and forms from the same traffic." },
  { id: 'Q07', category: 'hiring', question: "What are red flags when hiring a web designer?", answer: "Watch for five things. No fixed written scope. No live sites you can open and test. Your domain or hosting registered in their name. No plan for redirects if you already have a site. And a vague answer about who fixes things after launch. Any one of these tends to cost you more later than it saves now." },
  { id: 'Q08', category: 'hiring', question: "What are the big 3 of web development?", answer: "HTML, CSS, and JavaScript. HTML holds the content and structure, CSS controls how it looks, and JavaScript adds behavior. Every website uses all three, whether it runs on WordPress, Webflow, or Next.js. For search and AI, the key point is that your real content should sit in the HTML, not only appear after scripts run." },
  { id: 'Q09', category: 'hiring', question: "What are the 7 C's of website design?", answer: "The 7 C's come from Rayport and Jaworski's e-commerce framework: context, content, community, customization, communication, connection, and commerce. In plain terms: a clear layout, useful content, a reason to come back, a site that fits the visitor, a way to talk to you, links to and from other sites, and an easy way to buy or get in touch." },
  { id: 'Q10', category: 'hiring', question: "What are the 7 stages of web development?", answer: "A common way to split it: discovery and goals, planning the sitemap and content, design and wireframes, development, testing on real devices, launch with redirects and a sitemap, and maintenance after launch. Names vary between agencies, but a good one never skips testing or the plan for after launch. Our own process folds these into five steps: discover, design, build, launch, and support." },
  { id: 'Q11', category: 'hiring', question: "How do I choose a website development company?", answer: "Start with your needs: the pages, features, and platform you think you want, and your budget. Shortlist three firms whose portfolios include sites like yours, and open those sites on your phone. Ask each for a fixed written scope, who owns the code and accounts, how they handle redirects, and what support looks like after launch. Call one reference. Choose the clearest answers, not the lowest first quote." },
  { id: 'Q12', category: 'platforms', question: "What platform should my website be built on?", answer: "It depends on who edits the site, how big it will get, and what it has to connect to. WordPress suits content teams that publish often and need plugins. Webflow suits marketing teams that want visual control on a hosted plan. Framer suits fast launch and startup sites. Next.js with a headless CMS suits sites that need top speed or app features. If you sell online, look at Shopify, WooCommerce, or BigCommerce." },
  { id: 'Q13', category: 'platforms', question: "Should I choose WordPress or a custom build?", answer: "Choose WordPress if your team already knows it, publishes often, and needs plugins for things like events or memberships. Choose a custom build if speed, security, or unusual features matter more than a plugin library. Either way, the site should be fast, easy for your team to edit, and fully owned by you." },
  { id: 'Q14', category: 'platforms', question: "Is Webflow better than WordPress?", answer: "Neither is better for every site. Webflow is a hosted visual builder: design, hosting, and security updates come in one plan, and marketers can edit pages without plugins. WordPress is open source and self-hosted: you pick the host, get the largest plugin library, and can handle big content archives and memberships, but someone has to keep plugins and core updated. Pick Webflow for a lean marketing site, and WordPress when the site needs many features or a big blog." },
  { id: 'Q15', category: 'platforms', question: "What is the difference between Webflow and Framer?", answer: "Both are hosted visual website builders. Framer feels like a design tool, so designers can build and publish very quickly, and it shines for landing pages, startup sites, and motion. Webflow gives more control over structure, styles, and its CMS, which suits larger marketing sites with many collection pages and several editors. Both host your site on their own platform, so moving later usually means a rebuild. We pick based on site size and who will edit it." },
  { id: 'Q16', category: 'platforms', question: "Is Next.js good for SEO?", answer: "Yes, when it is set up right. Next.js can render pages on the server or build them ahead of time, so the full content is in the HTML the moment a crawler asks for it. Google says server-side or pre-rendering is still a great idea because it makes sites faster and not all bots can run JavaScript. The risk is a Next.js site that only loads content in the browser. We ship server-rendered pages with metadata, schema, and a sitemap.", source: { label: "Google Search Central", url: "https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics" } },
  { id: 'Q17', category: 'platforms', question: "What is a headless CMS, and do I need one?", answer: "A headless CMS stores your content, and a separate front end shows it. Sanity, Contentful, and headless WordPress are common examples. Your team edits in a clean editor while developers build the site in Next.js or Astro, so pages can be very fast and the same content can feed an app or several sites. You probably don't need one for a ten-page brochure site. It pays off for large content sites, several brands, or custom features." },
  { id: 'Q18', category: 'platforms', question: "Is WordPress outdated in 2026?", answer: "No. According to W3Techs, WordPress still runs about 40% of all websites in September 2026, far more than any other CMS, and its block editor is actively developed. What feels outdated is the typical build: a heavy theme, a page builder, and dozens of plugins that slow the site and need constant updates. A custom block theme with a short plugin list is fast and easy to edit. The platform is fine. The way it is often built is the problem.", source: { label: "W3Techs CMS usage", url: "https://w3techs.com/technologies/overview/content_management" } },
  { id: 'Q19', category: 'platforms', question: "What are the downsides of WordPress?", answer: "The main ones are upkeep and bloat. Core, theme, and plugin updates need regular attention, and plugins that fall behind on updates are a common security risk. Page builders and stacked plugins can make pages slow on a phone, and quality varies a lot between themes and plugins. All of this is manageable with a lean custom theme, a short plugin list, good hosting, and a maintenance plan, but someone has to own it." },
  { id: 'Q20', category: 'platforms', question: "Should I use a website builder like Wix or hire a web design company?", answer: "Use a builder like Wix or Squarespace if you need a simple site fast, you are happy to edit it yourself, and the site is not your main source of leads. Hire a web design company when the site has to rank, carry paid ads, connect to your CRM or booking tools, or win buyers who compare vendors. A builder is cheaper to start, but moving off it later usually means rebuilding the site from scratch." },
  { id: 'Q21', category: 'platforms', question: "Can I switch from WordPress to Webflow or Next.js without losing rankings?", answer: "Yes, if you treat the move as a migration and not just a rebuild. List every URL with traffic or links, keep the same URL paths where you can, and set a 301 redirect for each one that changes. Carry over titles, meta descriptions, headings, and structured data. Then submit the new sitemap and watch Search Console for a few weeks. Most ranking drops after a platform switch come from missing redirects." },
  { id: 'Q22', category: 'cost', question: "How much does it cost to have a website designed?", answer: "It depends on scope. The biggest cost drivers are the number of unique page designs, whether content and rankings have to move over from an old site, integrations such as booking, payments, or a CRM, and the platform you build on. A DIY builder costs the least to start, a freelancer template site costs more, and a custom agency build costs the most. Our US website cost guide breaks down typical ranges. We quote a fixed price after a scoping call.", link: { label: "US website cost guide", url: "/blog/how-much-does-a-website-cost-small-business-usa-2026" } },
  { id: 'Q23', category: 'cost', question: "How much should I pay a website designer?", answer: "Pay for the scope, not the hours. A fair quote lists every page, every integration, redirects if you have an old site, and what support you get after launch. Compare two or three quotes written against the same scope, and be wary of a low price that leaves out content migration or fixes after launch. Our US website cost guide shows typical ranges by type of provider.", link: { label: "US website cost guide", url: "/blog/how-much-does-a-website-cost-small-business-usa-2026" } },
  { id: 'Q24', category: 'cost', question: "How much does it cost to pay someone to build my website?", answer: "It depends on how many pages you need, how custom the design is, and what the site must connect to. Booking, payments, logins, and CRM connections all add build time. Get two or three fixed quotes on the same written scope so you compare like for like. For typical ranges, see our US website cost guide. We give you a fixed proposal after a scoping call.", link: { label: "US website cost guide", url: "/blog/how-much-does-a-website-cost-small-business-usa-2026" } },
  { id: 'Q25', category: 'cost', question: "How long does it take to build a website?", answer: "A small site of up to five pages can launch in about seven business days after you approve the design. A 10 to 20 page site with content moved over from an old site usually takes two to four weeks. Web apps and large sites take longer and get a phased timeline. We confirm dates in writing after the scoping call." },
  { id: 'Q26', category: 'cost', question: "What are the ongoing costs after launch?", answer: "Plan for a yearly domain renewal, monthly hosting, any paid plugins or platform plans (Webflow and Framer both charge a monthly site plan), and someone to handle updates, backups, and security checks. You can do that yourself or keep us on a monthly support plan. There is no FactoryJet license fee to keep your site online, and the domain and hosting stay in your name. Our cost guide covers typical figures.", link: { label: "US website cost guide", url: "/blog/how-much-does-a-website-cost-small-business-usa-2026" } },
  { id: 'Q27', category: 'cost', question: "How much does it cost for someone to update your website?", answer: "Small text or image changes are usually covered by a monthly support plan, if you choose one. Bigger changes, like new pages or a new booking flow, are quoted as a small fixed project. If your team edits content itself in the CMS, many updates cost nothing beyond your own time, and we show your team how to do that at handoff." },
  { id: 'Q28', category: 'redesign', question: "How much should a website redesign cost?", answer: "It depends on how many pages you have, whether you change platforms, how much content moves over, and how many URLs need redirects. Moving old content and mapping redirects is the cost most quotes leave out, so make sure it is written into the scope. Our website redesign cost guide covers typical ranges, and we quote a fixed price after reviewing your current site.", link: { label: "Website redesign cost guide", url: "/blog/website-redesign-cost-us-small-business-2026" } },
  { id: 'Q29', category: 'redesign', question: "How do I know if my website needs a redesign?", answer: "Redesign when the problem is under the surface. Signs include a slow mobile PageSpeed score, a platform you can't update or edit, forms that rarely produce leads, and a site you can't change without calling the person who built it. If the platform and speed are fine and only the look is dated, a smaller refresh may be enough." },
  { id: 'Q30', category: 'redesign', question: "What is the difference between a website redesign and a refresh?", answer: "A refresh changes the look: colors, images, fonts, and small layout fixes, on the same platform and code. A redesign rebuilds the site, often on a new platform, with new structure, new code, and content moved over. Choose a refresh if your speed and platform are healthy. Choose a redesign if either one is broken." },
  { id: 'Q31', category: 'redesign', question: "Will a website redesign hurt my Google rankings?", answer: "Not if it is done carefully. Before launch we list every URL that gets traffic or links, keep the strong pages, and set a 301 redirect from every old URL that changes to its new home. On launch day we submit the new sitemap in Search Console and watch rankings for the next few weeks. Missing redirects cause most ranking drops." },
  { id: 'Q32', category: 'redesign', question: "Can AI redesign my existing website?", answer: "AI tools can suggest layouts, draft copy, and write code fast, and we use them. But they don't know which of your pages bring in leads, which URLs need redirects, or what your buyers ask on sales calls. A redesign that skips that work can look new and still lose traffic. Use AI for speed, and people for the decisions." },
  { id: 'Q33', category: 'ai', question: "Is AI replacing web designers?", answer: "No. AI now drafts layouts and code quickly, but it doesn't know your buyers, your offer, or why someone should call you instead of a competitor. The work has moved from pushing pixels toward strategy, content, speed, and conversion. Good web teams use AI to move faster, not to skip the thinking." },
  { id: 'Q34', category: 'ai', question: "Can ChatGPT design or build a website?", answer: "ChatGPT can draft page copy, sketch a layout, and write code for a simple page, and builder tools can turn a prompt into a basic site. That's useful for a first draft. It won't plan your pages around what buyers ask, set up redirects from your old site, or connect your CRM and booking tools. Someone still has to own the result." },
  { id: 'Q35', category: 'ai', question: "Is web design still worth it in 2026?", answer: "Yes. More buyers now ask ChatGPT, Perplexity, or Google's AI Overviews before they visit a site, and those tools pull from pages they can read and trust. A clear, fast, well-structured website is what gets you named in those answers, and it's still where the buyer lands before they call or fill in a form." },
  { id: 'Q36', category: 'ai', question: "How do you make a website readable by Google and AI assistants?", answer: "Put the real content in the HTML, use one clear H1 and a logical heading order, answer common buyer questions directly, add structured data for your business, services, and FAQs, keep pages fast, and let search and AI crawlers in through robots.txt. Google says no special markup is needed for its AI features. It's good SEO, done properly." },
  { id: 'Q37', category: 'ai', question: "Will my website work on mobile?", answer: "Yes. We design phone layouts first, then scale up to desktop, and test on real iOS and Android devices. We check tap targets, text size, and forms, and measure Core Web Vitals, the speed and stability scores Google uses, before launch. You get the PageSpeed report at handoff so you can check it yourself." },
  { id: 'Q38', category: 'working', question: "Do I get to approve the design before you start building?", answer: "Yes, always. We design every page type in Figma for desktop and mobile, and you approve it before any code is written. Changes are cheap at the design stage and expensive after the build, so we would rather revise twice in Figma than once in code." },
  { id: 'Q39', category: 'working', question: "Do I own the website and code after the project?", answer: "Yes. The code goes into a repository in your account, and the domain, hosting, analytics, and Search Console stay in your name. You also get the Figma design files. There is no platform fee to us to keep the site running, so if you ever change agencies, you take everything with you." },
  { id: 'Q40', category: 'working', question: "Can I update my website without a developer?", answer: "Yes. Every build includes a CMS your team can use: the WordPress or Webflow editor, or a headless CMS such as Sanity for custom builds. We record a short walkthrough showing your team how to edit pages, add blog posts, and swap images, so routine changes never wait on us." },
  { id: 'Q41', category: 'working', question: "Can you add booking, payments, or intake forms?", answer: "Yes. We connect booking tools such as Calendly or Acuity, send form leads straight into HubSpot or Salesforce, and add Stripe for deposits and payments. For stores with a product catalog, our ecommerce team builds on Shopify, BigCommerce, or WooCommerce." },
  { id: 'Q42', category: 'working', question: "What happens after my website launches?", answer: "We stay. The team that built your site supports it after launch, so you are never chasing a vendor who stopped answering email the week after go-live. If you want ongoing help, we offer a monthly support plan for updates, backups, security checks, and small changes. Or you can run the site yourself, since you own the code and every account." },
  { id: 'Q43', category: 'working', question: "Do you build websites for small businesses?", answer: "Yes. Small businesses and B2B firms make up most of our website work. We also build industry sites for manufacturers, SaaS companies, law firms, real estate teams, restaurants, and nonprofits, each with its own page covering what that type of site needs." },
  { id: 'Q44', category: 'working', question: "Do you build websites for businesses in both the US and India?", answer: "Yes. The same team, process, and standards apply wherever you are: design approval before code, a speed check on a real phone, redirects for any old site, and full ownership of the code and accounts. Your price depends on your scope, not your location. Wherever you are, you get a fixed proposal after a scoping call." },
];
