import React from 'react';
import type { BlogPost } from '../data.types';

const BUILD_ROUTES = [
  { name: 'n8n', kind: 'Workflow and agent builder', url: 'https://n8n.io/ai-agents/', offer: 'Connect app events, workflow steps and an AI agent.', test: 'Replay the same event and inspect the stored identifier before a write.' },
  { name: 'Make', kind: 'Visual automation and agent builder', url: 'https://help.make.com/manage-ai-agents', offer: 'Configure agent behaviour and connect it to scenarios.', test: 'Check which scenario an agent can call and what happens when that call fails.' },
  { name: 'Lindy', kind: 'Configurable agent platform', url: 'https://www.lindy.ai/integrations', offer: 'Build workflows around supported app integrations.', test: 'Verify the exact action your connector can perform and the permission it needs.' },
  { name: 'Microsoft Copilot Studio', kind: 'Low-code agent and workflow studio', url: 'https://learn.microsoft.com/en-us/microsoft-copilot-studio/fundamentals-what-is-copilot-studio', offer: 'Build agents and workflows connected to organisational data and systems.', test: 'Confirm the identity used for each action and the deployment channel your team needs.' },
  { name: 'LangGraph', kind: 'Coding framework and runtime', url: 'https://docs.langchain.com/oss/python/langgraph/overview', offer: 'Engineer stateful workflows mixing fixed steps and model decisions.', test: 'Have an engineer demonstrate saved state and recovery after an interrupted run.' },
] as const;

const faqs = [
  { q: 'What is the best AI agent builder?', a: 'Choose the builder that passes the tests for your actual sources and permitted actions. Compare n8n, Make, Lindy and Copilot Studio for configurable workflows. Compare LangGraph when engineers need a coding framework. The table describes published offers, not a hands-on ranking of those tools. Check the connector and failure path before buying.' },
  { q: 'What is an AI agent builder?', a: 'An AI agent builder provides tools to configure a model-driven workflow, connect sources and expose actions. Some builders are visual products; others require code. A completed configuration still needs representative tests and an operating owner. Use the type column in this comparison to distinguish a configurable product from an engineering framework.' },
  { q: 'Where can I build my own AI agent?', a: 'You can evaluate the four configurable products in the table or use a coding framework such as LangGraph. Start in an isolated environment with approved sample data. Ask whether the chosen route can enforce your required source checks, action permissions and review steps before connecting production credentials.' },
  { q: 'Who builds AI agents for businesses?', a: 'Internal engineers, implementation partners and custom software agencies can build them. Some agencies configure existing products; others write application code. FactoryJet’s Washington Law Group case documents a custom research workflow with source checks and duplicate handling. Ask a supplier to state the route it proposes and which components you receive at handover.' },
  { q: 'Should I build or buy an AI agent?', a: 'Try a product when its supported tools and permissions cover your workflow. Scope custom engineering when a required source check, action or business rule needs work the product cannot provide. Compare both routes using the same acceptance examples. The ownership and operating responsibilities belong in the decision alongside the implementation estimate.' },
  { q: 'Can I build an AI agent without coding?', a: 'Visual products can cover some tasks without custom code. Confirm the required connector actions and the exception routes in the configuration you build. A missing API action or a business-specific calculation can still require engineering. For a news workflow, test a duplicate article and an unsupported extracted name before treating the configuration as complete.' },
  { q: 'Is LangGraph an AI agent platform?', a: 'LangGraph describes itself as an orchestration framework and runtime for stateful agents. It gives engineers control over fixed and model-driven steps. In this table it is the coding route. Your team still needs to decide how to deploy the application, manage credentials and handle failures after launch.' },
  { q: 'Should I choose n8n or Make for AI agents?', a: 'Give both the same workflow brief and check the required actions, operator visibility and failed-run handling. Their published pages describe agent capabilities within workflow environments. We have not benchmarked them side by side. Your test should include the same event arriving twice and the connected system rejecting a write.' },
  { q: 'When should I consider Microsoft Copilot Studio?', a: 'Evaluate it when the data connections, identity controls and publishing channels described by Microsoft match your organisation’s requirements. Ask your administrator to verify tenant access and licensing for the proposed workflow. Run the action under the intended user or service identity before assuming a demonstration has the permissions needed in production.' },
  { q: 'When should I consider Lindy?', a: 'Check Lindy’s integration catalogue when the workflow depends on common team tools. Confirm the specific trigger and action, rather than only the app name. For an inbox-to-CRM task, test a repeated message and a missing customer record. Agree who maintains the configuration and reviews failed runs after it is enabled.' },
  { q: 'Can I use a builder and custom code together?', a: 'Yes. A builder can handle routing while a custom component validates evidence or performs a restricted action. Write down the boundary and keep a shared identifier across both components so the operator can trace a run. Test failures on each side of that boundary and assign a maintenance owner for each.' },
  { q: 'How much does it cost to build your own AI agent?', a: 'Budget for implementation, connected software, model usage, hosting, review time and maintenance. Estimate the workflow using its real volume and agreed failure handling. FactoryJet quotes custom work after discovery. A product subscription and a development quote are comparable once each includes the same sources, permitted actions and operating responsibilities.' },
  { q: 'Can I create my own AI agent for free?', a: 'Some tools offer a trial or software you can start without a licence purchase. Verify the current terms. Connecting a live system still uses engineering or configuration time and can involve model, hosting and app charges. Include the time spent reviewing outputs and fixing failures when you assess the pilot.' },
  { q: 'What ongoing costs does a custom AI agent have?', a: 'Model calls, hosting, source subscriptions, operator review and engineering support can all continue after delivery. Our Washington Law Group case identifies dedicated hosting, encrypted backups and a client-owned news subscription. Those are costs and responsibilities the operating plan must account for alongside any model usage.' },
  { q: 'Does buying an AI agent remove the need for testing?', a: 'Your workflow still needs testing. A supported connector does not establish that the configured rules handle your missing fields, duplicates or approval limits. Give the product and a custom proposal the same input set. Keep the expected outputs so later configuration or model changes can be checked against them.' },
  { q: 'How do I avoid vendor lock-in?', a: 'Inspect export formats and contract terms before committing. Ask which rules, credentials, execution history and test data can move to another environment. Separate client-owned application code from third-party licences. In the Washington Law Group agreement, the client owns the system code; your own contract must state what handover includes.' },
  { q: 'Does owning the code keep all data inside our own systems?', a: 'Data location follows the deployed architecture and the services it calls. Code ownership alone does not establish that location. Trace each source, model request, log and backup in the proposal. Ask which account holds each item and what access and retention settings apply to the agreed implementation.' },
  { q: 'Can I switch agent builders later?', a: 'Switching depends on the configuration format, connector dependencies and export rights. Ask for a sample export during evaluation and have an engineer inspect what it contains. If only conversation data exports, rules may need to be rebuilt. Include that work in your comparison rather than assume every builder can import another’s configuration.' },
  { q: 'How do we test a custom agent before launch?', a: 'Use representative successful inputs plus missing sources, conflicting fields, duplicate events and unavailable tools. Write down the expected action for each. FactoryJet’s published research workflow shows why source-name checks and duplicate handling matter. A new support or ERP agent needs equivalent tests tailored to the records it may change.' },
  { q: 'When should I hire an AI agent development company?', a: 'Consider a developer when the workflow needs custom integration, source validation or operating support your team cannot own. Ask for a relevant deployed case and a scoped test plan. Our ten-company comparison links the providers’ published offers and includes FactoryJet with a disclosure. The selection should follow the workflow requirements.' },
];

export const post: BlogPost = {
  id: '450', slug: 'ai-agent-build-vs-buy-2026',
  title: 'AI Agent Builders and Build vs Buy for Business (2026)',
  excerpt: 'Compare four configurable agent builders and a coding framework, then use source checks, duplicate handling and handover to decide what to buy or build.',
  category: 'Emerging Tech', author: 'Bhavesh Barot', date: 'Sep 19, 2026', dateModified: 'Oct 04, 2026', readTime: '11 min read',
  imageUrl: '/blog-images/build-ai-agents-small-business-diy-vs-agency-2026-hero.webp', imageAlt: 'A business team comparing a configurable agent builder with a custom development route',
  meta: { title: 'AI Agent Builders: Build vs Buy for Business', description: 'Compare n8n, Make, Lindy, Copilot Studio and LangGraph by buying route, with tests drawn from FactoryJet’s Washington Law Group implementation.' },
  keyTakeaways: ['Compare configurable builders and coding frameworks as different routes.', 'Test the required action and the failure path before buying a subscription.', 'Our research case supplies concrete source-check and duplicate-event examples.', 'Include review work, source subscriptions and maintenance in the operating scope.'], faqs,
  content: <>
    <p className="text-sm text-gray-600 mb-4">Updated <time dateTime="2026-10-04">October 4, 2026</time>.</p>
    <p className="text-lg leading-relaxed mb-6"><strong>Buy an AI agent builder when its connectors and controls cover your workflow. Scope custom work when a required action or source check needs additional engineering.</strong> This guide compares four configurable products and one coding framework. We use FactoryJet’s Washington Law Group research-agent implementation to show what belongs in the acceptance test and handover.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">Compare five routes for building an AI agent</h2>
    <p className="mb-4">The links describe each vendor’s current offer. We checked them on October 4, 2026. This is a comparison of buying routes, rather than a benchmark of tool performance. LangGraph is listed separately by type because using a framework requires an engineering team to own the application.</p>
    <div className="overflow-x-auto mb-8"><table className="w-full text-sm border-collapse"><caption className="text-left mb-3">Agent builders and a coding framework, with a test to run before selection</caption><thead><tr>{['Option', 'Type', 'Published offer', 'Test on your workflow'].map(t => <th scope="col" key={t} className="border p-3 text-left">{t}</th>)}</tr></thead><tbody>{BUILD_ROUTES.map(r => <tr key={r.name}><th scope="row" className="border p-3 text-left"><a href={r.url} className="text-[#B23E13] underline">{r.name}</a></th><td className="border p-3">{r.kind}</td><td className="border p-3">{r.offer}</td><td className="border p-3">{r.test}</td></tr>)}</tbody></table></div>
    <h2 className="text-2xl font-bold mt-10 mb-4">What our deployed research workflow required</h2>
    <p className="mb-4">Washington Law Group needed a system that reads published accident sources and sends relevant findings to the firm. The published implementation combines a model extraction step with fixed source and eligibility checks. Staff review records through a private console.</p>
    <p className="mb-4">An extracted name must appear in the source article before it can be saved. Duplicate handling stops several stories about one incident from becoming a fresh notification each time. These requirements give us concrete acceptance tests when we assess a builder or a custom proposal.</p>
    <p className="mb-4">The case documents dedicated hosting, encrypted daily backups and a news subscription owned by the firm. It also records client ownership of the system code under the agreement. Those details tell you what a delivery and operating scope should make explicit. The case does not publish a comparative saving against any builder in this table.</p>
    <p className="mb-6"><a href="/case-studies/washington-law-group-accident-detection-agent" className="text-[#B23E13] underline">Read the Washington Law Group implementation</a> before adapting the tests below to your own queue.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">Run the same test on a product and a custom proposal</h2>
    <p className="mb-4">For a research workflow, use an approved sample article and the expected saved record. For an RFQ, use the source request and the expected quote draft. These are acceptance examples you define before the build. Keep the same examples when comparing routes.</p>
    <ol className="list-decimal pl-6 space-y-3 mb-6">
      <li><strong>Unsupported fact.</strong> Give the workflow an extracted name or quantity absent from the source. Check the review path and confirm it cannot quietly save the invented field.</li>
      <li><strong>Duplicate event.</strong> Send the same input twice. Inspect whether it creates a second record and which stored identifier is used to recognise the first run.</li>
      <li><strong>Unavailable connector.</strong> Make the target service fail in a sandbox. Check the operator’s message, retry limit and route back into the queue.</li>
      <li><strong>Restricted action.</strong> Give a test identity read access only. Confirm that a proposed write is rejected and recorded. Repeat with the intended approved identity.</li>
      <li><strong>Interrupted run.</strong> Stop the run after a completed step. Check which result is saved and what will happen when it resumes.</li>
    </ol>
    <div className="bg-orange-50 border border-orange-200 rounded-lg p-6 my-8"><h2 className="text-xl font-bold mb-3">Need a view on one workflow?</h2><p className="mb-3">Send a redacted input, the required action and the tools involved. We will identify which builder capabilities to test and which gaps need custom work.</p><a href="/contact" className="text-[#B23E13] underline font-semibold">Discuss the build-versus-buy decision</a></div>
    <h2 className="text-2xl font-bold mt-10 mb-4">Compare the full operating scope</h2>
    <p className="mb-4">Use the same period and expected workload on both sides. The worksheet below lists costs without assuming a subscription replaces review time or that custom code avoids outside services. Get the current terms from each supplier.</p>
    <ul className="list-disc pl-6 space-y-3 mb-6">
      <li><strong>Implementation:</strong> configuration or engineering, approved access, test preparation and operator training.</li>
      <li><strong>Connected services:</strong> the builder subscription, data-source licences, model usage and infrastructure required by the chosen design.</li>
      <li><strong>Review work:</strong> count expected escalations and estimate review time using sample runs. Record the estimate separately from observed results.</li>
      <li><strong>Maintenance:</strong> credential rotation, connector changes, source changes, regression checks and incident response.</li>
    </ul>
    <p className="mb-6">FactoryJet quotes custom development after the scope is agreed. The <a href="/blog/what-is-an-ai-agent-cost-2026" className="text-[#B23E13] underline">AI agent cost guide</a> covers budgeting questions. Ask for assumptions on volume and review work alongside any estimate.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">Inspect what you receive at handover</h2>
    <p className="mb-4">For a configurable builder, ask for the workflow export and test it in the agreed account. For custom code, ask for the repository, environment instructions and acceptance set. In either route, check that the operator can trace a failed run without depending on a developer’s personal account.</p>
    <p className="mb-4">The Washington Law Group case states that the client owns the system code. That statement describes the agreement for that implementation. A new contract needs its own terms for custom code, third-party licences, prompts and connector credentials. Draw the data path separately, because ownership alone does not determine where a model request or log is stored.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">Choose who will operate the result</h2>
    <p className="mb-4">If your team can maintain a builder configuration, start by testing the supported route. If you need engineers for source validation or a restricted ERP action, define that work before selecting the tool. Read our <a href="/blog/best-ai-agent-development-companies-2026" className="text-[#B23E13] underline">ten-company comparison</a> and <a href="/blog/how-to-hire-an-ai-agent-developer-2026" className="text-[#B23E13] underline">developer hiring guide</a> when assessing a delivery partner.</p>
    <p className="mb-6">The <a href="/services/ai-agent-development" className="text-[#B23E13] underline">development service</a> describes the custom route. For ongoing operation, use the <a href="/services/ai-agent-monitoring" className="text-[#B23E13] underline">monitoring and support scope</a> to agree who handles failed runs and changes after launch.</p>
  </>,
};
