import React from 'react';
import type { BlogPost } from '../data.types';

/*
 * Local SEO cost, US. Written 2026-09-17.
 *
 * Scope is LOCAL SEO ONLY: Google Business Profile, reviews, citations, location
 * pages, local links and map pack tracking. General SEO pricing lives in
 * /blog/seo-cost-small-business-2026 (cited by ChatGPT), so this post links to it
 * instead of repeating it.
 *
 * Every external figure was fetched on 2026-09-17 and found on the source page
 * before it was written here. No FactoryJet prices, by rule.
 *
 * FAQs: People Also Ask from 11 US Google results pages pulled 2026-09-17
 * (DataForSEO organic/live/advanced, PAA click depth 2), plus PAA from the July
 * 2026 pull for "how to rank in google maps" and the local-search PAA questions
 * named in the brief. Job, salary and creator questions excluded.
 *
 * The FAQPage JSON-LD is generated by the blog route from the `faqs` array below.
 * Do not add a second FAQ list or a JSON-LD block to the content.
 */

const faqs = [
  {
    q: 'How much should I pay for local SEO?',
    a: 'Pay for the work your market needs, not a package name. WebFX\'s 2026 guide puts local SEO retainers at $500 to $3,000 a month, while 43% of businesses with 1 to 10 employees in its survey spend $100 to $500. One location in a quiet market sits low. More locations or tougher competition push you higher.',
  },
  {
    q: 'How much does local SEO cost in the USA?',
    a: 'WebFX\'s 2026 guide lists $500 to $3,000 a month for local SEO retainers, $500 to $5,000 for one-time projects and $75 to over $200 an hour for consulting. The Google Business Profile at the center of it is free. You pay for the setup, reviews, listings, pages and tracking around it.',
  },
  {
    q: 'How much do people charge for local SEO?',
    a: 'Most charge a monthly fee. In BrightLocal\'s Local Search Industry Survey, shared in its 2024 pricing guide, 63% of local SEO agencies bill a monthly fee based on deliverables, 36% charge per project and 28% bill by the hour. Ask which model a quote uses, because a monthly fee and a one-off project are not comparable.',
  },
  {
    q: 'How much should I expect to pay for SEO?',
    a: 'For a local business, expect two numbers. One is one-time setup: fixing your Google Business Profile, cleaning up listings, building location pages and fixing your site. The other is monthly: reviews, profile updates, local links and tracking. Ask providers to price them separately so you can see what repeats.',
  },
  {
    q: 'How much does SEO typically cost?',
    a: 'It depends on how far away your customers are. Local SEO is the narrower job: your profile, reviews, listings and a few location pages. A full SEO program adds content, technical work and link building to rank beyond your area, so it is a bigger scope. If your customers are nearby, price local SEO first.',
  },
  {
    q: 'Is local SEO free?',
    a: 'Parts of it are. Google Business Profile and Google Search Console are both free, and asking customers for reviews costs only time. What costs money is the skill and software around them: cleaning up listings, writing location pages, earning local links and tracking where you rank.',
  },
  {
    q: 'How much does it cost to get listed on Google Maps?',
    a: 'Nothing. Your Google Maps listing comes from a Google Business Profile, which Google offers free. You claim it, verify that you run the business and fill it in. Google also sells Local Services Ads, which it bills per lead, but ads are separate from your free listing and do not change its ranking.',
  },
  {
    q: 'Is it worth having a Google Business Profile?',
    a: 'Yes, if you serve customers in person or in a local area. It is free, it is what shows in Google Maps and the map pack, and it is where people read your Google reviews. BrightLocal\'s 2026 survey found 97% of consumers read reviews for local businesses. Without a profile, you cannot appear in map results.',
  },
  {
    q: 'How much does BrightLocal cost?',
    a: 'BrightLocal\'s pricing page lists a managed local SEO service at $1,299 a month and its Citation Builder at $3.20 per listing site, or as low as $2 with bulk credits, with no recurring fee. Its software plans vary with the number of locations. We checked on 17 September 2026, so confirm current prices on its site.',
  },
  {
    q: 'What is the cheapest SEO?',
    a: 'The cheapest local SEO is the work you do yourself: completing your profile, asking every customer for a review, fixing your directory listings and giving each service its own page. Very cheap packages carry risk. If the low price comes from junk directory submissions or bought reviews, fixing the damage costs more.',
  },
  {
    q: 'Is paid SEO worth it?',
    a: 'It is worth it when the math works. Divide the monthly cost by the profit from one new customer. That is how many extra customers local SEO must bring in each month to pay for itself. If a client is worth thousands in profit, the bar is low. If one is worth $30, do the free work first.',
  },
  {
    q: 'Is local SEO worth it?',
    a: 'For businesses that rely on nearby customers, usually yes. The core platform is free, people searching for a nearby service are often ready to buy, and setup work keeps paying after it is done. It is not worth it if you cannot take more calls, only sell online, or already lead your map pack.',
  },
  {
    q: 'Can I do local SEO myself?',
    a: 'Yes, a lot of it. You can complete your Google Business Profile, choose accurate categories, add real photos, ask every customer for a review, reply to reviews and fix your main listings. Owners usually pay for the rest: cleaning up messy listings at scale, strong location pages, local links and rank tracking.',
  },
  {
    q: 'Can I do SEO myself for free?',
    a: 'The basics, yes. Google Business Profile and Google Search Console cost nothing, and review requests cost only time. Free does not cover software for tracking map rankings or building listings in bulk. For reference, Localo lists a single-business plan at $49 a month, or $39 a month billed annually.',
  },
  {
    q: 'Can you do local SEO without a website?',
    a: 'You can start without one, because a Google Business Profile can show in Maps on its own. But a website makes local SEO easier to win: it gives Google more to match against, holds your service pages, and is where customers check you out. BrightLocal found 54% of consumers visit a business website after reading positive reviews.',
  },
  {
    q: 'How to do local SEO for beginners?',
    a: 'Work in this order. Claim and verify your Google Business Profile. Pick the most accurate primary category. Fill in every field and add real photos. Make your name, address and phone number match everywhere online. Ask every customer for a Google review and reply to each one. Then give each main service its own web page.',
  },
  {
    q: 'How does Google Maps ranking work?',
    a: 'Google ranks local results mainly on three things. Relevance is how well your profile matches the search. Distance is how far you are from the searcher. Prominence is how well known you are, which Google says draws on your reviews and how many websites link to you. You can improve relevance and prominence, not distance.',
  },
  {
    q: 'Can I pay Google to rank higher?',
    a: 'Not in the free local results. Google says there is no way to request or pay for a better local ranking. You can buy ads, such as Google Ads or Local Services Ads, which show as sponsored results, and Google bills Local Services Ads per lead. Budget for ads and local SEO separately.',
  },
  {
    q: 'How many reviews do you need to rank on Google?',
    a: 'Google does not publish a number. It says more reviews and positive ratings can help your local ranking, so your real target is the businesses already in your map pack: check how many reviews the top three have and pass them steadily. Customers set a bar too. BrightLocal found 47% will not use a business with fewer than 20 reviews.',
  },
  {
    q: 'How much is a 5 star Google review worth?',
    a: 'Nobody can put a fair dollar value on one review, and you should never pay for one. The FTC\'s 2024 final rule bans buying fake reviews, and Google removes paid or incentivized reviews from Maps. The value is trust: BrightLocal found 85% of consumers are more likely to use a business after reading positive reviews.',
  },
  {
    q: 'Is it better to leave reviews on Google or Yelp?',
    a: 'For a local business, focus on Google. Google reviews show on your Business Profile, and Google says reviews can help your local ranking. Yelp is different: its support center tells businesses not to ask for reviews, and warns that its software may not recommend reviews that look prompted. Let Yelp reviews come on their own.',
  },
  {
    q: 'Why is my Google ranking so low?',
    a: 'The usual local causes are a wrong primary category, an incomplete profile, fewer reviews than the businesses above you, details that do not match across directories, or duplicate profiles. Distance matters too, so you rank lower for people far away. Google also does not allow profiles at virtual offices, so a rented mailbox address can sink you.',
  },
  {
    q: 'How long until SEO works?',
    a: 'Local SEO usually moves faster than national SEO, because you compete with fewer businesses. Profile and listing fixes can show within weeks once Google picks them up. A competitive map pack spot in a busy city often takes months, because reviews and local links build slowly. Anyone promising the top spot in 30 days is guessing.',
  },
  {
    q: 'Can ChatGPT do SEO?',
    a: 'It can help with parts of local SEO: drafting your business description, writing review replies and producing LocalBusiness schema, the code that describes your business to search engines. It cannot verify your profile, earn real reviews or links, or check your rankings across your area. Check its work, because it can get your details wrong.',
  },
  {
    q: 'Is SEO dead now with AI?',
    a: 'No. BrightLocal\'s 2026 survey found 45% of consumers now use ChatGPT or other AI tools for local recommendations, up from 6% a year earlier. Those tools lean on public information about your business, such as listings, reviews and your website. If your details are wrong across the web, AI answers can repeat the mistake.',
  },
  {
    q: 'What is the 80/20 rule in SEO?',
    a: 'It is the idea that a small share of the work drives most of the results. In local SEO, that share is usually your primary category, a complete Google Business Profile, a steady flow of genuine reviews and matching business details everywhere. Get those right before paying for big directory packages or thin location pages.',
  },
];

const LINK = 'text-[#B23E13] underline hover:text-[#9A3510]';
const TH = 'p-3 text-left border border-gray-700';
const TD = 'p-3 border border-gray-200';

export const post: BlogPost = {
  id: '449',
  slug: 'local-seo-cost-2026',
  title: 'How Much Does Local SEO Cost in the USA? 2026 Pricing, Itemized',
  excerpt:
    'Agency guides put local SEO retainers at $500 to $3,000 a month, yet 43% of the smallest US businesses in one survey spend $100 to $500. The gap is scope. Here is every piece of local SEO work, and whether you pay for it once or every month.',
  category: 'Web Design & Strategy',
  author: 'Bhavesh Barot',
  date: 'Sep 17, 2026',
  readTime: '12 min read',
  imageUrl: '/images/us/phoenix-seo/phoenix-local-owner.webp',
  imageAlt:
    'A local shop owner hands a customer a paper bag across the counter of a small independent store',
  meta: {
    title: 'Local SEO Cost 2026: Pricing, Itemized for Small Businesses',
    description:
      'What local SEO costs a US small business in 2026, itemized: Google Business Profile, reviews, citations, location pages and links. One-time vs monthly.',
  },
  keyTakeaways: [
    'There is no list price. WebFX\'s 2026 guide puts local SEO retainers at $500 to $3,000 a month and one-time projects at $500 to $5,000.',
    'Small businesses often spend less: 43% of businesses with 1 to 10 employees in the same survey spend $100 to $500 a month.',
    'The core is free. Google Business Profile costs nothing, and Google says there is no way to pay for a better local ranking.',
    'Most of the cost is one-time setup. Reviews, profile upkeep, local links and rank tracking are the monthly part.',
    'Each extra location needs its own profile, listings, reviews and a genuinely different page.',
    'Never buy reviews. The FTC\'s 2024 rule bans buying fake reviews, and Google removes paid reviews from Maps.',
  ],
  faqs,
  content: (
    <>
      {/* Article, BreadcrumbList and FAQPage schema are emitted once by the blog route (src/app/blog/[slug]/page.tsx) from the faqs array above. */}

      {/* Quick Answer Box */}
      <div className="bg-orange-50 border-l-4 border-[#F05A28] p-6 rounded-r-lg mb-6">
        <p className="text-sm font-semibold text-[#B23E13] uppercase tracking-wide mb-2">Quick answer</p>
        <p className="text-gray-800 font-medium">
          There is no fixed price. WebFX&apos;s 2026 pricing guide puts local SEO agency retainers at{' '}
          <strong>$500 to $3,000 a month</strong> and one-time projects at $500 to $5,000. Small businesses often
          spend less: in the survey behind that guide, 43% of businesses with 1 to 10 employees spend{' '}
          <strong>$100 to $500 a month</strong>. Your Google Business Profile is free. You pay for the work around it.
        </p>
      </div>

      <p className="text-sm text-gray-600">
        Checked on 17 September 2026. Every outside number links to its source. We sell local SEO too, so our own
        prices are left out.
      </p>

      <nav aria-label="Table of contents" className="bg-gray-50 p-6 rounded-lg my-8 border not-prose">
        <p className="text-lg font-bold text-gray-900 mb-3">In this guide</p>
        <ol className="list-decimal pl-5 space-y-1 text-sm">
          <li><a href="#what-it-costs" className={LINK}>The published prices</a></li>
          <li><a href="#itemized" className={LINK}>The work, itemized: one-time or monthly</a></li>
          <li><a href="#cost-drivers" className={LINK}>What pushes your price up or down</a></li>
          <li><a href="#multi-location" className={LINK}>One location vs several</a></li>
          <li><a href="#diy" className={LINK}>What you can do yourself for free</a></li>
          <li><a href="#worth-it" className={LINK}>Is local SEO worth it?</a></li>
          <li><a href="#red-flags" className={LINK}>Red flags in a quote</a></li>
          <li><a href="#get-a-quote" className={LINK}>How to get an accurate quote</a></li>
          <li><a href="#who-google-quotes" className={LINK}>Who Google quotes today</a></li>
          <li><a href="#sources" className={LINK}>Sources</a></li>
          <li><a href="#faqs" className={LINK}>FAQs</a></li>
        </ol>
      </nav>

      <p>
        Local SEO (search engine optimization for nearby customers) gets you found in the map pack: the three
        businesses with a map that Google shows for searches like &ldquo;plumber near me&rdquo;. Most of the work
        happens off your website, on your Google Business Profile (your free listing on Google Search and Maps), your
        reviews and your listings on other sites. So the price depends on your locations and your competition, not
        on the size of your website.
      </p>
      <p>
        This guide covers local SEO only. For full SEO programs with content and national rankings, see{' '}
        <a href="/blog/seo-cost-small-business-2026" className={LINK}>what SEO costs a small business</a>.
      </p>

      {/* Section 1 */}
      <h2 id="what-it-costs" className="text-2xl font-bold mt-10 mb-4">What local SEO costs in 2026: the published prices</h2>
      <p>There is no list price, so start with prices someone has published and you can check.</p>

      <div className="overflow-x-auto my-6">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="bg-gray-800 text-white">
              <th scope="col" className={TH}>What you pay for</th>
              <th scope="col" className={TH}>Published price</th>
              <th scope="col" className={TH}>Source</th>
            </tr>
          </thead>
          <tbody>
            <tr className="bg-white">
              <td className={TD}>Agency retainer (a fixed monthly fee)</td>
              <td className={`${TD} font-semibold`}>$500 to $3,000 a month</td>
              <td className={TD}><a href="https://www.webfx.com/local-seo/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>WebFX 2026 guide</a></td>
            </tr>
            <tr className="bg-gray-50">
              <td className={TD}>One-time project, like an audit or new location pages</td>
              <td className={`${TD} font-semibold`}>$500 to $5,000</td>
              <td className={TD}><a href="https://www.webfx.com/local-seo/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>WebFX 2026 guide</a></td>
            </tr>
            <tr className="bg-white">
              <td className={TD}>Hourly consulting</td>
              <td className={`${TD} font-semibold`}>$75 to over $200 an hour</td>
              <td className={TD}><a href="https://www.webfx.com/local-seo/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>WebFX 2026 guide</a></td>
            </tr>
            <tr className="bg-gray-50">
              <td className={TD}>What businesses with 1 to 10 employees spend</td>
              <td className={`${TD} font-semibold`}>$100 to $500 a month (43% of them)</td>
              <td className={TD}><a href="https://www.webfx.com/local-seo/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>WebFX survey of 250 US marketing and sales professionals</a></td>
            </tr>
            <tr className="bg-white">
              <td className={TD}>Managed local SEO from a software company</td>
              <td className={`${TD} font-semibold`}>$1,299 a month</td>
              <td className={TD}><a href="https://www.brightlocal.com/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>BrightLocal</a></td>
            </tr>
            <tr className="bg-gray-50">
              <td className={TD}>Local SEO software for one business</td>
              <td className={`${TD} font-semibold`}>$49 a month, or $39 a month billed annually</td>
              <td className={TD}><a href="https://localo.com/pricing" target="_blank" rel="noopener noreferrer" className={LINK}>Localo</a></td>
            </tr>
            <tr className="bg-white">
              <td className={TD}>One citation (a listing of your business on a directory)</td>
              <td className={`${TD} font-semibold`}>$3.20 per site, or $2 with bulk credits</td>
              <td className={TD}><a href="https://www.brightlocal.com/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>BrightLocal</a></td>
            </tr>
            <tr className="bg-gray-50">
              <td className={TD}>Google Business Profile</td>
              <td className={`${TD} font-semibold`}>Free</td>
              <td className={TD}><a href="https://business.google.com/us/business-profile/" target="_blank" rel="noopener noreferrer" className={LINK}>Google</a></td>
            </tr>
          </tbody>
        </table>
      </div>
      <p className="text-xs text-gray-500 mb-6">Checked 17 September 2026. Confirm on each site before you budget.</p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Why agency quotes and small business budgets differ</h3>
      <p>
        Rows one and four tell different stories. Retainers start at $500 a month, yet 43% of businesses with 1 to 10
        employees spend $100 to $500, and so do 45% of businesses with 11 to 50 employees. Those are two different
        purchases. In our experience, up to $500 mostly buys software, some listings and a few hours of help, with
        the owner doing the rest. From $500 up, someone does the work for you every month.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">How providers bill</h3>
      <p>
        BrightLocal&apos;s 2024 guide to local SEO pricing shares figures from its{' '}
        <a href="https://www.brightlocal.com/learn/what-should-my-agency-be-charging-for-local-seo/" target="_blank" rel="noopener noreferrer" className={LINK}>Local Search Industry Survey</a>:
        63% of local SEO agencies bill a monthly fee based on deliverables, 36% charge per project and 28% bill by
        the hour. Compare quotes on the same model, or you will weigh a year of work against a one-off job.
      </p>

      {/* Section 2 */}
      <h2 id="itemized" className="text-2xl font-bold mt-10 mb-4">Local SEO work, itemized: one-time or monthly</h2>
      <p>Here is local SEO split into its jobs, with what each involves and whether you pay once or every month.</p>

      <div className="overflow-x-auto my-6">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="bg-gray-800 text-white">
              <th scope="col" className={TH}>The work</th>
              <th scope="col" className={TH}>What it involves</th>
              <th scope="col" className={TH}>One-time or monthly</th>
              <th scope="col" className={TH}>What makes it cost more</th>
            </tr>
          </thead>
          <tbody>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Google Business Profile setup</td>
              <td className={TD}>Verify the profile, pick the right primary category, add services, hours and photos, remove duplicates</td>
              <td className={TD}>One-time</td>
              <td className={TD}>Duplicate or suspended profiles, a move, a name change</td>
            </tr>
            <tr className="bg-gray-50">
              <td className={`${TD} font-semibold`}>Profile upkeep</td>
              <td className={TD}>Posts, new photos, answering questions, holiday hours</td>
              <td className={TD}>Monthly</td>
              <td className={TD}>How often your offers or hours change</td>
            </tr>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Reviews</td>
              <td className={TD}>A simple way to ask every customer for a review, and a reply to each one</td>
              <td className={TD}>Setup once, then monthly</td>
              <td className={TD}>Customer volume, and how many review sites matter in your industry</td>
            </tr>
            <tr className="bg-gray-50">
              <td className={`${TD} font-semibold`}>Citations</td>
              <td className={TD}>Making your name, address and phone number match on directories and data aggregators (firms that feed many directories at once)</td>
              <td className={TD}>Mostly one-time</td>
              <td className={TD}>Old addresses, past names, tracking numbers, more locations</td>
            </tr>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Location and service pages</td>
              <td className={TD}>One useful page per location or main service</td>
              <td className={TD}>One-time per page</td>
              <td className={TD}>Number of locations and services</td>
            </tr>
            <tr className="bg-gray-50">
              <td className={`${TD} font-semibold`}>On-page and technical fixes</td>
              <td className={TD}>Page titles, contact details, LocalBusiness schema (code that describes your business to search engines), speed on phones</td>
              <td className={TD}>Mostly one-time</td>
              <td className={TD}>Your website platform, and the site&apos;s age and size</td>
            </tr>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Local links</td>
              <td className={TD}>Chamber of commerce, sponsorships, local news, partner pages that link to you</td>
              <td className={TD}>Monthly</td>
              <td className={TD}>How crowded your category is locally</td>
            </tr>
            <tr className="bg-gray-50">
              <td className={`${TD} font-semibold`}>Map pack rank tracking</td>
              <td className={TD}>Checking your position from many points across your area</td>
              <td className={TD}>Monthly</td>
              <td className={TD}>Keywords, locations and competitors tracked</td>
            </tr>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Call and lead tracking</td>
              <td className={TD}>Tracking numbers and analytics events for calls, direction requests and forms</td>
              <td className={TD}>Setup once, then small monthly fees</td>
              <td className={TD}>Number of locations</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h3 className="text-xl font-semibold mt-6 mb-3">Why each job exists</h3>
      <p>
        Google&apos;s{' '}
        <a href="https://support.google.com/business/answer/7091" target="_blank" rel="noopener noreferrer" className={LINK}>local ranking help page</a>{' '}
        names three factors: relevance (how well your profile matches the search), distance (how far you are from
        the searcher) and prominence (how well known you are, based partly on your reviews and how many websites link
        to you). Profile and page work buys relevance. Reviews, citations and local links buy prominence. Nobody can
        sell you distance.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Most of the cost is setup</h3>
      <p>
        Profile setup, citations, pages and site fixes are done once and keep working. If a quote bills setup as a
        permanent monthly line, ask what exactly gets redone each month.
      </p>

      <div className="bg-orange-50 border border-orange-200 p-5 rounded-lg my-8 not-prose">
        <p className="font-semibold text-orange-900 mb-2">Want this table filled in for your business?</p>
        <p className="text-orange-800 mb-3">
          We scope local SEO to your locations and the businesses already in your map pack, split one-time work from
          monthly work, and quote it before anything starts. Engagements run month-to-month.
        </p>
        <a
          href="/services/local-seo"
          className="inline-block bg-[#B23E13] text-white px-5 py-2 rounded font-semibold hover:bg-[#9A3510] transition-colors"
        >
          See our local SEO service
        </a>
      </div>

      {/* Section 3 */}
      <h2 id="cost-drivers" className="text-2xl font-bold mt-10 mb-4">Six things that push your price up or down</h2>
      <p>A good provider asks about all six before quoting.</p>
      <ol className="list-decimal pl-6 space-y-3 mb-6">
        <li>
          <strong>Locations.</strong> Each real location needs its own profile, listings, reviews and page. WebFX&apos;s
          guide names location count as a main cost factor.
        </li>
        <li>
          <strong>Competition.</strong> Catching rivals who have hundreds of reviews takes longer, so a common service
          in a large metro like <a href="/austin/seo" className={LINK}>Austin</a> usually costs more to win than in a
          smaller city like <a href="/fargo/seo" className={LINK}>Fargo</a>.
        </li>
        <li>
          <strong>Messy listings.</strong> Old addresses, past business names or tracking numbers mean cleanup first.
        </li>
        <li>
          <strong>Service area.</strong> Google ranks by distance from each searcher, so a wide area means more towns
          to cover.
        </li>
        <li>
          <strong>Your website.</strong> A slow site, or one with no page per service, needs fixing before it can grow.
        </li>
        <li>
          <strong>Who does the work.</strong> WebFX notes that freelancers cost less than agencies and often include
          fewer deliverables.
        </li>
      </ol>

      {/* Section 4 */}
      <h2 id="multi-location" className="text-2xl font-bold mt-10 mb-4">Single-location vs multi-location businesses</h2>
      <p>More locations do not multiply every cost. They multiply the work that lives off your website.</p>

      <h3 className="text-xl font-semibold mt-6 mb-3">One location</h3>
      <p>
        One profile, one set of listings, one review stream and a few service pages. Most of the spend lands early, on
        setup. After that, it is reviews, upkeep, some local links and tracking.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Several locations</h3>
      <div className="overflow-x-auto my-6">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="bg-gray-800 text-white">
              <th scope="col" className={TH}>What you pay for</th>
              <th scope="col" className={TH}>One location</th>
              <th scope="col" className={TH}>Several locations</th>
            </tr>
          </thead>
          <tbody>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Google Business Profiles</td>
              <td className={TD}>One</td>
              <td className={TD}>One per real location, with bulk verification once you have 10 or more</td>
            </tr>
            <tr className="bg-gray-50">
              <td className={`${TD} font-semibold`}>Citations</td>
              <td className={TD}>One set</td>
              <td className={TD}>One set per location, priced per site</td>
            </tr>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Reviews</td>
              <td className={TD}>One request flow</td>
              <td className={TD}>One request flow and set of replies per location</td>
            </tr>
            <tr className="bg-gray-50">
              <td className={`${TD} font-semibold`}>Location pages</td>
              <td className={TD}>One page</td>
              <td className={TD}>One genuinely different page each</td>
            </tr>
            <tr className="bg-white">
              <td className={`${TD} font-semibold`}>Rank tracking</td>
              <td className={TD}>One service area</td>
              <td className={TD}>One per location</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p>
        Shared costs, like one website, one page template and bulk listing credits, make each extra location cost
        less than the first.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Three rules that stop multi-location budgets leaking</h3>
      <ul className="list-disc pl-6 space-y-3 mb-6">
        <li>
          <strong>Only real locations get profiles.</strong> Google&apos;s{' '}
          <a href="https://support.google.com/business/answer/3038177" target="_blank" rel="noopener noreferrer" className={LINK}>Business Profile guidelines</a>{' '}
          say a virtual office, an address you rent but do not work from, is not eligible. A business that travels to
          customers keeps one profile for its central office, with a service area.
        </li>
        <li>
          <strong>Make every location page different.</strong> Google&apos;s{' '}
          <a href="https://developers.google.com/search/docs/essentials/spam-policies" target="_blank" rel="noopener noreferrer" className={LINK}>spam policies</a>{' '}
          list pages aimed at specific cities that funnel visitors to one page as an example of doorway abuse.
        </li>
        <li>
          <strong>Track each place you compete.</strong> A business serving Lakewood, Westlake and Beachwood from one
          Cleveland office competes in several map packs, because Google ranks by distance from each searcher. Our{' '}
          <a href="/cleveland/seo" className={LINK}>Cleveland local SEO page</a> explains how we handle suburbs like
          those.
        </li>
      </ul>

      {/* Section 5 */}
      <h2 id="diy" className="text-2xl font-bold mt-10 mb-4">What you can do yourself for free</h2>
      <p>If money is tight, do these seven jobs first. They cost nothing but time.</p>
      <ol className="list-decimal pl-6 space-y-3 mb-6">
        <li><strong>Claim and verify your Google Business Profile.</strong> It is free.</li>
        <li><strong>Choose the most accurate primary category,</strong> then add the services you really offer.</li>
        <li><strong>Fill in every field:</strong> hours, holiday hours, service area and real photos.</li>
        <li>
          <strong>Make your name, address and phone number match</strong> on your website, Google, Apple Maps, Bing,
          Yelp and Facebook. Local SEO people call this NAP.
        </li>
        <li>
          <strong>Ask every customer for a review, not only happy ones.</strong> Google&apos;s{' '}
          <a href="https://support.google.com/contributionpolicy/answer/7400114" target="_blank" rel="noopener noreferrer" className={LINK}>Maps content policy</a>{' '}
          does not allow selectively asking for positive reviews.
        </li>
        <li>
          <strong>Connect Google Search Console,</strong> a{' '}
          <a href="https://support.google.com/webmasters/answer/9128668" target="_blank" rel="noopener noreferrer" className={LINK}>free Google tool</a>{' '}
          that shows which searches your website appears in.
        </li>
        <li><strong>Give each main service its own page,</strong> with your area, real photos and answers to common questions.</li>
      </ol>

      <h3 className="text-xl font-semibold mt-6 mb-3">Where paid help earns its fee</h3>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>Cleaning up conflicting listings, including data aggregators such as Data Axle, Neustar Localeze and Foursquare</li>
        <li>Writing location pages that are genuinely different from each other</li>
        <li>Earning links from local organizations and local press</li>
        <li>Tracking map pack positions across your whole service area</li>
      </ul>

      {/* Section 6 */}
      <h2 id="worth-it" className="text-2xl font-bold mt-10 mb-4">Is local SEO worth it? Do this math first</h2>
      <p>It is worth it when the extra customers pay for the work. Check with three numbers you already know.</p>
      <ol className="list-decimal pl-6 space-y-3 mb-6">
        <li><strong>Profit from one new customer.</strong> Use gross profit, not the sale price.</li>
        <li><strong>Your close rate.</strong> The share of calls that become customers.</li>
        <li>
          <strong>Your monthly budget, divided by profit times close rate.</strong> That is how many extra calls a month
          you need to break even.
        </li>
      </ol>
      <p>
        <strong>A made-up example.</strong> A job earns $400 in profit and you book half your calls, so each call is
        worth $200. A $1,000 monthly budget needs five extra calls a month. If one client is worth $3,000 in profit,
        you need less than one. These are illustrations, not benchmarks, so use your own numbers.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">What buyers do</h3>
      <p>
        BrightLocal&apos;s{' '}
        <a href="https://www.brightlocal.com/research/local-consumer-review-survey/" target="_blank" rel="noopener noreferrer" className={LINK}>Local Consumer Review Survey 2026</a>,
        a panel of 1,002 US adults, found:
      </p>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>97% of consumers read reviews for local businesses.</li>
        <li>47% will not use a business with fewer than 20 reviews.</li>
        <li>85% are more likely to use a business after reading positive reviews.</li>
        <li>45% use ChatGPT or other AI tools for local recommendations, up from 6% a year earlier.</li>
      </ul>
      <p>
        AI assistants draw on public listings, reviews and websites, so local SEO work now reaches beyond Google. See
        what they say about you with our free <a href="/ai-visibility-checker" className={LINK}>AI visibility checker</a>.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">When it is not worth it</h3>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>You cannot take on more calls or bookings.</li>
        <li>You only sell online and do not serve a local area.</li>
        <li>You already lead your map pack and only need upkeep.</li>
      </ul>
      <p>
        For the same math on a full program, see{' '}
        <a href="/blog/seo-cost-small-business-2026" className={LINK}>what SEO costs a small business in 2026</a>.
      </p>

      {/* Section 7 */}
      <h2 id="red-flags" className="text-2xl font-bold mt-10 mb-4">Eight red flags in a local SEO quote</h2>
      <ol className="list-decimal pl-6 space-y-3 mb-6">
        <li>
          <strong>A guaranteed top spot.</strong> Google&apos;s help page is blunt: &ldquo;There&apos;s no way to request
          or pay for a better local ranking on Google.&rdquo;
        </li>
        <li>
          <strong>Bought or rewarded reviews.</strong> The{' '}
          <a href="https://www.ftc.gov/news-events/news/press-releases/2024/08/federal-trade-commission-announces-final-rule-banning-fake-reviews-testimonials" target="_blank" rel="noopener noreferrer" className={LINK}>FTC&apos;s August 2024 final rule</a>{' '}
          bans buying fake reviews and lets the agency seek civil penalties, and Google removes paid or incentivized
          reviews from Maps.
        </li>
        <li><strong>Review gating.</strong> Sending review requests only to happy customers breaks Google&apos;s rules.</li>
        <li>
          <strong>Pushing for Yelp reviews.</strong> Yelp&apos;s{' '}
          <a href="https://www.yelp-support.com/article/Don-t-Ask-for-Reviews?l=en_US" target="_blank" rel="noopener noreferrer" className={LINK}>support center</a>{' '}
          tells businesses not to ask for reviews.
        </li>
        <li>
          <strong>Wanting to own your profile.</strong> You should own your Google Business Profile and add them as a
          manager.
        </li>
        <li><strong>Hundreds of directory submissions.</strong> Accuracy beats volume, and junk listings are hard to remove.</li>
        <li><strong>Cloned city pages.</strong> Swapping only the town name risks being treated as doorway abuse.</li>
        <li>
          <strong>Reports without calls.</strong> Rankings and traffic without calls, direction requests and bookings
          prove very little.
        </li>
      </ol>

      {/* Section 8 */}
      <h2 id="get-a-quote" className="text-2xl font-bold mt-10 mb-4">How to get an accurate local SEO quote</h2>
      <p>Send this before the first call. It turns a package into a price for your situation.</p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Tell them</h3>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>How many locations you have, and whether customers come to you</li>
        <li>Your main services and the towns you want customers from</li>
        <li>Links to your Google Business Profile and website</li>
        <li>Any past moves, name changes or duplicate profiles</li>
        <li>Your review count, and the counts of the top three businesses in your map pack</li>
        <li>What counts as a result: calls, bookings or form fills</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-3">Ask them for</h3>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>Setup work and monthly work priced separately</li>
        <li>Monthly deliverables in plain words</li>
        <li>Who owns the profile, listings and pages if you leave</li>
        <li>What happens to listings in their software if you cancel</li>
        <li>Contract length, and what the monthly report measures</li>
      </ul>

      <div className="bg-white border-2 border-[#F05A28] rounded-2xl p-6 my-8 not-prose">
        <p className="text-xl font-bold text-gray-900 mb-2">Get local SEO priced for your business</p>
        <p className="text-gray-700 mb-4">
          Bring that list to a short call. We will map the work, split one-time from monthly, and quote it before
          anything starts. Still comparing? Our shortlist compares eight US local SEO companies, including us.
        </p>
        <div className="flex flex-wrap gap-3">
          <a
            href="/services/local-seo"
            className="inline-flex items-center justify-center bg-[#B23E13] hover:bg-[#9A3510] text-white font-semibold text-sm px-6 py-3 rounded-lg transition-colors"
          >
            See our local SEO service
          </a>
          <a
            href="/blog/best-local-seo-companies-usa"
            className="inline-flex items-center justify-center bg-white hover:bg-gray-50 text-gray-900 border border-gray-300 font-semibold text-sm px-6 py-3 rounded-lg transition-colors"
          >
            Compare local SEO companies
          </a>
        </div>
      </div>

      {/* Section 9 */}
      <h2 id="who-google-quotes" className="text-2xl font-bold mt-10 mb-4">Who Google quotes on local SEO cost today</h2>
      <p>On 17 September 2026 we pulled 11 US Google results pages for local SEO cost searches. What we found:</p>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>An AI Overview, the AI-written summary Google shows above results, appeared on 10 of the 11.</li>
        <li>
          For &ldquo;local seo cost&rdquo; and &ldquo;local seo pricing&rdquo;, it cited the same seven pages: Localo,
          Blueprint Digital, WebFX, Fiverr, eSEOspace, Softtrix and SEO Locale. All seven sell local SEO: five
          agencies, a freelance marketplace and a software company.
        </li>
        <li>
          The top regular result for both &ldquo;local seo cost&rdquo; and &ldquo;how much does local seo cost&rdquo;
          was a Reddit thread asking whether $300 a month for local SEO is a good price.
        </li>
        <li>&ldquo;How much should I pay for local SEO?&rdquo; was the most common People Also Ask question, on 7 of the 11 pages.</li>
        <li>factoryjet.com appeared on none of them, in regular results or in the AI Overviews we could read.</li>
      </ul>
      <p>
        Every source quoting a local SEO price also sells it, us included. That is why each figure here links to its
        source.
      </p>

      {/* Section 10 */}
      <h2 id="sources" className="text-2xl font-bold mt-10 mb-4">Sources</h2>
      <ul className="list-disc pl-6 space-y-2 mb-6 text-sm">
        <li><a href="https://www.webfx.com/local-seo/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>WebFX: How Much Does Local SEO Cost in 2026?</a></li>
        <li><a href="https://support.google.com/business/answer/7091" target="_blank" rel="noopener noreferrer" className={LINK}>Google Business Profile Help: Tips to improve your local ranking on Google</a></li>
        <li><a href="https://business.google.com/us/business-profile/" target="_blank" rel="noopener noreferrer" className={LINK}>Google Business Profile</a></li>
        <li><a href="https://support.google.com/business/answer/3038177" target="_blank" rel="noopener noreferrer" className={LINK}>Google Business Profile Help: Guidelines for representing your business on Google</a></li>
        <li><a href="https://support.google.com/business/answer/4490296" target="_blank" rel="noopener noreferrer" className={LINK}>Google Business Profile Help: Verify Business Profiles in bulk</a></li>
        <li><a href="https://developers.google.com/search/docs/essentials/spam-policies" target="_blank" rel="noopener noreferrer" className={LINK}>Google Search Central: Spam policies for Google web search</a></li>
        <li><a href="https://support.google.com/contributionpolicy/answer/7400114" target="_blank" rel="noopener noreferrer" className={LINK}>Google Maps user generated content policy: Prohibited and restricted content</a></li>
        <li><a href="https://support.google.com/webmasters/answer/9128668" target="_blank" rel="noopener noreferrer" className={LINK}>Search Console Help: About Search Console</a></li>
        <li><a href="https://support.google.com/localservices/answer/6224841" target="_blank" rel="noopener noreferrer" className={LINK}>Local Services Help: Getting started with Local Services Ads</a></li>
        <li><a href="https://www.brightlocal.com/research/local-consumer-review-survey/" target="_blank" rel="noopener noreferrer" className={LINK}>BrightLocal: Local Consumer Review Survey 2026</a></li>
        <li><a href="https://www.brightlocal.com/pricing/" target="_blank" rel="noopener noreferrer" className={LINK}>BrightLocal: Pricing</a></li>
        <li><a href="https://www.brightlocal.com/learn/what-should-my-agency-be-charging-for-local-seo/" target="_blank" rel="noopener noreferrer" className={LINK}>BrightLocal: What Should My Agency Be Charging for Local SEO?</a></li>
        <li><a href="https://localo.com/pricing" target="_blank" rel="noopener noreferrer" className={LINK}>Localo: Pricing</a></li>
        <li><a href="https://www.ftc.gov/news-events/news/press-releases/2024/08/federal-trade-commission-announces-final-rule-banning-fake-reviews-testimonials" target="_blank" rel="noopener noreferrer" className={LINK}>FTC: Final rule banning fake reviews and testimonials (August 14, 2024)</a></li>
        <li><a href="https://www.yelp-support.com/article/Don-t-Ask-for-Reviews?l=en_US" target="_blank" rel="noopener noreferrer" className={LINK}>Yelp Support Center: Don&apos;t Ask for Reviews</a></li>
      </ul>
      <p className="text-sm text-gray-600">
        All pages opened on 17 September 2026. If a figure no longer matches its source, tell us and we will fix it.
      </p>
    </>
  ),
};
