import React from 'react';
import type { BlogPost } from '../data.types';

const faqs = [
  { q: 'What is agentic AI?', a: 'Agentic AI describes systems in which an AI model can choose steps and use tools to work toward a goal, within limits set by the application. For a business, the useful questions are which source it can read, which action it can take and when it must stop for review. A fixed workflow can also contain AI steps.' },
  { q: 'What does agentic mean in AI?', a: 'It refers to the system having some control over the steps it takes toward a goal. The degree of control varies. Anthropic distinguishes predefined workflows from agents that choose their own path. Ask a developer to mark those boundaries on the proposed workflow rather than infer autonomy from the product name.' },
  { q: 'What is an example of agentic AI in business?', a: 'Consider a proposed support system that checks an order, retrieves the current policy and chooses a permitted next action. FactoryJet’s published Washington Law Group implementation is a more bounded example: a model extracts facts, then fixed rules check relevance, source names and duplicates. That case describes a hybrid workflow with defined actions.' },
  { q: 'How does agentic AI work?', a: 'The application gives a model a task, approved context and a limited set of tools. It records results between steps and decides when another step or a review is needed. Our Washington Law Group system uses source validation and duplicate records to constrain its research workflow. A developer must explain where the model can choose and where code fixes the path.' },
  { q: 'Is agentic AI the same as generative AI?', a: 'Generative AI produces outputs such as text or extracted fields. An agentic application can use that output to choose and perform another step through a tool. In the Washington Law Group workflow, extraction is the model step and source checking is a separate code step. Treat the whole application as the unit you evaluate.' },
  { q: 'Is agentic AI the same as an AI agent?', a: 'An AI agent is an individual implementation. Agentic AI is a description applied to systems with some ability to choose steps and act toward a goal. Suppliers use the terms differently. Ask for the actual task, tools and review rules before comparing offers that use either label.' },
  { q: 'Is a chatbot an AI agent?', a: 'A chat interface alone does not tell you how the application works. Check whether it can use approved tools, choose a next step and carry state between steps. For a Shopify support tool, distinguish a drafted answer from an order lookup or an authorised update. Each has different access and testing requirements.' },
  { q: 'Is ChatGPT an agent or a language model?', a: 'ChatGPT is an application that uses language models and can expose tools and agent features. Available capabilities depend on the product and configuration. For your business, check the actual connector permissions and permitted actions. A chat subscription by itself does not establish that the application can operate your CRM or ERP.' },
  { q: 'Does an AI agent need several other agents?', a: 'Start with one bounded workflow. Add separate agents when distinct tasks or parallel research justify them, then test each handoff. Our published research case can be explained through its sources, extraction step and fixed checks without claiming a multi-agent architecture. A supplier should be able to explain the simpler design it considered.' },
  { q: 'What are the risks of agentic AI?', a: 'Evaluate the actions your workflow permits. An incorrect extracted name, a duplicate notification or a write to the wrong record needs a different control. In the Washington Law Group system, source-name checks and duplicate handling address two specific risks. For a new workflow, test its own failure cases and keep an operator able to pause it.' },
  { q: 'How do you stop an agent inventing facts?', a: 'Validate important fields against the authorised source and define what happens when evidence is missing. In the Washington Law Group implementation, an extracted name must appear in the source article before it can be saved. That control checks a specific field. Other claims and actions need their own checks and review rules.' },
  { q: 'Can agentic AI work with NetSuite, Odoo or SAP?', a: 'An application can use an approved integration route when the ERP exposes the required records and actions. Confirm the version, licence, permissions and sandbox access during discovery. A listing of ERP names does not establish that a connector handles your business rules. Ask for tests on a rejected write and a repeated request.' },
  { q: 'Can a small business use agentic AI?', a: 'Choose a recurring task with accessible sources and a person who can accept the output. A supplier can evaluate a redacted sample before proposing a custom build. For a standard app workflow, a configurable product may cover the task. Compare both routes against the same missing-data and duplicate-event examples.' },
  { q: 'Can I develop an AI agent?', a: 'You can prototype with a builder or a coding framework, then connect approved tools and test representative inputs. A deployed system also needs credential handling, failure recovery and an operating owner. Our build-versus-buy guide compares those responsibilities. The prototype becomes useful evidence once it is tested on the exceptions in your actual queue.' },
  { q: 'Do I need an agent or a fixed automation?', a: 'Use fixed rules for decisions you can write down and test directly. Use a model when interpreting variable text is part of the job. In the Washington Law Group implementation, a model extracts article facts while fixed rules check eligibility and duplicates. Keeping those responsibilities separate makes the workflow easier to inspect.' },
  { q: 'How much does agentic AI cost?', a: 'Price the complete workflow: implementation, model usage, hosting, subscriptions, review work and support. The Washington Law Group case identifies dedicated hosting and a client-owned news subscription, so model calls are only one part of its operating scope. FactoryJet quotes a new build after the sources, actions and acceptance tests are agreed.' },
  { q: 'Who owns an agentic AI system?', a: 'Ownership depends on the contract and the software used. Ask which code, prompts, connectors and tests you receive and which parts depend on third-party licences. The Washington Law Group agreement assigns the system code to the client. The same case also identifies a news subscription owned by the firm.' },
  { q: 'How do we measure an agentic AI pilot?', a: 'Choose a task-level acceptance set before the build. Include successful inputs, missing evidence, repeated events and unavailable tools. Record the expected result for each. The Washington Law Group case publishes delivery controls rather than a measured revenue lift, so use it as an implementation example and establish your own pilot baseline.' },
  { q: 'Which company can build an agentic AI system?', a: 'Compare a provider’s published offering with a relevant deployed implementation and the tests it proposes for your workflow. FactoryJet has a named research-agent case. Our ten-company comparison links other developers’ own service pages and states its selection method. Ask candidates to identify the access dependencies and handover work in their proposals.' },
  { q: 'What should we do first?', a: 'Collect redacted examples from one queue and identify the source the operator uses to decide. Write down the permitted action and a reason to stop. For a research task, add an unsupported name and a duplicate story to the examples. That gives a developer something concrete to scope and test.' },
];

export const post: BlogPost = {
  id: '240', slug: 'what-is-agentic-ai',
  title: 'What Is Agentic AI? Definition and a Deployed Business Example',
  excerpt: 'Understand agentic AI through tool use, fixed rules and review points. See how FactoryJet’s Washington Law Group research workflow handles sources and duplicates.',
  category: 'Emerging Tech', author: 'Bhavesh Barot', date: 'Jul 11, 2026', dateModified: 'Oct 04, 2026', readTime: '11 min read',
  imageUrl: '/blog-images/what-is-agentic-ai.webp', imageAlt: 'A team reviewing the steps in an agentic business workflow',
  meta: { title: 'What Is Agentic AI? Definition and Business Example', description: 'Agentic AI explained through tools, fixed rules and review points, with FactoryJet’s deployed Washington Law Group case and questions for business buyers.' },
  keyTakeaways: ['An agentic system gives the model some choice over steps and tools.', 'Fixed workflows can include AI extraction without handing the model every decision.', 'Our Washington Law Group case makes source checks and duplicate handling visible.', 'Evaluate the permitted action and the failure path before buying a system.'], faqs,
  content: <>
    <p className="text-sm text-gray-600 mb-4">Updated <time dateTime="2026-10-04">October 4, 2026</time>.</p>
    <p className="text-lg leading-relaxed mb-6"><strong>Agentic AI describes systems in which an AI model can choose steps and use tools to work toward a goal.</strong> The application sets the limits, records the results and decides when human review is required. For a business owner, the useful detail is the action the system may take inside your software.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">The distinction we use when designing a workflow</h2>
    <p className="mb-4"><a href="https://www.anthropic.com/engineering/building-effective-agents" className="text-[#B23E13] underline">Anthropic’s engineering guide</a> distinguishes predefined workflows from agents that choose their path. That distinction helps us scope a build. If the decision is a fixed eligibility rule, write it as code. If the input is a variable news article or email, a model can help interpret it.</p>
    <p className="mb-6">Ask the developer to label every step in the proposal. Which step follows a fixed rule? Which step calls a model? Which step changes a record? The same system can include all of those. A diagram labelled “autonomous” leaves the most useful buying questions unanswered.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">A deployed example from Washington Law Group</h2>
    <p className="mb-4">FactoryJet built a news-monitoring and research system for Washington Law Group. It reads published sources, extracts accident facts and applies rules before sending relevant findings to the firm. The published case identifies a licensed news API, a nationwide news index, local feeds and the California Highway Patrol feed among its sources.</p>
    <p className="mb-4">This is a hybrid AI workflow with a fixed operating path. We use it here to show the engineering around model output. It does not establish that a model should choose every next action or that a business should buy a multi-agent system.</p>
    <ol className="list-decimal pl-6 space-y-3 mb-6">
      <li><strong>Read the authorised source.</strong> The system starts with a published article or incident feed. It does not need a model to invent a new source.</li>
      <li><strong>Extract the facts.</strong> A model reads the article and proposes fields. The application treats those fields as outputs to check.</li>
      <li><strong>Validate a name.</strong> A returned name must appear in the article text before it can be saved. The published case reports that this check has caught invented names in actual runs.</li>
      <li><strong>Apply eligibility rules.</strong> Fixed rules determine whether the incident meets the firm’s configured criteria. The model’s narrative does not replace those checks.</li>
      <li><strong>Handle a repeated story.</strong> Duplicate detection controls whether a notification is new or an update. Staff can inspect records through a private console.</li>
    </ol>
    <p className="mb-6"><a href="/case-studies/washington-law-group-accident-detection-agent" className="text-[#B23E13] underline">Read the deployed case</a>. It documents source handling, access controls and code ownership. It does not publish a measured revenue increase or a conversion benchmark.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">Generative AI and agentic AI in one business process</h2>
    <div className="overflow-x-auto mb-6"><table className="w-full text-sm border-collapse"><caption className="text-left mb-3">Separate the model output from the application action</caption><thead><tr>{['Step', 'Responsibility', 'Question to ask'].map(t => <th key={t} scope="col" className="border p-3 text-left">{t}</th>)}</tr></thead><tbody>
      <tr><th scope="row" className="border p-3 text-left">Article extraction</th><td className="border p-3">A model proposes facts from source text.</td><td className="border p-3">Can each required fact be traced to the source?</td></tr>
      <tr><th scope="row" className="border p-3 text-left">Source-name check</th><td className="border p-3">Code checks the returned name against the article.</td><td className="border p-3">What happens when the name is absent?</td></tr>
      <tr><th scope="row" className="border p-3 text-left">Notification</th><td className="border p-3">The application applies eligibility and duplicate rules.</td><td className="border p-3">Can the same story create a second alert?</td></tr>
      <tr><th scope="row" className="border p-3 text-left">Operator review</th><td className="border p-3">Authorised staff inspect the saved record.</td><td className="border p-3">Can the reviewer see the source and checks?</td></tr>
    </tbody></table></div>
    <p className="mb-6">For the terminology comparison, see <a href="/blog/agentic-ai-vs-generative-ai" className="text-[#B23E13] underline">agentic AI versus generative AI</a>. For the difference between an individual implementation and the broader term, read <a href="/blog/agentic-ai-vs-ai-agents" className="text-[#B23E13] underline">agentic AI versus AI agents</a>.</p>
    <h2 className="text-2xl font-bold mt-10 mb-4">Translate those checks to your own systems</h2>
    <p className="mb-4">For an RFQ, replace the article with the customer’s request and the source-name check with a check on extracted line items. For a Shopify support queue, use the order record and the current return policy as the sources. These are proposed examples, each requiring its own implementation and tests.</p>
    <p className="mb-4">A quote draft can wait for approval. A refund changes a financial record. Agree the permitted action before choosing a model or builder. That gives the team a concrete way to assess API access, review work and incident handling.</p>
    <ul className="list-disc pl-6 space-y-3 mb-6">
      <li><strong>Missing source:</strong> a request names an order that cannot be found. Define what the reviewer receives and prevent a guessed result.</li>
      <li><strong>Conflicting evidence:</strong> two documents disagree about a quantity. Preserve both values for review rather than quietly choosing one.</li>
      <li><strong>Repeated event:</strong> the same email arrives twice. Check the stored identifier before creating another draft.</li>
      <li><strong>Unavailable tool:</strong> the ERP cannot answer. Record the failure and apply the agreed retry or review route.</li>
    </ul>
    <div className="bg-orange-50 border border-orange-200 rounded-lg p-6 my-8"><h2 className="text-xl font-bold mb-3">Bring us one recurring task</h2><p className="mb-3">Send a redacted input and name the system the operator checks today. We can identify which steps need a model, which need fixed rules and which need approval.</p><a href="/contact" className="text-[#B23E13] underline font-semibold">Scope an AI workflow</a></div>
    <h2 className="text-2xl font-bold mt-10 mb-4">Choose the buying route after defining the action</h2>
    <p className="mb-4">A configurable agent builder can cover a task when its connector and permissions match the brief. A coding framework gives engineers more control and leaves them responsible for deployment and operation. Our <a href="/blog/ai-agent-build-vs-buy-2026" className="text-[#B23E13] underline">builder and build-versus-buy comparison</a> separates those routes.</p>
    <p className="mb-4">For a development engagement, compare the source checks and handover against a deployed case. Our <a href="/blog/best-ai-agent-development-companies-2026" className="text-[#B23E13] underline">ten-company comparison</a> links published offers and gives each provider a question to answer. FactoryJet publishes that comparison and is included in it.</p>
    <p className="mb-6">The <a href="/services/ai-agent-development" className="text-[#B23E13] underline">AI agent development service</a> describes how we scope custom work. Ask for a proposal that names the sources, actions and acceptance set. In our Washington Law Group agreement, the client owns the system code; check ownership and third-party licences for your own build.</p>
  </>,
};
