#!/usr/bin/env python3
"""
FactoryJet — AI Image Processing Pipeline
==========================================
Processes PNG images generated by Google Gemini (Imagen):
  1. Removes the Gemini watermark logo from the bottom-right corner
  2. Resizes to 1200×800px (3:2 ratio)
  3. Converts to WebP at quality 85
  4. Routes each file to the correct /public/images/ folder based on filename

Usage:
  python process_ai_images.py
  python process_ai_images.py --source ~/Desktop
  python process_ai_images.py --source ~/Downloads --dry-run
  python process_ai_images.py --watermark-height 80   (if logo is taller than default)

Requirements:
  pip install Pillow
"""

import argparse
import os
import shutil
import sys
from pathlib import Path

try:
    from PIL import Image, ImageFilter
except ImportError:
    print("❌  Pillow not installed. Run:  pip install Pillow")
    sys.exit(1)

# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

WEBSITE_ROOT = Path(__file__).resolve().parents[2]  # FactoryJet/website/
PUBLIC_DIR   = WEBSITE_ROOT / "public"

TARGET_W = 1200
TARGET_H = 800
WEBP_QUALITY = 85

# Gemini (Imagen 3) watermark is in the bottom-right corner.
# It's a gradient badge approximately 58px tall × 210px wide.
# We crop the entire bottom strip by this height, then scale back to 1200×800.
GEMINI_WATERMARK_HEIGHT = 70   # px to crop from bottom  (use --watermark-height to override)
GEMINI_WATERMARK_WIDTH  = 220  # px from right edge where the logo lives (for reference only)

# ---------------------------------------------------------------------------
# ROUTING TABLE
# Maps filename stem → destination folder (relative to PUBLIC_DIR)
# ---------------------------------------------------------------------------

US_CITIES = {
    "hero-austin":    "images/us/austin",
    "hero-miami":     "images/us/miami",
    "hero-denver":    "images/us/denver",
    "hero-nashville": "images/us/nashville",
    "hero-portland":  "images/us/portland",
    "hero-charlotte": "images/us/charlotte",
    "hero-raleigh":   "images/us/raleigh",
    "hero-tampa":     "images/us/tampa",
}

# Everything else goes to /images/us/services/
US_SERVICES_FOLDER = "images/us/services"

KNOWN_SERVICE_FILES = {
    "hero-ai-chatbot",
    "hero-ai-workflow",
    "hero-ai-integration",
    "hero-ai-agent-us",
    "hero-wordpress",
    "hero-webflow",
    "hero-shopify",
    "hero-enterprise-ecommerce",
    "service-web-design-process",
    "service-redesign",
    "service-team",
    "service-mobile",
}

# ---------------------------------------------------------------------------
# CORE PROCESSING
# ---------------------------------------------------------------------------

def remove_gemini_watermark(img: Image.Image, wm_height: int) -> Image.Image:
    """
    Removes the Gemini watermark by cropping the bottom wm_height pixels
    from the full image width, then scaling back to TARGET_W × TARGET_H.

    Strategy: crop-and-rescale is visually cleaner than pixel-patch inpainting
    for production images. The crop is only ~8.75% of a 800px-tall image —
    imperceptible after Lanczos rescale.
    """
    w, h = img.size
    cropped = img.crop((0, 0, w, h - wm_height))
    restored = cropped.resize((TARGET_W, TARGET_H), Image.Resampling.LANCZOS)
    return restored


def process_image(src_path: Path, dest_path: Path, wm_height: int, dry_run: bool) -> bool:
    """
    Full pipeline for a single image:
      open PNG → remove watermark → resize → save as WebP
    Returns True on success.
    """
    try:
        img = Image.open(src_path).convert("RGB")
        w, h = img.size

        print(f"  📐  Input:  {w}×{h}px")

        # Step 1 — Remove Gemini watermark
        img = remove_gemini_watermark(img, wm_height)
        print(f"  ✂️   Cropped bottom {wm_height}px, scaled back to {TARGET_W}×{TARGET_H}")

        # Step 2 — Final resize to exact target (already done in remove step, but ensure)
        if img.size != (TARGET_W, TARGET_H):
            img = img.resize((TARGET_W, TARGET_H), Image.Resampling.LANCZOS)

        if dry_run:
            print(f"  🔍  DRY RUN — would save to: {dest_path}")
            return True

        # Step 3 — Save as WebP
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        img.save(dest_path, format="WEBP", quality=WEBP_QUALITY, method=6)

        size_kb = dest_path.stat().st_size / 1024
        print(f"  💾  Saved:  {dest_path.relative_to(WEBSITE_ROOT)}  ({size_kb:.0f} KB)")

        return True

    except Exception as e:
        print(f"  ❌  Error: {e}")
        return False


def resolve_destination(stem: str) -> Path:
    """
    Maps a filename stem (e.g. 'hero-austin', 'hero-ai-chatbot') to
    its correct destination folder under PUBLIC_DIR.
    """
    if stem in US_CITIES:
        folder = US_CITIES[stem]
    else:
        folder = US_SERVICES_FOLDER

    return PUBLIC_DIR / folder / f"{stem}.webp"


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Process Gemini PNG images → clean WebP for FactoryJet website"
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=Path.home() / "Downloads",
        help="Folder to scan for PNG files (default: ~/Downloads)"
    )
    parser.add_argument(
        "--watermark-height",
        type=int,
        default=GEMINI_WATERMARK_HEIGHT,
        help=f"Pixels to crop from bottom to remove Gemini logo (default: {GEMINI_WATERMARK_HEIGHT})"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would happen without writing any files"
    )
    parser.add_argument(
        "--all-pngs",
        action="store_true",
        help="Process ALL .png files in source folder (not just known filenames)"
    )
    args = parser.parse_args()

    source_dir = args.source.expanduser().resolve()
    if not source_dir.exists():
        print(f"❌  Source folder not found: {source_dir}")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"  FactoryJet Image Processing Pipeline")
    print(f"{'='*60}")
    print(f"  Source:          {source_dir}")
    print(f"  Website root:    {WEBSITE_ROOT}")
    print(f"  Watermark crop:  {args.watermark_height}px from bottom")
    print(f"  Target size:     {TARGET_W}×{TARGET_H}px")
    print(f"  WebP quality:    {WEBP_QUALITY}")
    print(f"  Dry run:         {args.dry_run}")
    print(f"{'='*60}\n")

    # Find PNGs
    png_files = sorted(source_dir.glob("*.png")) + sorted(source_dir.glob("*.PNG"))

    if not png_files:
        print(f"⚠️   No PNG files found in {source_dir}")
        print(f"     Make sure your Gemini-generated images are in that folder.")
        sys.exit(0)

    print(f"Found {len(png_files)} PNG file(s):\n")

    processed = 0
    skipped   = 0
    errors    = 0

    for png_path in png_files:
        stem = png_path.stem.lower().strip()

        # Decide whether to process this file
        is_known = stem in US_CITIES or stem in KNOWN_SERVICE_FILES
        if not is_known and not args.all_pngs:
            print(f"⏭   Skipping '{png_path.name}' — not in routing table.")
            print(f"     (rename to match a known filename, or use --all-pngs)")
            skipped += 1
            continue

        dest = resolve_destination(stem)

        print(f"🖼   {png_path.name}")
        print(f"  📂  Dest:   {dest.relative_to(WEBSITE_ROOT)}")

        ok = process_image(png_path, dest, args.watermark_height, args.dry_run)

        if ok:
            processed += 1
        else:
            errors += 1
        print()

    # Summary
    print(f"{'='*60}")
    print(f"  Done.")
    print(f"  ✅  Processed: {processed}")
    print(f"  ⏭   Skipped:   {skipped}")
    print(f"  ❌  Errors:    {errors}")
    if not args.dry_run and processed > 0:
        print(f"\n  Next step:")
        print(f"  cd {WEBSITE_ROOT} && git add public/images && git commit -m 'feat: add AI service images'")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
