/**
 * Content for /uk/leeds.
 *
 * Everything the page renders as a list lives here as a plain array, for two
 * reasons that both bit this page before:
 *
 *  1. FAQPage JSON-LD is generated by mapping FAQS in page.tsx. There is no
 *     second hand-written FAQ array anywhere. The old build shipped a comment
 *     claiming "16 Q&As" over an array holding 12, which is exactly the drift
 *     this structure prevents.
 *  2. The rulebook's strongest citation signal is <li> density. Content held in
 *     arrays gets rendered as real <li>, not as <div> that merely looks like a
 *     list.
 *
 * House rules enforced in this file: no pricing figures of ours anywhere, no em
 * dashes, UK spelling, plain English. City statistics are economic data and are
 * allowed; they come from src/data/countries/gb/cities/leeds.json, the same
 * dataset the 15 templated UK city pages render.
 */

/* ── External sources, all fetch-verified 2026-08-25 (HTTP 200) ───────────── */
export const SOURCES = {
  googleSeoGuide: {
    href: 'https://developers.google.com/search/docs/fundamentals/seo-starter-guide',
    label: 'Google Search Central, SEO Starter Guide',
  },
  googleLocalRanking: {
    href: 'https://support.google.com/business/answer/7091',
    label: 'Google Business Profile Help, Tips to improve your local ranking on Google',
  },
  onsBusinesses: {
    href: 'https://www.ons.gov.uk/businessindustryandtrade/business/activitysizeandlocation/bulletins/ukbusinessactivitysizeandlocation/2025',
    label: 'ONS, UK Business: activity, size and location, 2025',
  },
} as const

/* ── What the retainer actually produces ──────────────────────────────────── */
export interface WorkGroup {
  title: string
  note: string
  items: string[]
}

export const WORK_GROUPS: WorkGroup[] = [
  {
    title: 'Technical SEO',
    note: 'The plumbing. If this is broken, nothing else you pay for can work.',
    items: [
      'Full crawl of every URL, with the errors ranked by how much traffic they cost',
      'Indexing check in Google Search Console, page by page, not site-wide averages',
      'Canonical tags, so two versions of one page stop competing with each other',
      'Redirect map with single hops only, because chained redirects lose crawlers',
      'Core Web Vitals work on the templates that carry your money pages',
      'Mobile rendering check on real page HTML, not a desktop preview',
      'XML sitemap and robots.txt that agree with each other',
      'Structured data that matches what a visitor can actually see on the page',
    ],
  },
  {
    title: 'Local SEO for Leeds',
    note: 'The part that decides whether you appear in the map results at all.',
    items: [
      'Google Business Profile filled in completely, categories included',
      'Opening hours, service areas and attributes kept current, not set once',
      'Name, address and phone number matched across every listing we can find',
      'Duplicate and abandoned listings claimed or removed',
      'Photos and products added on a schedule rather than in one burst',
      'Review requests built into your existing follow-up, plus replies to every review',
      'Service and area pages for the parts of Leeds and West Yorkshire you actually cover',
      'Local links from Leeds organisations you have a real connection to',
    ],
  },
  {
    title: 'On-page and content',
    note: 'What each page says, and whether it answers the question that brought someone there.',
    items: [
      'Keyword to page mapping, so one page owns one job',
      'Title tags and meta descriptions written for the click, not for a character count',
      'One H1 per page and a heading order that does not skip levels',
      'Answer-first opening paragraph on every commercial page',
      'Internal links added from pages that already have traffic',
      'FAQ blocks written from questions customers ask on the phone',
      'Thin or duplicate pages merged, redirected or rewritten',
      'Image alt text and file names that describe the image',
    ],
  },
  {
    title: 'Off-site and authority',
    note: 'Slow, manual, and the reason cheap SEO stalls after month three.',
    items: [
      'Link profile audit, including anything a previous agency built',
      'Disavow only where there is real evidence of harm, never as routine',
      'Digital PR angles based on things your business genuinely knows',
      'Trade body, supplier and partner listings that pass real signals',
      'Sponsorships and community links in Leeds, where they make sense',
      'Competitor link gap analysis against the sites currently outranking you',
    ],
  },
  {
    title: 'Measurement',
    note: 'You should be able to check our work without taking our word for it.',
    items: [
      'Google Analytics 4 and Search Console configured and checked, not assumed',
      'Conversion tracking on forms and calls before any ranking work starts',
      'Rank tracking split by Leeds searches and national searches',
      'Google Business Profile calls, direction requests and website clicks',
      'A monthly note in plain English saying what changed and what it means',
      'Everything in accounts you own, so the data stays yours if we part ways',
    ],
  },
  {
    title: 'AI search visibility',
    note: 'Being quotable when someone asks an assistant instead of typing a keyword.',
    items: [
      'Crawler access checked for the AI bots that read pages to answer questions',
      'Content restructured so a machine can lift a clean answer out of it',
      'Entity and organisation markup kept consistent across the site',
      'Facts stated plainly with a date, because stale pages get skipped',
      'Tracking of whether your brand gets named in AI answers for your terms',
    ],
  },
]

/* ── How an engagement runs ───────────────────────────────────────────────── */
export interface Phase {
  name: string
  window: string
  detail: string
  items: string[]
}

export const PHASES: Phase[] = [
  {
    name: 'Audit and baseline',
    window: 'First two weeks',
    detail:
      'We look before we touch anything. You get the findings whether or not you go ahead with the work.',
    items: [
      'Technical crawl and Search Console review',
      'Baseline rankings recorded for Leeds and national terms',
      'Current traffic and enquiry volume written down, so later claims can be checked',
      'Competitor set agreed with you, not chosen to flatter us',
    ],
  },
  {
    name: 'Fix the blockers',
    window: 'Weeks three to six',
    detail:
      'Errors that stop pages being indexed or ranked come first. This is unglamorous and it is where most of the early movement comes from.',
    items: [
      'Indexing and crawl errors cleared',
      'Redirect chains flattened to single hops',
      'Duplicate and competing pages resolved',
      'Google Business Profile completed and verified',
    ],
  },
  {
    name: 'Build the pages that earn',
    window: 'Weeks six to twelve',
    detail:
      'Once the site can be read properly, we work on the pages that are closest to money.',
    items: [
      'Service pages rewritten around one search job each',
      'Area pages for the parts of Leeds you serve, with real detail',
      'Internal links pointed at the pages you want ranking',
      'FAQ content added from your own customer questions',
    ],
  },
  {
    name: 'Earn authority',
    window: 'Month three onwards',
    detail:
      'Links and mentions are the slowest part and the hardest to fake. We would rather get a handful of real ones than a list of directories.',
    items: [
      'Digital PR and outreach on stories you can genuinely tell',
      'Local and trade listings that are worth having',
      'Partner and supplier links tidied up',
      'Ongoing content on the questions your buyers ask',
    ],
  },
  {
    name: 'Review and adjust',
    window: 'Every month',
    detail:
      'A short call and a written note. If something is not working we say so, rather than reporting on the parts that happen to be up.',
    items: [
      'What we did, in plain English',
      'What moved, and what did not',
      'What we are doing next month and why',
      'Anything we need from you',
    ],
  },
]

/* ── What moves, and roughly when. Rendered as a table, because two columns of
 *    paired values is what a table is for. Timeframes are ranges we have seen,
 *    not promises, and the last row is deliberately in the list. ──────────── */
export const TIMELINE_ROWS: { change: string; when: string }[] = [
  { change: 'Google Business Profile filled in properly', when: 'Often within weeks' },
  { change: 'Indexing and crawl errors cleared', when: 'As soon as Google recrawls' },
  { change: 'Click-through rate from better page titles', when: 'A month or two' },
  { change: 'Long-tail and area searches', when: 'Commonly three to six months' },
  { change: 'Competitive head terms in a city this size', when: 'Six months and up' },
  { change: 'A guaranteed ranking position', when: 'Never, from anyone' },
]

/* ── Scope boundaries ─────────────────────────────────────────────────────── */
export const INCLUDED: string[] = [
  'A named senior person doing the work, not an account handler passing it on',
  'Every account in your name, including Analytics, Search Console and your Google Business Profile',
  'A written scope agreed before the first invoice',
  'Monthly reporting you can read without a glossary',
  'Direct access to us by email, phone or WhatsApp during UK hours',
  'Full handover of documents and access if you leave',
]

export const NOT_INCLUDED: string[] = [
  'Bought links, private blog networks or anything that needs hiding from Google',
  'Ranking guarantees, because nobody can honestly offer one',
  'Reports that show impressions going up while enquiries stay flat',
  'Long lock-in contracts you have to argue your way out of',
  'Traffic targets for keywords that never lead to a sale',
  'Work billed for months when there is nothing worth doing',
]

/* ── Who this fits ────────────────────────────────────────────────────────── */
export const GOOD_FIT: string[] = [
  'You sell to customers in Leeds and West Yorkshire and want the phone to ring',
  'You have a site that works but almost no organic enquiries',
  'You lost traffic after a redesign or a platform move',
  'You are spending on Google Ads and want a channel that keeps running when the budget stops',
  'You need to show a board or a parent company what search is doing',
]

export const POOR_FIT: string[] = [
  'You need enquiries this month. Paid search will do that, SEO will not',
  'Nobody at your end can approve content or sign off changes',
  'You want a fixed ranking position written into a contract',
  'Your product has no search demand yet, in which case demand creation comes first',
]

/* ── Leeds specifics ──────────────────────────────────────────────────────── */
export interface Sector {
  name: string
  note: string
}

export const SECTORS: Sector[] = [
  {
    name: 'Financial and professional services',
    note: 'Leeds is the largest financial centre in the UK outside London, and HSBC UK moving its head office here brought a further 2,500 jobs. Search buyers in this sector check credentials before they enquire, so people pages, regulatory detail and case evidence do more work than a clever headline.',
  },
  {
    name: 'Legal services',
    note: 'A dense local market with national firms and high street practices bidding on the same terms. The winnable ground is almost always practice area plus location, not the head term everyone fights over.',
  },
  {
    name: 'Fashion and retail',
    note: 'From Victoria Quarter independents to online-only brands, this sector lives or dies on product and category pages. Faceted navigation, duplicate product URLs and thin category copy are the recurring problems.',
  },
  {
    name: 'Digital and technology',
    note: 'Around 12,000 tech jobs sit in the city and the sector keeps growing. These buyers read documentation, compare in detail, and rarely convert on a first visit, so the content has to hold up under scrutiny.',
  },
  {
    name: 'Health and care',
    note: 'Clinics and private practices need local visibility and clear, careful claims. Reviews and Google Business Profile completeness usually move the needle faster than anything on the website.',
  },
  {
    name: 'Trades and home services',
    note: 'Coverage across Leeds and the surrounding towns is the whole game. One page that lists thirty areas ranks for none of them. Fewer, genuinely written area pages beat a long list every time.',
  },
]

export const AREAS: string[] = [
  'Leeds City Centre',
  'Headingley',
  'Chapel Allerton',
  'Horsforth',
  'Roundhay',
  'Armley',
  'Beeston',
  'Garforth',
  'Morley',
  'Pudsey',
  'Otley',
  'Wetherby',
]

export const DISTRICTS: string[] = [
  'Leeds Dock',
  'Wellington Place',
  'South Bank',
  'Victoria Quarter',
  'Park Row',
  'Thorpe Park',
  'White Rose Office Park',
  'Kirkstall Forge',
]

export const NEARBY: string[] = [
  'Bradford',
  'Wakefield',
  'Harrogate',
  'Huddersfield',
  'Halifax',
  'Castleford',
  'Dewsbury',
  'York',
  'Ilkley',
  'Selby',
]

/* ── FAQs. 25 questions, written the way a business owner asks them. ───────
 * page.tsx maps THIS array into FAQPage JSON-LD. Do not create a second copy.
 */
export interface Faq {
  q: string
  a: string
}

export const FAQS: Faq[] = [
  {
    q: 'What does an SEO agency in Leeds actually do all month?',
    a: 'Three things, in this order. It fixes the technical faults stopping Google reading your site properly. It improves the pages closest to a sale, so they answer the question people search. Then it earns links and mentions from other sites, which is the slow part. Anything that does not fall into one of those three buckets is usually filler.',
  },
  {
    q: 'How much does SEO cost in Leeds?',
    a: 'It depends on how many pages you have, how competitive your terms are and how much is already broken. We scope it on a short call and send a written proposal before any work starts. Most engagements run either as a one-off audit with a fix list you can hand to anyone, or as a monthly retainer. You will know the full figure before you commit to anything.',
  },
  {
    q: 'How long before I see results?',
    a: 'Google says it plainly: some changes take effect in a few hours, others can take several months. In practice, technical fixes and Google Business Profile work often show inside four to eight weeks. Competitive organic rankings usually take six months or more. Anyone promising page one in thirty days is either lucky or lying.',
  },
  {
    q: 'Can you guarantee I will rank number one?',
    a: 'No, and neither can anyone else. Google is clear that there are no secrets that will automatically rank a site first. What we can commit to is the work itself: what gets done, when it gets done, and what we expect it to move. If an agency offers you a guaranteed position, ask them what happens contractually when it does not happen.',
  },
  {
    q: 'Do I actually need a Leeds agency, or does location not matter?',
    a: 'For the work itself, location does not matter. Nobody needs to be in the room to fix a canonical tag. What matters is whether the team understands your market and answers the phone. Where local knowledge does help is area pages and local link building, because knowing that Wetherby and Morley are different markets stops you writing one page for both.',
  },
  {
    q: 'We already show up on Google Maps. Do we still need SEO?',
    a: 'Probably yes, for two reasons. Map results only cover searches with local intent, so anything researched rather than urgent goes to the normal results instead. And map position moves with distance from the searcher, so you may be visible in Headingley and invisible in Morley. Check by searching from different parts of the city, not just your office.',
  },
  {
    q: 'What is local SEO and how is it different from normal SEO?',
    a: 'Local SEO is the work that gets you into the map results and into searches with a place attached. It centres on your Google Business Profile, consistent listings, reviews and area pages. Normal SEO is about ranking pages in the standard results. Most Leeds businesses need both, but local usually pays back faster.',
  },
  {
    q: 'How do I get into the map pack for Leeds searches?',
    a: 'Google says local results are ranked on three things: relevance, distance and prominence. Relevance is how well your profile matches the search. Distance is how far you are from the person searching. Prominence is how well known you are, which is influenced by links, articles and reviews. You can only really control relevance and prominence, so start there.',
  },
  {
    q: 'Someone else built my website. Can you still do the SEO?',
    a: 'Yes. Most of what we do is content, structure and access, none of which needs the original developer. If the site is on a platform that blocks basic changes such as page titles or redirects, we will tell you that on the first call rather than three months in. We work with WordPress, Shopify, Webflow, Squarespace and custom builds.',
  },
  {
    q: 'What access do you need from us?',
    a: 'Google Search Console, Google Analytics, your Google Business Profile, and a login for the website content. All of it stays in accounts you own, with us added as a user we can be removed from. If any of those accounts do not exist yet, we set them up in your name. We never hold your data in an account only we can open.',
  },
  {
    q: 'What happens in the first month?',
    a: 'We crawl the site, review Search Console, record where you currently rank and how many enquiries you get, and agree the competitor set with you. Then you get a fix list ranked by likely impact. Some of it we do, some of it you may prefer to hand to your own developer. Either is fine.',
  },
  {
    q: 'Do you write the content or do we have to?',
    a: 'We write it. You review it. The parts we cannot invent are the ones only you know: the objections you hear on the phone, why a job went wrong, what a client actually asked. A short call a month gives us that, and it is the difference between content that sounds like everyone else and content worth reading.',
  },
  {
    q: 'Do you build links, and are they safe?',
    a: 'We earn links rather than buy them. That means digital PR, trade and supplier relationships, local sponsorships and genuinely useful content. We do not use link networks or paid placements. They work briefly, then they cost you more to clean up than they ever returned. If a previous agency built them, we audit what is there first.',
  },
  {
    q: 'How will I know it is actually working?',
    a: 'We set up conversion tracking before any ranking work starts, so enquiries and calls are counted from day one. Monthly reporting shows rankings split between Leeds searches and national ones, organic enquiries, and Google Business Profile calls and direction requests. If impressions rise but enquiries do not, we say so rather than leading with the flattering number.',
  },
  {
    q: 'Do I have to sign a long contract?',
    a: 'No. Audits are one-off pieces of work. Retainers run month to month with a notice period, not a twelve month tie-in. SEO does need time to pay back, and we will say that honestly, but the way to earn a second month is to be worth keeping rather than to be difficult to leave.',
  },
  {
    q: 'If we stop after six months, do the rankings disappear?',
    a: 'Not immediately. Technical fixes, content and links stay in place and keep working. What stops is the compounding: no new pages, no new links, and no response when a competitor overtakes you or Google changes something. Sites usually hold position for a while, then drift. It is a slow decline, not a switch.',
  },
  {
    q: 'We are a trade business covering Leeds and the towns around it. Can we rank in more than one area?',
    a: 'Yes, but not with one page listing thirty places. That ranks for none of them. It needs a real page per area you genuinely serve, with detail specific to that place, and it works best where you have some proof of working there. We would rather build six good area pages than thirty thin ones.',
  },
  {
    q: 'We sell nationally from Leeds. Is local SEO still relevant?',
    a: 'Partly. Your Google Business Profile still helps for brand searches and for buyers checking you are a real company. But the bulk of the work moves to national terms, which are harder and slower. We would separate the two in reporting so a healthy local picture does not hide a weak national one.',
  },
  {
    q: 'Someone cold-called saying our Google listing needs fixing. Is that real?',
    a: 'Almost always no. Google does not cold-call small businesses to sell listing fixes. These calls usually push a paid service for something you can do yourself in your Google Business Profile, or they are trying to get access to your account. Do not give anyone access over the phone. Check the profile yourself while you are on the call.',
  },
  {
    q: 'What is AI search and does it change what SEO means?',
    a: 'It means people ask ChatGPT, Gemini or Google AI Overviews a question instead of typing keywords, and get an answer with a few sources. The honest position is that it is mostly ordinary good SEO plus being easy to quote: clear structure, plain answers, facts stated with a date. Anyone selling it as a separate secret discipline is overselling.',
  },
  {
    q: 'Our traffic dropped after a redesign. Can you fix it?',
    a: 'Usually yes, and this is one of the more fixable problems. It is nearly always the redirect map: old URLs pointing nowhere, or chained through two or three hops. We map every URL that used to have traffic against where it went, repair the gaps, and watch Search Console daily until coverage recovers. Speed matters, so bring it to us early.',
  },
  {
    q: 'Do you work with online shops in Leeds?',
    a: 'Yes. E-commerce SEO is a different job from a brochure site because the problems live in category pages, filters and product URLs rather than in blog posts. We work on Shopify, WooCommerce and headless setups. The first thing we usually look at is how many near-duplicate URLs your filters are generating.',
  },
  {
    q: 'What do you need from us each month?',
    a: 'Around an hour. A short call so we can ask about jobs you have won or lost, someone to review content within a few days, and a heads up when something changes in the business such as a new service or a location. Clients who give us that hour get noticeably better work than clients who do not.',
  },
  {
    q: 'How do you report on the work?',
    a: 'A written note each month plus a short call if you want one. It covers what we did, what moved, what did not, and what is next. It is written in plain English, not exported from a tool. You also keep live access to Analytics and Search Console, so you can check anything yourself at any point.',
  },
  {
    q: 'How do we start?',
    a: 'Send a short brief or book a call. We look at your site, your Search Console data and who currently ranks for your terms, then tell you what we think is realistic and what it would take. If the honest answer is that paid search suits you better right now, we will say that. No obligation and no pressure on the call.',
  },
]

/* ── The rest of the work. /uk/web-design, /uk/ecommerce-development and
 *    /uk/shopify-development all link to this page, so the page has to answer
 *    those visitors too rather than pretending it only does search. ──────── */
export const OTHER_SERVICES: { name: string; note: string; href: string; cta: string }[] = [
  {
    name: 'Website builds and rebuilds',
    note: 'Fast, custom sites rather than a theme you spend a year fighting. Built so the search work has something solid to stand on: clean markup, sensible URLs and pages that load quickly on a phone in a car park.',
    href: '/uk/web-design',
    cta: 'Web design in the UK',
  },
  {
    name: 'Online stores',
    note: 'Shopify, WooCommerce and headless builds. The platform recommendation follows your catalogue size, your trade rules and what has to connect to your stock system, not what we prefer to build.',
    href: '/uk/ecommerce-development',
    cta: 'E-commerce development in the UK',
  },
  {
    name: 'Shopify work',
    note: 'Theme builds, migrations from another platform, and the technical clean-up that stops filters generating thousands of near-identical URLs. Common for Leeds fashion and retail brands selling well beyond the city.',
    href: '/uk/shopify-development',
    cta: 'Shopify development in the UK',
  },
  {
    name: 'AI agents',
    note: 'Software that handles repetitive operational work: answering routine enquiries, syncing stock between channels, chasing quotes. Useful when a small team is the bottleneck. Not a replacement for people making judgement calls.',
    href: '/uk/ai-agents',
    cta: 'AI agents in the UK',
  },
]

/* ── National hubs for internal linking ───────────────────────────────────── */
export const UK_HUBS: { label: string; href: string }[] = [
  { label: 'SEO', href: '/uk/seo' },
  { label: 'Local SEO', href: '/uk/local-seo' },
  { label: 'SEO audit', href: '/uk/seo-audit' },
  { label: 'E-commerce SEO', href: '/uk/ecommerce-seo' },
  { label: 'Shopify SEO', href: '/uk/shopify-seo' },
  { label: 'AI SEO', href: '/uk/ai-seo' },
  { label: 'Web design', href: '/uk/web-design' },
  { label: 'E-commerce development', href: '/uk/ecommerce-development' },
  { label: 'Shopify development', href: '/uk/shopify-development' },
  { label: 'AI agents', href: '/uk/ai-agents' },
]
