import { BlogPost } from './data.types';

export const POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'how-ai-websites-save-money',
    title: 'How AI Websites Save ₹50k/Year',
    excerpt: 'Discover the transformative power of artificial intelligence in modern manufacturing web presence. Learn how automated customer service and predictive analytics are cutting costs drastically.',
    category: 'Emerging Tech',
    author: 'Amit Verma',
    date: 'Oct 24, 2024',
    readTime: '8 min read',
    imageUrl: 'https://picsum.photos/id/4/800/600',
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'seo-2026-dominating-local-search',
    title: 'SEO in 2026: Dominating Local Search',
    excerpt: 'The landscape of search engines is shifting. Here is how your factory can stay visible to local distributors.',
    category: 'Web Design & Strategy',
    author: 'Sarah Jenkins',
    date: 'Oct 22, 2024',
    readTime: '5 min read',
    imageUrl: 'https://picsum.photos/id/20/600/400',
  },
  {
    id: '3',
    slug: 'local-business-growth-strategies',
    title: 'Local Business Growth Strategies',
    excerpt: 'Proven tactics to expand your manufacturing footprint in tier-2 cities across India.',
    category: 'Web Design & Strategy',
    author: 'Rajesh Kumar',
    date: 'Oct 20, 2024',
    readTime: '6 min read',
    imageUrl: 'https://picsum.photos/id/48/600/400',
  },
  {
    id: '4',
    slug: 'smart-automation-for-smes',
    title: 'Smart Automation for SMEs',
    excerpt: 'Why small to medium enterprises are adopting robotics faster than ever before.',
    category: 'Emerging Tech',
    author: 'Priya Singh',
    date: 'Oct 18, 2024',
    readTime: '4 min read',
    imageUrl: 'https://picsum.photos/id/60/600/400',
  },
  {
    id: '5',
    slug: 'textile-giant-goes-digital',
    title: 'Case Study: Textile Giant Goes Digital',
    excerpt: 'A deep dive into how a 50-year-old textile mill modernized its entire supply chain.',
    category: 'Web Design & Strategy',
    author: 'Vikram Malhotra',
    date: 'Oct 15, 2024',
    readTime: '10 min read',
    imageUrl: 'https://picsum.photos/id/119/600/400',
  },
  {
    id: '6',
    slug: 'future-of-b2b-procurement',
    title: 'The Future of B2B Procurement',
    excerpt: 'Digital marketplaces are replacing traditional vendor relationships. Is your business ready?',
    category: 'E-Commerce Development',
    author: 'Anjali Gupta',
    date: 'Oct 12, 2024',
    readTime: '7 min read',
    imageUrl: 'https://picsum.photos/id/180/600/400',
  },
];